Shine1594
code-squad/javascript-todo pull request #1
Opened 2017-10-23 03:36 UTC by shine1594

level3 test에 작성했던 todo app을 refactoring했습니다.

리뷰 부탁드립니다 :)

2017-10-23 08:45 UTC, crongro requested changes
설계를 하고 진행하시고요. 
설계를 하면서 아래 리뷰와 함께 어색한 구조는 없는지 수정해보세요.

2017-10-23 08:45 UTC, nigayo commented on task.js
> +    var functions = [
여기 함수들이 배열안에 있어서, postfixes와 순서가 맞아야 하는건 좀 이상한거 같아요.

2017-10-23 08:45 UTC, nigayo commented on task.js
> +        function getDiffWeeks(start, end) {
아래 getDiffXXX () 함수들은 모두 중복인거 같네요. 해결할 수 있을까요?

2017-10-23 08:45 UTC, nigayo commented on task.js
> +var getTimeDiff = (function() {
getTimeDiff 라는 녀석은 task.js 에 있는게 맞을까요? 그 성격이 유틸리티 같기도 한데요. 고민해서 수정해보면 좋겠네요

2017-10-23 08:45 UTC, nigayo commented on task.js
> +    this.startAt;
기본값을 보통 설정하는게 일반적이에요.

2017-10-23 08:45 UTC, nigayo commented on app.js
> +    add: function(content) {
이름은 그냥 add보다 더 자세한 이름으로 수정.

2017-10-23 08:45 UTC, nigayo commented on app.js
> +        var counts = {};
이게 필요한가요? this.taskList 가 실제 데이터를 가지고 있으니, 그걸 대표 데이터(state)로 관리하면서 바로 가져다가 쓰는건 어때요?

2017-10-23 08:45 UTC, nigayo commented on interpreter.js
> +    commandList: [
commandList는 좋은 거 같아요.

2017-10-23 12:29 UTC, shine1594 commented on app.js
> +        var counts = {};
네. app객체에서 상태값도 가지고 있는게 좋을것 같네요. 수정하도록 하겠습니다.

2017-10-23 12:31 UTC, shine1594 commented on app.js
> +    add: function(content) {
```javascript
rl.on('line', function(input) {
    try {
        var result = interpreter.execute(input);
        app[result.commandName].apply(app, result.params);
    } catch(exception) {
        console.log(exception);
    }
});
```

이런식으로 command명과 매칭되는 함수를 바로 실행하려는 의도로 naming하였는데 안좋은 방법인가요??

2017-10-23 12:32 UTC, shine1594 commented on task.js
> +    var functions = [
postfix와 function을 가지는 객체의 배열로 수정해보겠습니다:)

2017-10-23 14:00 UTC, shine1594 commented on task.js
> +        function getDiffWeeks(start, end) {
두 시간의 차이를 계산할 때, n초(seconds) ~ n주(weeks)단위로 계산하는 경우에는 두 시간 차의 miliseconds값을 알맞은 단위로 나눠주기만 하면 되기 때문에 함수를 재사용할 수 있습니다. 그런데 월(month)나 년(year)단위로 계산하려면  두 시간 차의 miliseconds값을 특정 값으로 나눠서 계산할 수 없습니다.(30일 / 31일, 윤년 / 평년 이슈) 따라서 비교하고자 하는 시간의 1년 혹은 1달 후의 시간값과 비교해야되기 때문에 로직이 모두 같지 않아서 함수를 재사용하지 못했습니다.

2017-10-24 03:29 UTC, shine1594 commented
flowchart랑 클래스 다이어그램 작성해봤는데 리뷰 부탁드릴게요 :)

2017-10-24 05:48 UTC, crongro requested changes
설계 잘 하셨어요. 
코드 변경이 필요할때 설계와 개발간의 sync를 꾸준히 맞춰보세요.

코멘트 확인해보시고, 고민도 해보시고,실험도 하면서
좀더 개선해보세요.

2017-10-24 05:48 UTC, crongro commented on skeleton.js
> +    var id = 0;
getNextId  함수는 그냥 this.id++ 이렇게 하면 안돼요?

2017-10-24 05:48 UTC, nigayo commented on app.js
> +    add: function(content) {
함수이름이 아닌 키값으로 사용되는 것이군요. 
좋아요~!

2017-10-24 05:48 UTC, nigayo commented on interpreter.js
> +        var commandIndex = this.commandList.findIndex(function (item) {
findIndex동작을 이해하고 polyfill 을 간단하게 만들어볼래요? 
요 메서드가 브라우저 지원상황이 좋지 않습니다.

2017-10-24 05:48 UTC, nigayo commented on interpreter.js
> +var interpreter = {
validator 역할인데 이름만 봐서는 잘 뭔지 몰랐네요.
validator 를 이렇게 구분해서 모듈을 만든건 좋은 거 같네요.

2017-10-24 05:48 UTC, nigayo commented on app.js
> +            throw `${status}상태의 task가 존재하지 않습니다.`;
error 면 new Error 로 해주는 게 좀더 직관적인 거 같아요.
알림메시지를 표현하는 것이면 throw를 던지지 말고  그냥 비정상 return값을 주어도 괜찮을거 같네요.

2017-10-24 05:48 UTC, nigayo commented on common.js
> +statusConstant.getList = (function () {
utility같기도 하고, common 이라는것이 명확한 역할이 애매해서인지 이함수의 위치가 별로인거 같아요.
앞으로 common에 어떤걸 추가해야하지? 할때도 좀 명확한거 같지 않아요.

2017-10-24 05:48 UTC, nigayo commented on utils.js
> +var getTimeDiff = (function() {
utilis 가 아니고 timemanager같은 느낌이군요.
진짜 utilis가 필요하면 만들어두고 재사용하면 좋겠네요.

2017-10-24 05:48 UTC, nigayo commented on interpreter.js
> +var interpreter = {
interpreter 구조는, 객체-배열-객체 이런구조인데.. 이렇게 바꿀 수도 있겠어요.

 ```javascript
var interpreter = {
   validator : { 
      show : function(){
      },
	  add : function(){
      }
   }
}
```

2017-10-24 06:37 UTC, shine1594 commented on app.js
> +            throw `${status}상태의 task가 존재하지 않습니다.`;
네 Error객체 생성해서 throw하는게 좋을 것 같습니다.

2017-10-24 06:40 UTC, shine1594 commented on interpreter.js
> +var interpreter = {
네 이 구조가 더 직관적인것 같습니다 👍

2017-10-24 06:43 UTC, shine1594 commented on skeleton.js
> +    var id = 0;
``` javascript
function Task(content) {
    this.id = this.getNextId();
    ...

```

이렇게 task객체가 생성될때 고유한 id값을 부여하기 위해 만든 메서드입니다.

2017-10-24 06:44 UTC, shine1594 commented on utils.js
> +var getTimeDiff = (function() {
utilis에 다른 function들 추가해나가도록 하겠습니다.

2017-10-24 07:59 UTC, shine1594 commented
리뷰 받은 내용 반영했습니다!

2017-10-24 08:23 UTC, shine1594 commented
완료하기까지 가장 시간이 적게 걸린 task를 저장하고 보여주는 기능까지 추가하였습니다:)

2017-10-26 00:05 UTC, crongro approved these changes

2017-10-26 00:06 UTC, merged