Step4-2 mission hyodol & YM
code-squad/javascript-todo pull request #102
Opened 2019-04-19 08:26 UTC by bestdevhyo1225

Step4-2 mission hyodol & YM
직전에 실수로 master에 PR 했습니다... ^_^.....죄송합니다.

2019-04-20 00:52 UTC, nigayo commented
Implement 라는 커밋 prefix는 좀 전 낯선데요. (잘모르겠음 다른데서 쓸수도 있죠)
이 단어는 사실 모든 코드가 구현이라 두리뭉실표현이라고 생각해요. ㅎㅎ
다른 것을 쓰는 게 어때유?

2019-04-20 00:56 UTC, crongro requested changes
수고했어요.
잘 구현했고요.

크게 두 가지를 개선하면 좋겠습니다
- add/update/delete 등 주요 함수를 하위함수(subroutine이라고 함)로 분리해보세요.
- for문말고 배열의 고차함수를 조금더 활용해보세요.

(화이팅)

2019-04-20 00:56 UTC, nigayo commented on Step4_2_control_command.js
> +    setTimeout( () => { processQuery['show'](['all']); }, 1000 );
1000은 인자로 받으면 더 범용적임 함수가 되겠죠?

2019-04-20 00:56 UTC, nigayo commented on Step4_2_control_command.js
> +    return ['all', 'todo', 'doing', 'done'].some( (status) => { return currentStatus === status } );
오 맘에 드는 코드네요. 
some도 쓰고~ 배열을 잘활용하셨고.
👍

2019-04-20 00:56 UTC, nigayo commented on Step4_2_control_command.js
> +const processQuery = {
객체리터럴은 싱글톤패턴이기도 해요. js에서는 이렇게 아주 쉽게 객체를 생성할 수 있는 장점이 있죠.

2019-04-21 05:18 UTC, bestdevhyo1225 commented
피드백 주신 내용을 토대로 수정했습니다!
1. show / add / delete / update 주요 함수를 서브 루틴으로 분리하고 메인 루틴에서 명령어를 관리하도록 수정했습니다.
2. Step4_2_process_data.js 부분에서 배열이나 객체에 접근할 때 for ..of 방식을 reduce, filter, map 을 사용하여 수정했습니다.

2019-04-22 04:39 UTC, bestdevhyo1225 commented
1. 유효성 체크하는 기능 모듈로 분리
2. 랜덤 ID 를 발생시키는 기능 모듈로 분리

2019-04-22 06:16 UTC, crongro approved these changes
승인은 합니다만 ㅎㅎ 
리뷰내용은 기억하시고, 공부하세요! 
수고하셨습니다.

2019-04-22 06:16 UTC, nigayo commented on Step4_2_control_command.js
> +const showCompletionStatus = (milliSecond) => {
단위를 변수명에 준것은 의미있고 좋아요. 하지만 맥락이 포함되면 더 좋겠죠?
delayTime 이라던가 하는 식으로요.

2019-04-22 06:16 UTC, nigayo commented on Step4_2_control_command.js
> +    const inputTag  = paramArr[1].split('["').join('').split('"]').join('');
아 좀 보기 어렵네요 ㅎㅎ 뭔지는 알겠습니다.
이런 파싱은, replace메서드를 사용하면서 정규표현식으로 치환시키는 방법도 있으니, 한번 공부해보세요.

2019-04-22 06:16 UTC, nigayo commented on Step4_2_control_command.js
> +    } else {
단순 if/else 구조의 코드는 else를 생략할 수도 있죠.

2019-04-22 06:16 UTC, nigayo commented on Step4_2_control_command.js
> +    const findId = processData.getTodoId(inputId);
findId.  id를 찾는 함수! 
아니라면 수정을..

2019-04-22 06:16 UTC, nigayo commented on Step4_2_control_command.js
> +            if (!validate.checkIdForm(paramArr[0])) return print.errorMessage('id');
참고.

코드에서 배열의 순서를 그대로 활용하는건 약간의 위험부담이 있죠. (paramArr[1]...)
배열의 순서가 바뀌거나 변경될 수 있으니까요.
객체를 사용한다면 이를 좀더 보완해줄 수 있을거에요.

2019-04-22 06:16 UTC, nigayo commented on Step4_2_process_data.js
> +    return todoList.map( (object) => { return object['id']; } );
Object라는 네이티브 메서드가 있으니, obj 라고 줄여서 쓰는 게 낫겠습니다.

2019-04-22 06:16 UTC, nigayo commented on Step4_2_print_message.js
> +const errorMessage = (keyword) => {
음 이부분은 switch문도 쓸 수 있지만, 
객체리터럴을 활용하는 것도 좋아보이네요.

2019-04-22 06:16 UTC, merged