andole, wook 제출
code-squad/javascript-todo pull request #103
Opened 2019-04-20 01:58 UTC by andole87

나름대로 CRUD 기능을 구현하려고 했는데, this에서 막혔습니다.

this를 that으로 바인딩하는 패턴도 적용해봤는데 잘 안되었어요. 😢 

전역 함수들 가지고 앱 구성해봤습니다..

2019-04-20 23:09 UTC, wo0kgod commented
저희 파일이 많은데... app.js만 봐주시면 됩니다!!!!

2019-04-21 00:48 UTC, pocokim reviewed
코드를 짜면서 여쭤보고 싶었던 부분을 표시하였습니다!

2019-04-21 00:48 UTC, pocokim commented on app.js
> +        if(filteredData === data){todo_shell.showCurrentStatus()}
showTodo함수에서 filterArg를 실행후 조건에 맞게 showCurrentStatus , showFilteredTodo 실행하도록 하였는데요. 
이부분에서 if-else문을 사용하였는데 ..  if -else 문 말고 다른 방법으로 해결할 수는 없을지 여쭤보고 싶습니다.

2019-04-21 00:48 UTC, pocokim commented on app.js
> +const data = require('./database.json');
require로 가져오는 변수는 전역에 선언하는것이 좋은가요? 

예를들어 data의 경우 todo_shell에서 사용되는 데이터기때문에
todo_shell.data = require('./database.json')으로 선언하는것이 의미상 맞는게 아닐까? 라는 생각이 들었습니다.

2019-04-21 00:48 UTC, wo0kgod commented on app.js
> +    updateTodo: function (objId, objKey, objValue) {
저희의 addTodo , updateTodo , deleteTodo 는 database.json 파일의 json을 가져와서 그 배열에 직접 접근을 합니다. 
push로 객체를 추가하고, forEach문을 돌면서 key에 맞는 value를 수정하고, splice로 객체를 삭제하였습니다. 

그런데 함수가 return은 없고 이렇게 데이터를 바꾸기만 하니 이게 일반적으로 많이 사용되는 패턴인가(?) 싶어서.. 정상적인 방법인지 여쭤보고 싶습니다.

그렇다고 변경한 데이터를 return 하는 방법으로 짜는게 사실 어려워보였구요.
그냥 원본 데이터를 바꾸는게 더 쉬워보였네요 ㅠㅠ

2019-04-21 00:48 UTC, wo0kgod commented on app.js
> +        return todo_shell[commandArg+"Todo"](...deliveryArg);
추가적으로 원래는 todo_shell 객체안에 COMMAND_DICT 객체를 만들어 커맨드에 맞게 들어왔을때 COMMAND_DICT의 key에 연결된 함수를 실행하고자 하였으나..
객체안에서 객체를 key로 연결하고 함수를 실행하려고 하니 COMMAND_DICT안이 todo_shell이 undefined가 되었습니다.
이 부분을 어떻게 해결하는것이 좋을까요?

parseCommand안에서는 todo_shell객체의 메소드를 부르는게 가능한데 
왜 COMMAND_DICT에서 todo_shell.showTodo가 undefined가 되는지 이유를 모르겠습니다 ㅠㅠ

2019-04-21 13:41 UTC, wo0kgod commented on app.js
> +        return todo_shell[commandArg+"Todo"](...deliveryArg);
해결방법을 찾았는데요. todo_shell 밖에 COMMAND_DICT 객체를선언하면 되었습니다만...
여전히 이유를 모르겠네요 ㅠ

2019-04-21 13:43 UTC, wo0kgod commented on app.js
> +todo_shell.run();
추가적으로 todo_shell.js 와 app.js로 나눠서 모듈화할 수는 있었지만.. app.js가 한줄이라.. 그냥 이렇게 구현하였습니다.

2019-04-22 05:15 UTC, nigayo commented on app.js
> +const data = require('./database.json');
아뇨 전역객체나 함수그대로 두고 사용하는게 일반적이죠.
todo_shell.data는 일반적이지 않고 어색합니다. database.json이 객체를 이미 반환하도록 하는게 맞고요.

todo_shell= require('./database.json')
 console.log(todo_shell.data) //이렇게 접근한다던가.

2019-04-22 05:16 UTC, nigayo commented on app.js
> +    updateTodo: function (objId, objKey, objValue) {
함수는 보통  값을 반환할 수 있지만, 그렇지 않을 수도 있죠.
후자의 경우 프로그래밍에서는 procedures 라고도 합니다.

2019-04-22 05:17 UTC, wo0kgod commented on app.js
> +    updateTodo: function (objId, objKey, objValue) {
크... 감사합니다.

2019-04-22 05:20 UTC, nigayo commented on app.js
> +        return todo_shell[commandArg+"Todo"](...deliveryArg);
글쌔요~ 좀더 고민해보세요. 디버깅도 해보시고요.

2019-04-22 05:20 UTC, wo0kgod commented on app.js
> +    updateTodo: function (objId, objKey, objValue) {
이게 그 ... 절차적 프로그래밍 이라는거군요..

2019-04-22 05:21 UTC, nigayo commented on app.js
> +todo_shell.run();
모듈화가 반드시 필요한 건 아니겠죠. 
스스로 이유를 찾고 판단해서 사용하면 됩니다. 
중요한 건 내 코드에 대한 설명이 가능한것이죠.

2019-04-22 05:33 UTC, crongro requested changes
리뷰드린 거 수정해보세요.

그리고, 이번 것과 관련없는 코드들은 모두 제거하세요. 
todo.js/app.js/apps.js... 이렇게 비슷한 코드를 만들어서 버전관리하지 말고 
git branch를 사용하고, commit을 좀더 잘하는 습관을 가지세요.

2019-04-22 05:33 UTC, nigayo commented on app.js
> +const todo_shell = {
shell 이라는 단어가 전 좀 어색하네요. 셀프로그래밍이 떠오르는 거 같고, 모호해보이네요.

2019-04-22 05:33 UTC, nigayo commented on app.js
> +    showCurrentStatus: function(){
showcurrentstatus보면,  
배열 -> 새로운배열 -> 객체 -> 새로운배열 -> 문자열
이런 과정으로 최종 결과를 출력하는데요.

불필요한 변형은 없을까요?  다시말해서, 데이터 구조변경을 좀더 줄일 수 없을까요?

2019-04-22 05:33 UTC, nigayo commented on app.js
> +    showFilteredTodo : function(_filteredData){
_filteredData 이녀석은왜 언더바를 특별히 붙인 걸까요? 같은이유로 다른 코드에서도 이 규칙을 사용한건가요?

2019-04-22 05:33 UTC, nigayo commented on app.js
> +            todo[arg[0]] === arg[1]
filterArg함수를 읽으면서 arg0,arg1 이 무엇인지  알기 어렵네요.
알 수 있도록 수정해보세요.

2019-04-22 05:33 UTC, nigayo commented on app.js
> +        if(filteredData === data){todo_shell.showCurrentStatus()}
filteredData가 data 랑 비교가 되는데, 비교대상이 그냥 'data' 라고 하니 무엇과 비교되는 코드인지 알수가 없습니다.

2019-04-22 05:33 UTC, nigayo commented on app.js
> +        if(filteredData === data){todo_shell.showCurrentStatus()}
if문이 많은 것도 아니고, 필요하면 사용해야죠 .
대체로 조건문은 객체매핑을 해두면 없앨수는 있습니다. (고민해보세요)

2019-04-22 05:33 UTC, nigayo commented on app.js
> +        return Math.abs((inputString + Date.now()).split("").reduce(function (a, b) { a = ((a << 5) - a) + b.charCodeAt(0); return a & a }, 0));
좀 가로로 긴~ 코드라 보기 어렵네요.
하위함수로 좀더 분리해서 함수이름으로 의도를 추상적으로 표현해보세요.

2019-04-22 06:11 UTC, wo0kgod commented on app.js
> +    showCurrentStatus: function(){
reduce 보다 map 을 사용하는것이 좋음

2019-04-22 06:35 UTC, nigayo commented
다시 다 수정하신건가요? 
수정하면서 커밋하시고, 다 완료됐으면 그때 push 해주세요!
@andole87 @wo0kgod

2019-04-22 06:55 UTC, wo0kgod commented
네 알겠습니다!

2019-04-22 09:01 UTC, crongro approved these changes
좋습니다.
이번에 배운 것을 다음단계에서 많이 활용해보세요!

2019-04-22 09:01 UTC, crongro commented on app.js
> +            todo_cli_interface.showFilteredTodo(database.filter(v => v[filterKey] === filterValue));
this.showFilteredTodo 로 호출할 수 있긴해요.
객체와 this를 이번주에 배우면서 이해해보세요.

2019-04-22 09:01 UTC, nigayo commented on app.js
> +                database.splice(i, 1);
database라는 이름도 너무 일반적인 이름이라 적절하진 않아보여요.
어떤 데이터인가요? 그 데이터 이름으로 표현해보세요.

2019-04-22 09:02 UTC, merged