step-5-2 : TUNA, YM
code-squad/javascript-todo pull request #112
Opened 2019-04-25 09:53 UTC by dev-dongwon

## step 5-2 : 프로토타입 패턴 이용해 todo 앱 구현하기
### 참가자
- YM, TUNA
### 클래스
- app.js : 어플리케이션 구동을 위한 프로그램
- utils.js : 반복 및 유틸성 메서드를 모아놓은 유틸
- commandParser.js : 명령어 파싱 및 instruction 객체로 명령어 전달
- instruction.js : 명령어를 받아 각 명령어에 맞는 function 수행
- exceptionHandling.js : 각 상황에 맞는 에러 객체를 만들어 throw

2019-04-26 00:43 UTC, nigayo commented
commit log 를 아주 잘 쓰셨군요!! 습관 잘 유지하세요.

2019-04-26 00:50 UTC, crongro requested changes
전체적으로 객체분리/ 함수등 잘 구현했고요.

리뷰남긴 부분은 공부&수정하시고 다시 commit/push 부탁드려요!

2019-04-26 00:50 UTC, nigayo commented on oop/app.js
> +function Program() {
생성자 이름이 너무 대명사네요. 구체적인 역할로 다시 지어보세요.

2019-04-26 00:50 UTC, nigayo commented on oop/app.js
> +            const cmdList = CommandParser.prototype.getCmdList(userInput);
no no !

prototype객체를 직접 접근해도 되지만, 객체를 생성하고 그걸 사용해야죠
이렇게 구현하게 된 이유가 아마도, 객체 속성이 없기 때문이긴하죠. 속성이 필요한 부분이 있는지 살펴보고, CommandParser 생성자에 추가해보세요. 

속성 필요 없어도 의도적으로 new 키워드로 객체생성하도록 수정하세요. 

다른 부분도 이 부분은 모두 수정하세요!

2019-04-26 00:50 UTC, nigayo commented on oop/exceptionHandling.js
> +CustomException.prototype = {
에러처리부분을 분리해보는 연습도 좋네요.
메시지가 로직에서 빠져서 이렇게 분리된게 전 좋아보입니다.

2019-04-26 00:50 UTC, nigayo commented on oop/instruction.js
> +    show: (status) => {
show메서드를 하위메서드로 좀더 분리하면 좋겠어요. 규모가 살짝 큽니다. 
리팩토링!!

2019-04-26 00:50 UTC, nigayo commented on oop/instruction.js
> +        const id = Utils.prototype.getRadomId(99999, 1);
99999, 1 이런 매직넘버를 함수안에서 없애볼래요?

2019-04-26 05:18 UTC, dev-dongwon commented on oop/app.js
> +function Program() {
생성자 이름을 RunTodoApp 으로 변경했습니다. 명확하고 구체적으로 역할을 적시할 수 있도록 하겠습니다.

2019-04-26 05:22 UTC, dev-dongwon commented on oop/app.js
> +            const cmdList = CommandParser.prototype.getCmdList(userInput);
바로 접근하지 않고 생성자 객체에서 new 키워드로 생성 후, prototype에 접근하도록 수정했습니다. 

한 가지 궁금한 것이 있는데
바로 prototype에 접근하지 않고 객체를 생성하는 이유가 prototype의 내용이 공유되어 다른 객체에서 수정할 수 있기 때문인지, 혹은 다른 이유인지 궁금합니다.

2019-04-26 05:23 UTC, dev-dongwon commented on oop/instruction.js
> +    show: (status) => {
show 메서드를 분리해 show$all 상태와 나머지 상태를 처리하는 두 가지 하위 메서드를 만들어 리팩토링했습니다.

2019-04-26 05:24 UTC, dev-dongwon commented on oop/instruction.js
> +        const id = Utils.prototype.getRadomId(99999, 1);
직접 매직 넘버를 넣지 않고 객체에서 maxNumber, minNumber를 생성해 사용할 수 있도록 수정했습니다

2019-04-27 04:05 UTC, dev-dongwon commented
step5-2 리뷰 받아 수정을 진행했습니다.
아직 확인 못하신것 같아 다시 리뷰 부탁드립니다!

2019-04-29 04:30 UTC, crongro approved these changes
피드백이 늦었네요. 
수정잘하셨네요.  확인했어요!

2019-04-29 04:30 UTC, nigayo commented on oop/utils.js
> +    getRandomId : (max, min) => {
다른 파일에서처럼 객체안에 메서드를 쉽게 표현하면 좋겠네요.

,
getRandomId(max,min) {
//...
},

2019-04-29 04:30 UTC, merged