Step5 2 Ruby / Koon
code-squad/javascript-todo pull request #117
Opened 2019-04-26 03:26 UTC by kkw10

Ruby / Koon 5-2 구현완료했습니다.

2019-04-26 06:13 UTC, crongro requested changes
my-todo-func.js  가 객체기반코드가 아니라 아쉽네요. my-todo-func.js  는 중요한 역할을 하고 있으니 이놈을 객체화 시키고요.  prototype 기반의 코드로 바꿔보세요.

todo-prototype.js는 출력을 담당하는 역할이라면 그것에 맞는 이름으로 바꾸고요.

2019-04-26 06:13 UTC, nigayo commented on oop/data.js
> +    { 'name': 'asdf1', 'tag': [ 'asdf' ], 'status': 'todo', 'id': 9547 },
참고.
일종의 이런게 모델이죠.
실제로는 database등에서 가져와야 할 부분일거고요.

2019-04-26 06:13 UTC, nigayo commented on oop/errorMsg.js
> +    'syntaxError' : "문법적으로 유효하지 않은 입력값입니다.",
메시지는 이렇게 분리하는게 늘 좋습니다.

함수안에 있으면 로직을 읽는 걸 방해해요.

2019-04-26 06:13 UTC, nigayo commented on oop/my-todo-func.js
> +    let todo = todoList.filter(v => v.status === 'todo').length;
todoCount라고 해야겠네요. 이름을.

2019-04-26 06:13 UTC, nigayo commented on oop/my-todo-func.js
> +    let todo = todoList.filter(v => v.status === 'todo').length;
참고로 reduce를 사용한다면 count정보를 담는 객체를 만들수도 있죠.

const todoCount = todoList.reduce(//count객체정보를 만드는 함수 , {})

2019-04-26 06:13 UTC, nigayo commented on oop/todo-prototype.js
> +const ShowPrint = function() {}
파일이름에 구현방식을(여기서는 prototype) 표현하지 않는게 좋아요. 역할을 고민하고 그에 맞게 추상화시켜셔 이름을 지으세요.

2019-04-26 06:13 UTC, nigayo commented on oop/todo-util-method.js
> +module.exports = {
유틸을 잘 만들었네요.
좀 아쉬운건 todoList에 종속된 util이라 아쉽네요. 즉 다른 프로그램에서는 사용하지 못하는 것이라, 다음엔 그런 부분까지 고민해서 범용성있는 유틸리티를 만드려고 생각해보세요.

지금은  이름에서처럼 todoutil이라고 할수 있고, 그럴거면 굳이 별도 모듈로 분리해야할까? 라는 생각도 듭니다.

2019-04-29 01:28 UTC, kkw10 commented
Ruby / Koon step5-2 리펙토링 작업내용입니다.
1. 프로토타입 기반으로 코드를 수정했습니다.
2. 함수명, 파일명 등 변경완료했습니다.
3. reduce를 사용하여 showAll 함수 개선작업을 진행했습니다.

2019-04-29 04:37 UTC, crongro approved these changes
다음미션으로 가시죠! 
오늘 수업때 들은 부분도 반영해보세요.

2019-04-29 04:37 UTC, nigayo commented on oop/todoPrint.js
> +module.exports = {
객체로 감싸서 반환하지 말고, 그냥 이렇게 할 수 있어요.

module.exports= ShowPrint;

2019-04-29 04:37 UTC, nigayo commented on oop/my-todo-func.js
> +    let todo = todoList.filter(v => v.status === 'todo').length;
filter말고 find 메서드를 활용하면 어때요?

2019-04-29 04:37 UTC, merged