Q & Kaku Step5-3 mission
code-squad/javascript-todo pull request #118
Opened 2019-04-26 09:12 UTC by park78951

Step 5-3 미션 피드백 부탁 드립니다.

2019-04-27 00:54 UTC, crongro requested changes
class 변경을 잘 했고요. 
undo/redo기능을 범용적인 기능으로 만들어주세요.

2019-04-27 00:54 UTC, nigayo commented on todo-error.js
> +        if (action !== 'add' && action !== 'delete' && action !== 'update' && action !== 'show' && action !== 'redo' && action !== 'undo') {
['a','b','c','d'].indexOf() 
이런방법으로 체크하면 !== 중복이 좀 줄거 같네요.

2019-04-27 00:54 UTC, nigayo commented on todo-error.js
> +    sameStatusCheck(that, id, inputStatus) {
checkSameStaus 라고 이름 짓기.

2019-04-27 00:54 UTC, nigayo commented on todo-proto.js
> +    sortItem2(action, inputReadline) {
sortItem2는 너무 이름을 막지은거 같네요 ㅎ

2019-04-27 00:54 UTC, nigayo commented on todo-proto.js
> +    constructor() {
constructor가 생성될때 파라미터로 값을 받도록 하는 게 좋겠죠. 객체생성이 필요한 속성을 추가해주는 것이죠.

2019-04-27 00:54 UTC, nigayo commented on todo-proto.js
> +        const that = this;
this를 제어하기 위해서는 that과 같은 표현도 많이 쓰죠. 
추가로 bind, call, apply 를 공부해보는 것도 필요하긴해요.

2019-04-27 00:54 UTC, nigayo commented on todo-proto.js
> +        console.log(`${redoItem.id}번항목 ${redoItem.name}가 ${redoItem.status}상태에서 삭제되었습니다.`);
삭제뿐아니라.. 추가/변경등의 모든 과정에서 undo/redo가 되어야 해요.
요기능 확인해주세요.

2019-04-28 08:54 UTC, park78951 commented on todo-proto.js
> +    sortItem2(action, inputReadline) {
좀더 명확하게 지어보겠습니다...

2019-05-01 07:43 UTC, closed without merging

2019-05-01 07:45 UTC, park78951 commented
redo 및 undo 기능 추가 과정 중 새로 작성하는 것이 좋겠다고 판단하여 새로운 branch로 다시 PR 드리겠습니다..