욱 && 써커스 Step5 2 제출!
code-squad/javascript-todo pull request #120
Opened 2019-04-26 09:33 UTC by wo0kgod

늦었지만 5-2 제출합니다! 

커밋 하나하나마다 내용에 저희가 겪은 시행착오도 적어 보았습니다.

2019-04-27 01:13 UTC, crongro requested changes
객체를 적절히 잘 분리했어요. 

조금 수정하고 가면 좋을 부분도 있습니다.
리뷰확인하시고 잘 이해안가는 부분 comment주세요~!

수정부탁드려요.

2019-04-27 01:13 UTC, nigayo commented on oop/schedule-manager-design.md
> +### 2.이전에 짰던 코드의 함수
설계 잘 하셨어요. 객체 역할/ 메서드 역할 정의해두는 것이 좋은 방법이에요.

2019-04-27 01:13 UTC, nigayo commented on oop/schedule-manager.js
> +    this.editor = new Editor();
editor ! 라는게 웹에디터가 연상되긴 하지만 ㅎㅎ 특별한 네이밍으로 보이네요.

2019-04-27 01:13 UTC, nigayo commented on oop/schedule-manager.js
> +App.prototype = {
prototype을 재정의 했는데, 이렇게 해도 되고요, 이 패턴의 단점을 하나만 찾아보세요.

2019-04-27 01:13 UTC, nigayo commented on oop/schedule-manager.js
> +        function delayShow(time){
run안에 새로운 내부메서드를 두지마시고요, 
밖으로 분리하세요!! 메서드 안에 메서드는 중복된 코드기도하고 재사용도 안돼죠.

2019-04-27 01:13 UTC, nigayo commented on oop/schedule-manager.js
> +        const self = this;
self이렇게 해도 되는데요,  this를 좀더 이해할겸 bind와 call/apply 를 이해하고 한번 적용해볼래요?

2019-04-27 01:13 UTC, nigayo commented on oop/schedule-manager.js
> +    this.errorChecker = new ErrorChecker();
Editor 생성할때 파라미터로 errorchecker를 받도록 수정하고, 뭐가 좋은지 한번 생각해보세요.

2019-04-27 01:13 UTC, nigayo commented on oop/schedule-manager.js
> +        this.id = _newId
언더바(_)를 private한 상황에서 쓰는 건 좋은데, 요즘은 유행이 좀 지난듯 합니다 ㅎ 그냥 이름지으셔도 됩니다.

2019-04-27 01:13 UTC, nigayo commented on oop/schedule-manager.js
> +        const selectedArray = Object.entries(selectedObject).filter(([key, value]) =>
filter, map some안의 함수를 별도 함수 만들어서 선언해서 분리해볼래요?

2019-04-27 01:13 UTC, nigayo commented on oop/schedule-manager.js
> +Viewer.prototype = {
뷰라는 객체 역할이 명학하고 잘 분리한 거 같네요. 
다만 여기서도 마찬가지로 Viewer생성자에서 인자로 받아서 객체에서 사용할 부분은 뭐가 있을까요?

2019-04-27 03:58 UTC, wo0kgod commented on oop/schedule-manager.js
> +App.prototype = {
1. 기존의 prototype객체가 가지고있는 constructor 속성이랑 __proto__가 사라질것같습니다.
2. 내부에 생성자함수를 추가할때 es6의 함수생성 문법을 사용하지 못하고 key,value를 명시해 주어야합니다. (이건 단점이라고 할 수 있는지 모르겠네요)

2019-04-27 04:41 UTC, wo0kgod commented on oop/schedule-manager.js
> +    this.errorChecker = new ErrorChecker();
Editor를 생성할때 파라미터로 errorChecker를 받으면 App에서 생성한 errorChecker를 Editor에서 새로운 errorChecker를 만들지 않고 사용할 수 있습니다.

2019-04-27 04:42 UTC, wo0kgod commented on oop/schedule-manager.js
> +Viewer.prototype = {
Viewer에서 발생하는 에러가 있다면 errorChecker를 인자로 받아서 사용해야겠지만 , 저희가 구현한 프로그램에서는 viewer에서 따로 에러처리를 하지 않아서 Viewer 생성자가 인자로 받을게 따로 없는것같습니다. 
혹시... 있나요...?

2019-04-29 08:11 UTC, crongro approved these changes
좋아요.

5-3달려보세요.

2019-04-29 08:11 UTC, nigayo commented on oop/schedule-manager.js
> +                    .then(() => {
then의 인자로 들어간 콜백함수는 밖으로 분리하도록 하세요.

2019-04-29 08:11 UTC, merged