Step5-3: SU & Sony
code-squad/javascript-todo pull request #121
Opened 2019-04-27 03:00 UTC by sonypark

SU & Sony

step5-3 미션 구현한 내용입니다.
step5-2에서 받은 피드백 반영하여 수정 후 구현했습니다.

# 피드백 반영 수정 사항
1. 프로토타입 메소드를 TodoUI.prototype.addTodoResult 형식으로 반복적으로 쓰지 않고 아래와 같이 메소드를 
Todo.prototype 객체 안에 넣었습니다.

`
Todo.prototype = {
add() {},
delete(){}
}
`

2. oopTodo에서 data.js 파일을 oopTodo생성자의 인자로 주어 data.js 파일의 의존성을 낮췄습니다.

3. 변수 이름, 불필요한 함수 제거 등 수정했습니다.

2019-04-29 03:37 UTC, sonypark commented
[개발중입니다]
기존에 undo redo 기능이 delete 했을 때만 동작하도록 구현했습니다.
add, update 했을 때도 동작하도록 수정 후 푸시하겠습니다.

2019-04-29 05:11 UTC, crongro requested changes
undo/redo 수정대기할게요~

2019-04-29 12:35 UTC, sonypark commented
undo/redo 수정했습니다.
1. add,delete,update 모두 동작하도록 수정했습니다.
2. undo,redo는 각각 최대 3번까지 할 수 있도록 할 수 있게 했습니다.
3. undo를 한 후 add/delete/update를 할 경우 undo 리스트를 초기화 하도록 했습니다.

피드백 부탁드립니다. 감사합니다!

2019-04-29 23:50 UTC, crongro requested changes
잘 하셨어요. 동작확인은 시간되면 구경하러 갈게요.

한가지만 더 하고 마무리해요.
TodoApp이 좀 큰 규모의 객체입니다.  하나의 의미있는 객체를 분리해보세요.

2019-04-29 23:50 UTC, nigayo commented on oop/oopTodo.js
> +    this.datalist = datalist;
생성자 활용 잘 했어요!

2019-04-29 23:50 UTC, nigayo commented on oop/oopTodo.js
> +        const todoList = this.checkStatus(this.datalist, 'todo');
음 같은 함수 세번을 부르는데 iteration하는 방법으로 체크하면 더 좋을거 같네요.

2019-04-29 23:50 UTC, nigayo commented on oop/oopTodo.js
> +    redo() {
undo 함수와 중복코드는 없나요?

2019-04-29 23:50 UTC, nigayo commented on oop/oopTodo.js
> +        if (this.past.length < 4) {
4 이런 것도 매직넘버니까 없애야죠.

2019-04-29 23:50 UTC, nigayo commented on oop/oopTodo.js
> +        if (command === 'show') {
개인차는 있지만 case가 많은 경우는 switch 문이 더 보기 좋은거 같더군요.

2019-04-30 09:58 UTC, sonypark commented on oop/oopTodo.js
> +        if (command === 'show') {
switch문으로 고쳤습니다

2019-04-30 09:58 UTC, sonypark commented on oop/oopTodo.js
> +        if (this.past.length < 4) {
매직넘버를 인자로 받도록 변경했습니다

2019-04-30 09:59 UTC, sonypark commented on oop/oopTodo.js
> +        const todoList = this.checkStatus(this.datalist, 'todo');
iteration해서 할당하도록 변경했습니다.

2019-04-30 09:59 UTC, sonypark commented
수정했습니다. 피드백 부탁드립니다.

2019-05-01 21:50 UTC, crongro approved these changes
네 잘 구현하셨어요. 
리뷰남긴 것은 참고하세요!

2019-05-01 21:50 UTC, nigayo commented on oop/commonUtility.js
> +    const [matchedListByID] = this.datalist.filter(list => {
filter함수를 한줄로 표현할 수 있겠네요. 짧게 표현하는 매력을 느껴보시길~

2019-05-01 21:50 UTC, nigayo commented on oop/oopTodo.js
> +const todoList = new TodoApp(datalist);
마지막 이 두 라인은 oopTodo.js에서 하지 않고,
app.js와 같은 진입점역할만 하는 파일에서 하면 더 좋겠어요. 
oopTodo.js 파일은 TodoUI를 선언만하고 객체초기화는 다른곳에서 필요할때 하는 것이죠.

2019-05-01 21:50 UTC, nigayo commented on oop/undoable.js
> +    if (this.save === false) {
if(!this.save) 
이렇게 표현 할 수 있겠네요.

2019-05-01 21:50 UTC, nigayo commented on oop/undoable.js
> +    if(this.storeCommand.length != 0){
===, == 
두 개 차이를 좀더 이해하시고, === 를 사용하는 게 더 좋겠습니다.

2019-05-01 21:50 UTC, nigayo commented on oop/undoable.js
> +        this.datalist.pop();
undo와 redo부분에서 중복코드가 여전히 보이는데요, 
이부분을 개선할 수 있으면 더 좋을 거 같습니다.

2019-05-01 21:50 UTC, merged

2019-05-03 04:58 UTC, sonypark commented on oop/commonUtility.js
> +    const [matchedListByID] = this.datalist.filter(list => {
네 짧게 표현하는 연습을 해야겠네요 :)

2019-05-03 04:59 UTC, sonypark commented on oop/oopTodo.js
> +const todoList = new TodoApp(datalist);
앞으로는 app.js 파일을 만들어 호출만 따로 해주도록 분리해보겠습니다.

2019-05-03 04:59 UTC, sonypark commented on oop/undoable.js
> +    if (this.save === false) {
저렇게하니 훨씬 간단해졌네요..ㅎㅎ

2019-05-03 05:00 UTC, sonypark commented on oop/undoable.js
> +    if(this.storeCommand.length != 0){
네 `!==` 이렇게 썼어야했는데.. 앞으로는 조심하겠습니다!

2019-05-03 05:00 UTC, sonypark commented on oop/undoable.js
> +        this.datalist.pop();
이 부분은 어떻게 중복을 제거할 수 있을지 고민해보겠습니다!