Step5-3 객체지향프로그래밍 Andole & Jake
code-squad/javascript-todo pull request #122
Opened 2019-04-28 08:12 UTC by cocahack

지난 번 미션에서 리뷰 해주셨던 내용은 모두 수정한 뒤, undo-redo 기능을 구현했습니다.

수정 사항
1. `readline.on('line')`에 `finally` 블록을 사용해서 항상 실행되는 부분은 여기에 넣었습니다. 
2. SQL에서 사용하는 `groupBy` 와 `count`를 구현해서 상태 별 객체의 개수를 깔끔하게 처리할 수 있도록 변경했습니다. 
3. `update` 메소드에서 `findIndex`와 `find`를 중복해서 사용하는 실수를 고쳤습니다.
4. `Parser` 관련 클래스를 prototype 패턴으로 마이그레이션 했습니다.

Step 5-3 관련
`TodoContainer` 클래스를 구현해서  undo, redo 기능을 지원하도록 업데이트 했습니다.

리뷰 부탁드립니다.

2019-04-29 05:10 UTC, crongro requested changes
undo/redo 동작은 잘 되나요? 
코드는 깔끔하게 잘 구현했어요 👍 

리뷰남긴 부분 조금 더 수정해보세요.

2019-04-29 05:10 UTC, crongro commented on oop/todoApp.js
> +Array.prototype.groupBy = function(prop) {
Native에 추가하는 방법은 꽤 편리하지만,   groupBy와 같은 이름을 가진 메서드가 native에 추가될때 문제가 될 수는 있어요.
안티패턴이라 이부분은 수정을 하면 좋겠어요.

2019-04-29 05:10 UTC, crongro commented on oop/TodoContainer.js
> +  undo(){
undo/redo 구현 잘 했어요.   _diffContainer 를 활용한 점이 괜찮아 보이네요.

2019-04-29 05:10 UTC, nigayo commented on oop/TodoContainer.js
> +        const targetIdx = this.container.findIndex(todo => todo.id === lastOp.todo.id );
undo기능에서 하는 추가/삭제/업뎃 기능이 
이미 있는 insert/remove/update등의 메서드와 중복인 부분들이 있어서 좀 아쉽네요.

중복을 조금이라도 줄일 수 있을지 판단해보세요.

2019-04-29 05:10 UTC, nigayo commented on oop/todoParser.js
> +TodoParser.prototype = Object.create(Parser.prototype);
상속이 재사용패턴이기도 하죠. 
상속 시도한 건 좋습니다.

TodoParser는 객체리터럴로 구현해도 좋겠고요.

2019-04-29 05:10 UTC, nigayo commented on oop/todoApp.js
> +    groups[prop] = (this[prop] instanceof Array ? this[prop].length : 1 );
Array 타입체크 하는 더 나은 방법이 있는지도 살펴보세요.

2019-04-29 05:10 UTC, nigayo commented on oop/todoParser.js
> +    const parsedLine = this.checkSingleCommand(line) ? [ line ] : Parser.prototype.parsing.call(this, line);
이렇게 부르지 않고, 다른 방법을 찾아볼래요? 

Parser.prototype.parsing.call(this, line);

2019-04-30 08:19 UTC, cocahack commented
안티패턴 부분과 배열을 체크하는 부분은 수정했습니다. 

undo에서 다른 메소드를 재사용하는 것도 해당 메소드의 위치를 `TodoContainer`에서 `TodoApp`으로 옮겨서 재사용할 수 있도록 수정했습니다. 다만 이 과정에서 소스코드가 너무 지저분해졌네요.....

call 메소드를 변경하는 부분은 손을 못댔습니다. `TodoParser`를 객체 리터럴로 변경하거나 class로 정의하는 방법말고는 생각나질 않네요. 어떤 방법을 써야 하나요?

2019-05-01 22:00 UTC, crongro approved these changes
잘 수정됐네요.

> Parser.prototype.parsing.call(this, line);
이 부분은 parser 객체를 생성하고 parser.parsing.call(this.line); 
이렇게 prototype을 생략하고 불러야겠죠.

2019-05-01 22:00 UTC, merged