Step5-3 객체지향프로그래밍 왕민 & 묵은지
code-squad/javascript-todo pull request #123
Opened 2019-04-28 13:28 UTC by mukeunzi

리뷰 부탁드립니다.

2019-04-29 05:28 UTC, crongro requested changes
queue를 사용해서 잘 구현했습니다.

큰 맥락에서는 좋고요, 
리뷰드린 내용을 조금더 수정해보시면 좋겠네요.

2019-04-29 05:28 UTC, nigayo commented on oop/todo.js
> +	todoLog.undo();
undo/redo 가 있는 Log에서 todolist를 직접 표현해서 쓰지 않고, 
여기와 같이 undo/redo 메서드를 부를때 todoList값을 인자로 넣어주는 게 어때요?

2019-04-29 05:28 UTC, nigayo commented on oop/todo.js
> +	Object.assign(prevData, newData);
두 줄을, 한 줄로 표현할 수 있겠네요.

var prevData = Object.assign({}, newData);

2019-04-29 05:28 UTC, nigayo commented on oop/todo.js
> +	setTimeout(() => {
add메서드가 여러개를 하는데, 좀 나누자면 예를들어서  이렇게도 가능하죠.

> add를 해서 데이터를 추가하고, 추가한 결과를 받은후에,  addLog수행하고 print수행하기.

2019-04-29 05:28 UTC, nigayo commented on oop/todo.js
> +	Object.assign(nextData, this.todoList[index]);
위에서 언급한 것처럼 수정하기.

2019-04-29 05:28 UTC, nigayo commented on oop/Log.js
> +	if (this.queue.length > 4) {
변경될 소지가 있으니 4라는 숫자 없애보기. (다른곳으로 옮겨서 표현해야겠죠)

2019-04-29 05:28 UTC, nigayo commented on oop/Log.js
> +		this.alterData(todoListIndex, 0, nextData);
인자3개를 넘겨주는게 
인자를 객체 하나를 사용하는 방법으로 수정해보세요.

2019-04-29 12:52 UTC, Min-92 commented
전체적인 구조 리팩토링 완료했습니다.
리뷰 부탁드립니다.

2019-04-30 01:22 UTC, crongro reviewed
undo/redo 과정에서 실제 todolist의 데이터 상태가 변경되는 건가요?

2019-04-30 01:22 UTC, nigayo commented on oop/log.js
> +	(this.queue = []), (this.index = -1), (this.undoLimit = 3);
이렇게 표현하는 게 전 좀 낯서네요 
(this.queue = []), (this.index = -1), (this.undoLimit = 3); 

-1,3 도 인자로 받으면 더 좋고요. default parameter도 활용해서 기본값도 셋팅할 수 있고요.

2019-05-01 13:34 UTC, Min-92 commented on oop/log.js
> +	(this.queue = []), (this.index = -1), (this.undoLimit = 3);
네! 실제 todolist 데이터 변경됩니다.
구조 변경하면서 발생한 버그 수정했고 default parameter 사용했습니다.
(this.queue = []), (this.index = -1), (this.undoLimit = 3);
이표현은 프리티어가 제멋대로...
아래 표현이 의도한 표현입니다.
this.queue = [], 
this.index = -1,
this.undoLimit = 3

2019-05-01 22:03 UTC, crongro approved these changes
수정하신 거 확인했어요.
수고하셨어요!  승인합니다.

2019-05-01 22:03 UTC, nigayo commented on oop/log.js
> +	(this.queue = []), (this.index = defaultIndex), (this.undoLimit = undoLimit);
괄호가 좀 불필요해보이긴 하는데요.
취향으로 인정할게요 ㅎ

2019-05-01 22:03 UTC, merged