Step5-3 Gren&Sage&PAPICO
code-squad/javascript-todo pull request #125
Opened 2019-04-29 08:29 UTC by ocipap

2019-04-29 23:08 UTC, crongro requested changes
undo/redo는 비교적 깔끔하게 구현했네요. 

리뷰 남긴 부분 수정하고 마무리하면 좋겠습니다.

2019-04-29 23:08 UTC, crongro commented on oop/ErrorConstant.js
> +module.exports = {
객체로 한번 감싸지 말고 바로, exports 하면 좋겠네요.
module.exports = ERR_MSG;

2019-04-29 23:08 UTC, crongro commented on oop/Todos.js
> +const historyQueue = {
historyQueue 객체는 Todos와 다른 모듈임으로, 파일도 분리해서 관리하면 더 좋겠네요.

2019-04-29 23:08 UTC, crongro commented on oop/Todos.js
> +let incrementId = 0
객체 밖에 있는 변수는 없애는 게 좋겠네요.

2019-04-29 23:08 UTC, crongro commented on oop/Todos.js
> +    getCountByStatus: function (status) {
getListByStatus와 중복메서드 같아요. 없어도 될 듯.

2019-04-29 23:08 UTC, nigayo commented on oop/Todos.js
> +    async delete(id) {
async 를 했더니 어떤 장점이 있나요?

2019-04-29 23:08 UTC, nigayo commented on oop/Todos.js
> +        await todoUtils.sleep(3000)
3000와 1000도 함수의 인자로 받거나, 변수로 선언해서 쓰는 게 나을 거 같아요.

2019-04-29 23:08 UTC, nigayo commented on oop/Todos.js
> +const todoList = []
todoList를 전역에 선언해서 많은 모듈에서 공유하기보다는, 
데이터를 관리하는(추가,삭제)객체에서 속성으로 갖고 있는게 좋겠어요.

2019-04-29 23:08 UTC, nigayo commented on oop/validator.js
> +const regexObj = {
todo용 validator 모듈을 잘 만들었네요.

2019-04-29 23:08 UTC, nigayo commented on oop/Todos.js
> +        if(this.pointer === 3) {
3이라는 숫자를 없애보죠?

2019-04-29 23:08 UTC, nigayo commented on oop/Todos.js
> +    data: [],
data보다는 좀더 자세한 이름을 지어줘보세요.

2019-04-29 23:08 UTC, nigayo commented on oop/Todos.js
> +        JSON.parse(JSON.stringify([...list])).forEach(el => {
객체->문자열->객체변환이 지금 필요한거 맞는거죠?  (확인좀해보세요)

2019-04-30 02:54 UTC, ocipap commented on oop/Todos.js
> +        JSON.parse(JSON.stringify([...list])).forEach(el => {
todoList를 복사할때 내부객체의 status가 얕은 복사가 되는 현상이 있어서 객체의 깊은 복사를 위해 사용하였습니다.

2019-04-30 03:04 UTC, ocipap commented on oop/Todos.js
> +    async delete(id) {
함수를 비동기로 제어하는데 조금 수월했습니다.

2019-04-30 03:11 UTC, ocipap commented
리뷰 감사합니다. 피드백 주신 내용 수정 하였습니다!

2019-04-30 05:41 UTC, crongro approved these changes
수고하셨어요 👍  
머지합니다. 

이번스탭에서 코딩하면서 배운것들 잘  마무리해서 이해하고 넘어가면 좋겠습니다.

2019-04-30 05:41 UTC, nigayo commented on oop/Todos.js
> +            "done": this.getListByStatus(todoList, "done").length
아마도 reduce를 써도 될 거 같죠?

2019-04-30 05:41 UTC, nigayo commented on oop/Todos.js
> +        JSON.parse(JSON.stringify([...list])).forEach(el => {
그렇군요. 
immutable 에 대해서도 같이 이해하고 넘어가면 best일 거 같군요.

2019-04-30 05:41 UTC, merged