Step5-3 Seldev & Nailer
code-squad/javascript-todo pull request #126
Opened 2019-04-29 09:38 UTC by nailerHeum

5-3 완료했습니다!
특이사항 : undo와 redo Loop가능

2019-04-29 23:14 UTC, crongro requested changes
undo/redo 를 각각 배열로 만들다보니 복잡도가 올라가는 거 같아요. 하나의 history자료구조를 통해서 보관하는 게 좀더 쉬울거 같은데요. 개선방법을 좀더 고민해보면 좋겠어요.  (선택입니다)

undo/redo 통합을 떠나서, 현재 코드에서 개선을 하려면 undo/redo 에서 중복코드가 좀 보입니다. 
종복을 찾아서 이를 제거하면 좋겠어요.

2019-04-30 03:31 UTC, nailerHeum commented
수정사항 반영했습니다!

2019-04-30 06:01 UTC, crongro approved these changes
중복은 많이 제거한거 같네요.

수고많이 했어요. 👍 
이번에 코딩하면서 배운것들 정리 & 복습하도록 하세요.
다른 사람들의 구현코드도 살펴보시고요.

2019-04-30 06:01 UTC, crongro commented on oop/todoHandler.js
>  const todos = JSON.parse(data)
클래스에서 주로 사용하는 속성인데 클래스 밖에 있으니 어색합니다.

2019-04-30 06:01 UTC, merged