Jin&Michelle step5-3 페어프로그래밍
code-squad/javascript-todo pull request #128
Opened 2019-04-29 10:11 UTC by eugene94

5-2에서 받았던 리뷰를 반영하여 리팩토링 하였습니다.

그 후 5-3 요구사항을 추가로 구현했습니다.

2019-04-29 23:36 UTC, crongro requested changes
잘 구현했는데요.

조금 더 수정하고 가면 좋겠어요.
managingTodo에서 좀 규모가 큰 함수들은 더 작게 만들면 좋겠고요.
중복코드를 찾아서 개선하면 좋겠습니다.

2019-04-29 23:36 UTC, nigayo commented on oop/managingTodo.js
>  const Todo = require('./todo');
managingTodo 보다는 TodoManager 라는 이름이 그럴싸하겠네요

2019-04-30 02:59 UTC, eugene94 commented
피드백 주신대로 
- managingTodo => todoManager로 변경하였습니다.
- 중복 코드도 제거해봤습니다.

2019-04-30 06:15 UTC, crongro approved these changes
중복이 꽤 줄었네요? 

이번 스탭은 여기서 마무리 해도 될 거 같네요.
수고하셨어요 👍

2019-04-30 06:15 UTC, merged