todoList 기본 기능 구현까지 :D
code-squad/javascript-todo pull request #13
Opened 2018-03-21 09:39 UTC by amorfati0310

2018-03-22 08:58 UTC, crongro requested changes
수고하셨네요.
잘 하셨고요. 
리팩토링을 고민해보죠.

2018-03-22 08:58 UTC, nigayo commented on todo/index.js
> +    const State = {
상태를 관리해야 하는 데이터가 몇개 있고 따로따로 있는데요.
하나의 객체에 표현해서 관리할 수 있을까요?

2018-03-22 08:58 UTC, nigayo commented on todo/index.js
> +const command = (function () {
지금 구조가 약간 중첩되어 있어요.
함수가 추가될수록 객체관계가 복잡해질 소지도 있네요.
중첩구조를 좀 줄여보면 좋을거 같아요.
지금은, 함수 - 함수 - 함수 로 되어 있는데요.
함수 -객체  정도로 구현가능할겁니다.

2018-03-22 08:58 UTC, nigayo commented on todo/index.js
> +    const controller = function (order) {
관리해야 할 정보들(데이터)들이 몇개 있는데 하나의 객체안에 모두 넣어서 관리하면 어때요?

2018-03-22 08:58 UTC, nigayo commented on todo/index.js
> +            const [first, second, last] = order.split('$');
변수에 의미를 부여해주면 더 좋겠어요.
first, second, last보다는.

2018-03-22 08:58 UTC, nigayo commented on todo/index.js
> +                    switch (state) {
별 다를게 없는 반복적인 case들을 나열하고 있자나요?

자바스크립트 객체를 잘 활용해서 이 switch문을 없애보죠.(if문도 안됨)

2018-03-22 08:58 UTC, nigayo commented on todo/index.js
> +                    console.log(`id: ${data.id} ${data.todo} 항목이 추가 되었습니다 `)
출력만 담당하는 걸 객체나, 함수형태로 별도로 만들어보세요.

2018-03-22 08:58 UTC, nigayo commented on todo/index.js
> +    const Actions = {
Actions 이 같은 key에 같은 value네요.
이게 꼭 객체형태여야 하나요?

2018-03-22 08:58 UTC, nigayo commented on todo/index.js
> +                if (!enumCheck(State, data)) throw new Error(errMsg)
enumCheckTodoState() 함수가 필요한가요? 
enumCheck를 wrapping하고만 있고요.
그 기능을 enumCheck에 넣어주는 건 어때요?

2018-03-22 08:58 UTC, nigayo commented on todo/index.js
> +                return;
return 이 필요할까요?

2018-03-22 10:16 UTC, amorfati0310 commented on todo/index.js
> +    const State = {
수정해보겠습니다 감사합니다 👍

2018-03-22 10:41 UTC, amorfati0310 commented on todo/index.js
> +            const [first, second, last] = order.split('$');
아 이 부분에 저도 의미를 부여해주고 싶었는데 first는 action으로 부여하면 되는데  update때는  id를 가져오고 show에서는  state를 가져와서 어떻게 이름 지어줘야 될 지 잘 모르겠더라고요 ㅜ

2018-03-23 02:27 UTC, nigayo commented on todo/index.js
> +            const [first, second, last] = order.split('$');
음 좀 어렵군요.

슬랙방에 제가 아침에 공유한 내용을 한번 참고하실래요?

2018-03-23 07:43 UTC, amorfati0310 commented on todo/index.js
> +            const [first, second, last] = order.split('$');
감사합니다 👍

2018-03-23 13:59 UTC, amorfati0310 reviewed
객체에서 data들이랑 함수들을  어떻게 묶고 같이 써야 될지를 잘 모르겠네요 'ㅁ';;;

2018-03-23 13:59 UTC, amorfati0310 commented on todo/index.js
> +    const Actions = {
state도 그렇고 단순히  'a'|'b'|'c' 이건지 아닌지 enum값 처럼 체크하기 위한 객체인데  이 부분을 간단히 쓸 수 있는지 조금 더 알아봐야겠습니다

2018-03-23 13:59 UTC, amorfati0310 commented on todo/index.js
> +                if (!enumCheck(State, data)) throw new Error(errMsg)
감사합니다 중복되는 부분이 2개가 있어서 함수로 넣어주긴 했는데 가독성도 굳이 만들어 줄 필요가 없었던 것 같습니다 'ㅁ'

2018-03-23 13:59 UTC, amorfati0310 commented on todo/index.js
> +                return;
필요 없네요 ㅜ 감사합니다 👍

2018-03-23 13:59 UTC, amorfati0310 commented on todo/index.js
> +const command = (function () {
네엡 얼른 수정해보겠습니다 👍

2018-03-23 13:59 UTC, amorfati0310 commented on todo/index.js
> +                    console.log(`id: ${data.id} ${data.todo} 항목이 추가 되었습니다 `)
객체로 바꾸는 과정에서 thisBinding을 하려고 하니까 함수-객체 = 또 다른 객체를 생성하기가 좀 까다로워서 하나의 객체로만 했는데... 한 번 프린트 하는 부분을 추후에 분리해보도록 해보겠습니다 약간 이해 안되는 부분이 있어서 그 부분도 정리해서 물어보겠습니다

2018-03-26 02:46 UTC, crongro requested changes
객체안에 함수의 크기는 아주 좋아요.

print를 처리하는 것이 곳곳에 있는데요. print하는 부분을 별도 객체로 분리해보세요.

2018-03-26 02:46 UTC, nigayo commented on todo/index.js
> +    enums.actions = {
enums 는 그냥 코드에 적어도 될 거 같아요. 
이름이 변경될 확률도 너무 적고..

2018-03-26 02:46 UTC, nigayo commented on todo/index.js
> +            update(id, state) {
update도 update된 결과가 나오도록 기능을 추가해볼래요?

2018-03-26 02:46 UTC, nigayo commented on todo/index.js
> +                if (!enumCheck(state, enums.state)) throw new Error(errMsg.wrongState)
잘못된 입력등을 모두 new Error로 처리했는데요. 프로그램 실행이 종료돼버리죠.
이렇게 오류처리를 해도 되긴해요. 에러처리는 보통 개발자들에게 알려줘서 디버깅을 쉽게 하기 위함이기도한데요.
어떤 sw는 메시지를 반환만하고, 계속 sw가 동작되도록 해야할경우도 있어요. 
그런경우는 new error를 통해서 에러를 발생시키면 안되겠죠.
참고하세요.

2018-03-26 02:46 UTC, nigayo commented on todo/index.js
> +            initState() {
state 라는 이름이 어떤 data 인지? 좀더 명확하게 표현하면 더 좋겠네요.

2018-03-26 03:09 UTC, amorfati0310 commented on todo/index.js
> +                if (!enumCheck(state, enums.state)) throw new Error(errMsg.wrongState)
감사합니다 👍 계속 동작시키게 할 때는 console.error('error message')로 대체하면 될까요?

2018-03-26 03:13 UTC, amorfati0310 commented on todo/index.js
> +            update(id, state) {
네엡 ~~ 👍

2018-03-27 01:31 UTC, crongro requested changes
모드 command 함수안에 있지만, 그 안에서 객체를 잘 그룹핑했어요. 코드도 복잡하지 않고 좋네요. 

몇가지 수정사항을 반영해보세요.

2018-03-27 01:31 UTC, nigayo commented on todo/index.js
> +            this.printTodo[enums.printMethods[actions]](printKey);
이 this.printTodo['show'] 로 불려지면 될 거 같은데, enums객체리터럴을 사용할 필요가 있을까요?

2018-03-27 01:31 UTC, nigayo commented on todo/index.js
> +                filterList.forEach(
reduce 공부하는 거 같던데, 이놈도  reduce를 써보세요.

2018-03-27 01:31 UTC, nigayo commented on todo/index.js
> +                if (!enumCheck(todoState, enums.todoState)) console.error(errMsg.wrongTodoState)
console.error로 에러메시지를 노출하고, 아래 로직은 그대로 처리되는게 맞나요?

2018-03-27 01:31 UTC, nigayo commented on todo/index.js
> +const enumCheck = (checkData, enumData) => {
enumCheck와 notNumber는 command 라는 함수안의 동작과 상관없어보여서 뺀거죠? 
이놈들끼리 유틸리티 역할을 하도록 객체리터럴로 같이 묶어두죠. 
그래서 이런 녀석들을 재사용하도록  하면 좋겠어요.

2018-03-28 23:41 UTC, crongro reviewed
전체적으로 구현잘했어요.
printTodo는 좀 막상분리하니 호출하는 쪽에서 보면 어색해보이네요. (심각한 문제는 아님)

이렇게 하면 출력 모든 command실행 이후에 누적돼서 나오는데요, 마지막 상태로 모든 결과가 동일하게 나오는거 같아요. 어떻게 보면 버그일 수도 있는데요.
왜 그럴까요?  설명만해보세요~ 

command('add$ES6공부');	     
command('add$TIL 블로그 글 쓰기');	     
command('add$TIL 블로그 글 쓰기');
command('add$이전에 짠 것들 Refactoring하기');	    
command('add$Express 공부');

2018-03-28 23:41 UTC, nigayo commented on todo/index.js
> +            add() {
객체로 분리로 잘했는데요.

하고보니,  printTodo.add() 라고 부르는게 좀 어색하네요.
printTodo가 하나의 객체이고, 어쩌면 그 안에 메서드가 있어서 부르는 쪽에서는 어색하게 느낄 수 있어보이네요. 

본인생각도 궁금하네요. 
지금 객체를다시 수정할필요는 없지만 다른 방법으로 매끄럽게 print부분이 불려지려면 어떻게 하는게 좋을지 고민스럽네요.

2018-03-28 23:41 UTC, nigayo commented on todo/index.js
> +            doneTime(id) {
이 함수는 이름을 무엇으로 짓는게 맞을까요? 
출력인가요? 그럼 doneTime이 어울리나요?

2018-03-28 23:41 UTC, nigayo commented on todo/index.js
> +                return filterList.reduce((result, todo) => {
reduce 이해가 좀더 높아진 거 같네요.  누산기라고 번역되는데요, 꽤 유용하게 데이터를 만들때 사용될 수 있어요.

2018-03-28 23:41 UTC, nigayo commented on todo/index.js
> +                return {
return 뒤에 { 하고 한줄씩 띄는 것은 그냥 개인취향하지만, 
꼭 그래야 하는건 아닐듯. 코드가 너무 가로로 길거나, 세로로 나열된 거만 조심해보세요.

2018-03-28 23:41 UTC, nigayo commented on todo/index.js
> +                    const {
이런코드를 개행해서 표현하지 않아도 될 듯. const { doing, done} = todos[id.].time 이렇게 짜는게 나을 거 같아요.

2018-03-28 23:41 UTC, nigayo commented on todo/index.js
> +function timeDelay(arr, time) {
재미있는 시도네요.
 몇가지 궁금증을 더 드리고 싶은데요.
- 이런 재귀호출시 call stack이 쌓일까요?  궁금해보세요~
- 배열값을 참조하면서 자르면서 그 상태를 유지하고 있는데, 유지하지 않고 복사해서 구현할 수 있을까요?

2018-03-30 03:39 UTC, crongro requested changes
객체 구조를 설명한 것처럼, 좀더 단순하게 만들어보세요.

2018-04-02 08:12 UTC, crongro requested changes
enums 는 제거하던가, 배열로 저장하던가.
전역변수없애기, Seconds 
클래스(모듈)별로 하나의 물리적인 파일로 관리.
printController라고 이름을 지으면, printModel이나 view가 있을거 같다.
printController의 메서드의 이름수정.
printController의 메서드들은 모두 todos 객체를 파라미터로 받아도 좋겠음.
command 함수는 compileOrder와 중복.
Controller 객체는 Main TODO객체에 포함되서 동작.

2018-04-03 02:26 UTC, crongro approved these changes
여기까지 하고 close하죠.

아래 코멘트는 참고해두세요.

복잡한 데이터 구조가아닌 이상은 지금수준에서는, 
this.todos = {}와 stateCounter를 합칠수도 있습니다. 
이렇게 되면 하나의 store안에서 모든 state를 관리하는 것이라 분리된 상태로 관리하는 것보다 좀더 나을 수 있습니다. 데이터들의 중복도 없고요.

throw로 던지는 에러가 매 함수마다 있는데요. 반드시 에러처리가 필수인 건 아닙니다. 에러가 발생할 소지가 있는 경우에 처리하고, 그렇다면 에러처리를 다른 함수에서 할 수 있도록 분리하는 것도 좋겠네요.

2018-04-03 02:26 UTC, merged