Step5-3 : TUNA, YM
code-squad/javascript-todo pull request #130
Opened 2019-04-29 11:24 UTC by dev-dongwon

#### PR을 잘못 날려 닫고 다시 PR 합니다

## STEP5-3 : OOP 개선
- prototype 패턴에서 ES6 Class로 변환
- undo, redo 기능 추가

2019-04-29 23:37 UTC, nigayo commented
@dev-dongwon master에 PR을 보내셔서, 제가 dev-dongwon으로 브랜치를 변경했는데요.
app.js에서 충돌이 발견...되었네요. 해결해서 다시 보내주시면 좋겠어요.

2019-04-29 23:45 UTC, crongro requested changes
일단 충돌해결 & 리뷰남긴것 같이 수정부탁드려요.

2019-04-29 23:45 UTC, nigayo commented on instruction.js
> +        } else if (arguments.length == 2) {  // add, delete
주석이 필요한.. arguments.length 로 구별하는 이방식을 어떻게 개선할 수 있을까요?

2019-04-29 23:45 UTC, nigayo commented on instruction.js
> +		this.utils = new Utils();
전체코드의 들여쓰기가 너무 깊은데요? 
좋은 indent 가 무엇인지 한번찾아볼래요? 
tab vs. space 중어떤것을 선택하는게 좋은지도요.

2019-04-29 23:45 UTC, nigayo commented on utils.js
> +    deepCopy (obj) {
오 이부분 잘 이해하고 계신거죠? 유용한 유틸이 하나 보이길래~

2019-04-29 23:45 UTC, nigayo commented on utils.js
> +		return new Promise(function(resolve, reject){
Promise패턴에 대해서 잘 이해하고 공부하시면 좋겠어요. 
(어렵습니다)

2019-04-29 23:45 UTC, nigayo commented on app.js
> +		this.commandParser = new CommandParser();
시작하는 것은 굳이 class로 만들지 않아도 될거 같아요.
재사용일 될 일이 정말 없을 거 같은 부분이기도 하니까요.

class를 사용한다면, 의존하고 있는 CommandParser, Utils, Instruction등은 밖에서 객체를 생성한후에, RunTodoApp 생성자의 인자로 주입받아서 사용하는 게 더 좋고요.

2019-04-29 23:45 UTC, nigayo commented on app.js
> +            .then(() => {if (cmdList[0] === 'update') return this.utils.delay(3500);})
promise패턴을 사용했는데요. 
then메서드를 사용했을때의 장점은 무엇이라고 생각되세요?

2019-04-29 23:45 UTC, nigayo commented on commandParser.js
> +	}
(전체 코드의 들여쓰기를 깨끗하게 맞추도록 해주세요 ^^)

2019-04-29 23:45 UTC, nigayo commented on customException.js
> +const CustomException = class {
이부분은 객체리터럴 vs. 클래스! 중 어떤 것이 더 어울릴까요? 
이유는 무엇일까요?

2019-04-30 02:59 UTC, closed without merging

2019-04-30 03:36 UTC, nigayo commented
이거 Close 된건가요?? 살아있는 경로는 어디죠? ㅎ

2019-04-30 03:39 UTC, dev-dongwon commented
오..오시면 직접 뵙고 말씀드리려 했는데, 충돌된 지점을 머지하기 이전에 커밋 히스토리를 훨씬 이전으로 돌리고 push하는 바람에 리모트 저장소를 날려버렸습니다 ㅜㅜ 다시 작업해서 다시 풀리퀘하겠습니다, 오시면 뵙고 말씀드릴게요 ㅠㅠ

2019-04-30 04:51 UTC, nigayo commented
아 네 다시 PR해주세요~  ^^
@dev-dongwon