Koon&Ruby step5-3
code-squad/javascript-todo pull request #135
Opened 2019-04-30 06:30 UTC by ruby413

## Step5-3 구현
- redo / undo 구현
- 프로토타입 클래스화

2019-04-30 07:58 UTC, crongro requested changes
제가 몇 자 적다가 아까 자리에 가서 설명드렸어요.
리뷰하던거 그냥 남깁니다.

2019-04-30 07:58 UTC, crongro commented on oop/errorMsg.js
> +    'ELSE_ERROR' : "치명적인 오류가 발생했습니다."
치명적!! 알수없는 오류~ 가 나을 거 같네요 ㅎㅎ

2019-04-30 07:58 UTC, crongro commented on oop/my-todo-func.js
> +const readline = require('readline');
파일이름에 func 나 module, class 와 같은 것을 표현하는건  좀 불필요해보여요.

2019-04-30 07:58 UTC, crongro commented on oop/ErrorCheck.js
> +module.exports = {
module.exports = ErrorCheck; 

라고 해도 됩니다. 

이제 require하는쪽에서는 이걸 어떻게 불러서 써야 할까요?

2019-04-30 07:58 UTC, crongro commented on oop/my-todo-func.js
> +const HistoryForm = function (model, name, id, status, tag){
이녀석은 왜 대문자로 시작하죠?

2019-04-30 07:58 UTC, crongro commented on oop/my-todo-func.js
> +    if(Error.syntaxError(answer) === false) {
if문은 자동으로 true/false를 판단하기때문에 
target === false 이렇게 비교할 필요가 없어요.

2019-05-02 05:35 UTC, ruby413 commented on oop/my-todo-func.js
> +const readline = require('readline');
네엡! 파일 이름 변경했습니다!

2019-05-02 05:35 UTC, ruby413 commented on oop/my-todo-func.js
> +const HistoryForm = function (model, name, id, status, tag){
수정했습니다! 좀더 조심하겠습니다 :)

2019-05-02 05:35 UTC, ruby413 commented on oop/my-todo-func.js
> +    if(Error.syntaxError(answer) === false) {
넵 감사합니다..!

2019-05-02 05:36 UTC, ruby413 commented
이해한 부분에 따라 부족하지만 undo 와 redo 를 history class로 다시 만들었습니다. 
기능에 따라 class를 명확히 나누는 부분 더 공부하겠습니다..!ㅠㅠ 직접 알려주셔서 감사합니다 :)

2019-05-07 07:45 UTC, crongro approved these changes
클래스 역할은  좀 명확한 편이에요. 잘하셨어요. 

main.js파일 이외에 클래스별로 파일을 만드는 게 더 좋겠죠.
fe/be모두 실무에서 이렇게 모듈별로 파일을 만들곤 합니다.

2019-05-07 07:45 UTC, nigayo commented on oop/main.js
> +        let firstWord = input.match(/\w+/);
const/let의 차이를 잘 알고 쓰도록 하세요.

2019-05-07 07:45 UTC, nigayo commented on oop/main.js
> +const Error = new ErrorCheck();
Error 라는 객체가 있음으로 이름을 Error 라고 하면 곤란할 듯.
'예약어'에 대해서 한번 알아보세요.

2019-05-07 07:45 UTC, nigayo commented on oop/main.js
> +        let done = todoModel.todoList.filter(v => v.status === 'done').length;
const todolist = todoModel.todoList;
이렇게 변수에 저장해두고 쓰면 반복적인 코드를 조금더 줄일 수 있죠.

2019-05-07 07:45 UTC, nigayo commented on oop/main.js
> +        this.HistoryForm = function (model, name, id, status, tag){
HistoryForm생성자는 HistoryContorller안에 있기보다, 별도로 분리하는 게 좋습니다.
크기는 작지만 새로운 객체를 만드는 클래스이기 때문이죠.

2019-05-07 07:45 UTC, nigayo commented on oop/main.js
> +        if(this.undoHistory.length < 3) {
3과 같은 매직넘버 없애기~

2019-05-07 07:45 UTC, nigayo commented on oop/main.js
> +const TodoModel = class{
Model 역할이 명확한 편이라 좋아요.

2019-05-07 07:46 UTC, merged