Step5-3 : TUNA & YM 리뷰 내용 반영
code-squad/javascript-todo pull request #136
Opened 2019-04-30 06:33 UTC by dev-dongwon

리뷰 내용 반영해 step5-3 수정해서 올립니다. 이번이 마지막입니다 ㅜㅜ 
깃 사용이 미숙해 여러 번 재시도했고, 많은 것을 배울 수 있었습니다.
사용법을 꼭 숙지해 다음엔 실수 없도록 하겠습니다.

리뷰 내용은 README.md 에 정리해두었고, 참고하시면 될 것 같습니다.
감사합니다.

2019-04-30 07:58 UTC, nigayo commented
깃 미숙이 부끄러운게 아니고, 
깃 충돌을 해결하면서 새로운 걸 배우셨으니 잘 된 겁니다. ㅎㅎ

2019-04-30 08:20 UTC, crongro requested changes
리뷰드린 것 조금더 수정해보시고요. 

질문도 좀 남겼어요. 공부&답변 부탁드립니다!

2019-04-30 08:20 UTC, nigayo commented on class/app.js
> +const customException = require('./customException.js');
뭐는 소문자, 뭐는 대문자.
코드의 구현방식뿐아니라, 변수의 이름에서부터 일관성을 유지하는 게 좋겠죠?

2019-04-30 08:20 UTC, nigayo commented on class/app.js
> +const commandParser = new CommandParser();
위에는 cmd 아래는 command ,
일관성(x)

2019-04-30 08:20 UTC, nigayo commented on class/app.js
> +	utils.delay(0)
then 메서드의 동작방식에 대해서 설명을 달아주세요.

2019-04-30 08:20 UTC, nigayo commented on class/commandParser.js
> +		this.instruction[command[0]](command[1], command[2]);
command 0,1,2 를 변수에 할당해두면 더 의도가 드러나는 코드가 될거 같네요.

2019-04-30 08:20 UTC, nigayo commented on class/customException.js
> +        if (arr.includes(command)) result = true;
이 함수에서 result 변수는 불필요해보여요.
return true;
return false; 
이렇게 하면 될 듯.

2019-04-30 08:20 UTC, nigayo commented on class/instruction.js
> +const convertedData = JSON.parse(JSON.stringify(originData)).data;
이 코드에 대해서 설명해보세요.

2019-04-30 08:20 UTC, nigayo commented on class/instruction.js
> +	convertedData.forEach((value) => {
forEach({status} => {...

이렇게 바꾸고 이게 무슨 문법인지 댓글을 달아주세요.

2019-04-30 08:20 UTC, nigayo commented on class/instruction.js
> +	} else if (statusArr.includes(status)) {
if /else 로 하셔야겠네요.

2019-04-30 08:20 UTC, nigayo commented on class/instruction.js
> +	    if (!targetObj) customException.notExistIdException();
try 문이 한 줄만 커버하는 게 아니고, delete 함수 전체를 감싸서 커버하는 게 나아보여요.

try  {
  //여러코드들...
}

2019-04-30 08:20 UTC, nigayo commented on class/instruction.js
> +    undo() {
undo 메서드와 redo 메서드간의 중복코드가 보입니다.
해결해보세요 !

2019-04-30 08:20 UTC, nigayo commented on class/utils.js
> +const Utils = class {
utils에는 속성도 없어서, 생성자도 필요없는 메서드들의 묶음이네요.
객체리터럴로 단일객체를 정의해두고 쓰면 될 거 같네요.
class는 필요가 없죠.

2019-05-02 05:29 UTC, dev-dongwon commented on class/app.js
> +const customException = require('./customException.js');
변수 이름을 일관되게 upperCase로 작성하였습니다.
일관성 유지 되도록 신경쓰겠습니다!

2019-05-02 05:29 UTC, dev-dongwon commented on class/app.js
> +const commandParser = new CommandParser();
의미가 명확히 드러나도록 모두 command로 통일하였습니다.

2019-05-02 05:29 UTC, dev-dongwon commented on class/app.js
> +	utils.delay(0)
유틸로 만든 delay 함수에는 Promise 객체를 리턴하게 되어있고,
작업 성공 시 (fulfill) resolve 메서드를 호출하고, 응답이 없으면 reject 메서드를 호출합니다.
resolve 메서드를 호출하면 then()이 실행되고, reject 메서드가 호출되면 catch로 넘어가 에러를 처리하게 됩니다.

이 같은 작업은 Promise가 체이닝되어 then이 실행순서를 지키며 일어나게 됩니다.

2019-05-02 05:29 UTC, dev-dongwon commented on class/commandParser.js
> +		this.instruction[command[0]](command[1], command[2]);
의도가 명확히 드러나도록
primaryCommand, firstSubCommand, secondSubCommand 의 네이밍을 가진 변수에 할당했습니다.

2019-05-02 05:29 UTC, dev-dongwon commented on class/customException.js
> +        if (arr.includes(command)) result = true;
불필요한 변수를 쓰지 않고 바로 boolean 값을 리턴하도록 했습니다.

2019-05-02 05:29 UTC, dev-dongwon commented on class/instruction.js
> +const convertedData = JSON.parse(JSON.stringify(originData)).data;
json Data인 originData를 stringfy 해서 JSON 문자열로 변환한 다음, parse 명령어를 수행해 JSON 문자열을 javascript에서 사용할 수 있는 값이나 객체로 변환합니다.

2019-05-02 05:29 UTC, dev-dongwon commented on class/instruction.js
> +	convertedData.forEach((value) => {
객체 전체를 value로 받는 대신 구조분해할당 (destructuring)을 사용해 객체의 필요한 프로퍼티를 바로 뽑아 쓸 수 있도록 수정하였습니다.

2019-05-02 05:29 UTC, dev-dongwon commented on class/instruction.js
> +	} else if (statusArr.includes(status)) {
else if 대신 else로 분기하도록 수정하였습니다.

2019-05-02 05:29 UTC, dev-dongwon commented on class/instruction.js
> +	    if (!targetObj) customException.notExistIdException();
함수 전체를 감싸서 error를 캐치할 수 있도록 수정했습니다.

2019-05-02 05:29 UTC, dev-dongwon commented on class/instruction.js
> +    undo() {
객체에서 필요한 프로퍼티를 획득하는 과정이 중복되어
makeLogObj 라는 함수로 따로 분리해 구현했습니다.

2019-05-02 05:29 UTC, dev-dongwon commented on class/utils.js
> +const Utils = class {
class 대신 객체 리터럴로 리팩토링했습니다.

2019-05-02 05:30 UTC, dev-dongwon commented
리뷰해 주신 내용 모두 다시 한 번 검토해 수정했고, 공부할 내용을 짚어주신 것도 스터디를 완료했습니다. 다시 한 번 리뷰 부탁드립니다.

감사합니다.

2019-05-02 09:31 UTC, nigayo commented on class/app.js
> +	utils.delay(0)
then이 실행되나요? then으로 등록된 콜백이 실행되나요?

2019-05-02 09:35 UTC, dev-dongwon commented on class/app.js
> +	utils.delay(0)
정확히 then으로 등록된 콜백 함수가 실행됩니다. 콜백 함수가 실행된 후, 결과에 따라 Promise 객체의 resolve 나 reject 메서드를 호출하게 됩니다!

2019-05-02 09:41 UTC, crongro approved these changes
수고하셨어요.
설명을 잘  달아주셨네요. 그부분도 확인했어요.
구현한 코드에 대해서는 100%가깝게 설명할 수 있도록 늘 공부하시면 좋겠습니다.

2019-05-02 09:41 UTC, nigayo commented on class/app.js
> +	.then(() => {if (commandList[0] === 'update') return Utils.delay(3500);})
commandList[0] 도 썩 좋은 표현은 아니네요, 
destructuring을 사용해서 변수병으로 할당하는게 더 의도가 드러날 거 같네요.

2019-05-02 09:41 UTC, nigayo commented on class/commandParser.js
> +		let [primaryCommand, firstSubCommand, secondSubCommand] = [command[0], command[1], command[2]];
primaryCommand 가 의미를 정하기 어려운 경우라고 가정하고 이렇게 허용할 수 있겠죠.
만약 primaryCommand가 의미가 있다면 그 의미를 이름으로 지어야겠고요.

2019-05-02 09:41 UTC, nigayo commented on class/utils.js
> +    getRandomId : function(max, min) {
어 이거 왜 function을 붙였죠? 
수정전이 더 편리한 문법이라..

2019-05-02 09:42 UTC, merged