[PR] TodoList PR
code-squad/javascript-todo pull request #14
Opened 2018-03-27 06:38 UTC by antaehyeon

2018-03-27 07:58 UTC, crongro requested changes
이거 PR을 놓친거 같네요.

addWorkToDo 와 
showWorkList 등의 전역공간에 위치하고 있는 함수들을 
객체리터럴 형태로 묶어보세요.
예시)
var Todo = {
  showWorkList() {
  },
  addWorkToDo {
  } 
  ...
}

2018-04-10 06:01 UTC, nigayo commented
상당히 어려운 내용을 공부중이군요.
객체리터럴로 만들면서 좀더 자기것으로 알게 되길 바랄게요.

2018-04-12 02:01 UTC, crongro requested changes
기본적인 이름짓기를 좀더 신경써보세요.

현재는 모두 구체적이지 않은 이름들입니다.

2018-04-12 02:01 UTC, nigayo commented on ToDo.js
> +    works : [],
보다 구체적인 이름을 지어보세요.

2018-04-12 02:01 UTC, nigayo commented on ToDo.js
> +        const forIndexMatchingData = 1;
for는 어색합니다.
명사로 이름을 지으면 좋겠어요.

2018-04-12 02:01 UTC, nigayo commented on ToDo.js
> +        let date = new Date();
date는 무슨 date라는 구체적인 이름을 지어보세요

2018-04-12 02:01 UTC, nigayo commented on ToDo.js
> +            calDoneTime: function() {
cal이 뭐에요? 
calculate...

2018-04-12 02:01 UTC, nigayo commented on ToDo.js
> +        let mode = (state === "todo") ? "TO DO" : (state === "doing") ? "DOING" : "DONE";
3항연산자는 이것보다 길게는 쓰면 가독성이 떨어진다고 봐요.
지금정도는 괜찮고요.

2018-04-12 02:01 UTC, nigayo commented on ToDo.js
> +        let result = "";
여기도 이름이 별로.

2018-04-12 02:01 UTC, nigayo commented on ToDo.js
> +        for(let i=0; i<this.works.length; i++) {
함수형 메서드를 좀 다뤄볼래요? 
forEach/map/reduce로

2018-04-16 17:05 UTC, antaehyeon commented on ToDo.js
> +    works : [],
확인하였습니다.

2018-04-16 17:07 UTC, antaehyeon commented on ToDo.js
> +        const forIndexMatchingData = 1;
확인하였습니다

2018-04-16 17:14 UTC, antaehyeon commented on ToDo.js
> +        let date = new Date();
확인하였습니다 👍

2018-04-16 17:15 UTC, antaehyeon commented on ToDo.js
> +            calDoneTime: function() {
하..하.. 줄여쓰지 않겠습니다 :(

2018-04-16 17:15 UTC, antaehyeon commented on ToDo.js
> +        let mode = (state === "todo") ? "TO DO" : (state === "doing") ? "DOING" : "DONE";
확인하였습니다 👍

2018-04-16 17:16 UTC, antaehyeon commented on ToDo.js
> +        let result = "";
확인하였습니다 👍

2018-04-16 17:23 UTC, antaehyeon commented on ToDo.js
> +        for(let i=0; i<this.works.length; i++) {
확인하였습니다 👍

2018-04-17 06:59 UTC, crongro requested changes
클래스구현 그래도 괜찮아요.
조금 수정해보세요.

2018-04-17 06:59 UTC, nigayo commented on ToDo.js
> +const todo = class {
이런 방법이 가능하지만 일반적인 class 표기법을 따라주면 좋겠어요.

class Rectangle {
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
}

2018-04-17 06:59 UTC, nigayo commented on ToDo.js
> +        var workObj = {
const와 let으로만 사용해보세요.

2018-04-17 06:59 UTC, nigayo commented on ToDo.js
> +            if(work.state === state && mode === "DONE") {
forEach에 앞서서 filter메서드를 한번 쓰고 나서 처리하면 어때요?

2018-04-17 06:59 UTC, nigayo commented on ToDo.js
> +    for (let i=0; i < works.length; i++) {
forEach와 같은 메서드로 처리해보죠.

2018-04-17 06:59 UTC, nigayo commented on ToDo.js
> +    second -= ((hour * 60 * 60) + (minute * 60));
60*60  과 같은 값은 늘 계산하기보다, 3600 으로 미리 할당하는 것이 더 낫겠네요.

2018-04-17 06:59 UTC, nigayo commented on ToDo.js
> +function printDoneWorkList(data) {
printDoneWorkList 와 printCurrentState 함수는 클래스 밖에서 있는데요. 
이 두 녀석이 비슷한 성격이니 객체리터럴로 같이 묶어두는 것은 어떨까요.

2018-04-17 06:59 UTC, nigayo commented on ToDo.js
> +    var todoListDataGroup = [];
밖에서 모델(todoListDataGroup)을 가지고 있는데요. 
이녀석을 전역에서 제거하고 클래스 안으로 밀어버리면 좋겠어요.

2018-04-19 05:25 UTC, antaehyeon commented on ToDo.js
> +const todo = class {
확인하였습니다 👍

2018-04-19 05:26 UTC, antaehyeon commented on ToDo.js
> +        var workObj = {
확인하였습니다 👍

2018-04-19 05:42 UTC, antaehyeon commented on ToDo.js
> +    second -= ((hour * 60 * 60) + (minute * 60));
확인하였습니다 👍

2018-04-19 07:57 UTC, antaehyeon commented on ToDo.js
> +            if(work.state === state && mode === "DONE") {
확인하였습니다 👍

2018-04-19 07:57 UTC, antaehyeon commented on ToDo.js
> +    for (let i=0; i < works.length; i++) {
확인하였습니다 👍

2018-04-19 10:04 UTC, antaehyeon commented on ToDo.js
> +function printDoneWorkList(data) {
확인하였습니다 👍

2018-04-19 11:25 UTC, antaehyeon commented on ToDo.js
> +    var todoListDataGroup = [];
확인하였습니다 👍

2018-04-20 02:10 UTC, crongro requested changes
리뷰남깁니다

2018-04-20 02:10 UTC, crongro commented on ToDo.js
> +const print = {
객체나 클래스는 어떤 목적을 표시하는게 더 좋아요.
따라서 명사형태로 이름을 짓습니다.

2018-04-20 02:10 UTC, nigayo commented on ToDo.js
> +// singleton을 만든 이유는
todo라는 클래스의 역할을 고민해볼 필요가 있어요.
이 클래스는 todo관련 데이터(배열이나 객체형태)를 가지고 있으면서 조작을 하면 됩니다.
데이터는 객체의 속성으로 추가하면 됩니다.
그 데이터는 변경이 일어나야 하자나요?  추가/삭제/변경 등등
그걸 해주는 것이 그 클래스의 메서드입니다. 

따라서 todo클래스는 이런 모습일 수 있는거죠.

```javascript
class TODO {
  constructor() {
    this.todos = [];
  }

  addTodo(newTodo) {
    this.todos.push(newTodo);
  }

  getTodos() {
    return this.todos;
  }
  deleteTodo(id) {
    //일치하는 것을 찾아서 삭제..
  } 
}

const todo = new TODO();
todo.addTodo({id:1, content:"야호 주말에 놀아야지"});
console.log(todo.getTodos());
```

다른 친구가 구현한 코드인데 참고하세요.
https://github.com/Imdonguk/javascript-todo/blob/931291a67476b4bf7d22f6d784a5d9a8231ead67/todo.html

2018-04-20 02:10 UTC, nigayo commented on ToDo.js
> +let singleton = (function() {
singleton은 객체를 재사용하는 방법인데, 
이런 해법을 찾아서 해결하려는 시도는 매우 좋아요^^
다만, 현재 상황에서는 위에 class구조를 다시 구현해서 푸는 것이 더 좋은상태입니다. 제가 설명드린대로요.

2018-04-20 02:58 UTC, antaehyeon commented on ToDo.js
> +const print = {
확인하였습니다 👍

2018-04-20 03:24 UTC, antaehyeon commented on ToDo.js
> +// singleton을 만든 이유는
확인하였습니다 👍

2018-04-22 16:54 UTC, antaehyeon commented on ToDo.js
> +let singleton = (function() {
확인하였습니다 👍

2018-04-23 02:47 UTC, crongro approved these changes
class를 좀더 이해한 거 같네요.
이전 코드와 지금코드의 차이를 잘 이해하면서 
다음에 클래스 구현할때 참고하세요.

2018-04-23 02:47 UTC, nigayo commented on ToDo.js
> +    doneList(data) {
함수 이름은 항상 동사+명사로.
지금은 result를 반환하니까 결과를 만드는 함수네요.

2018-04-23 02:47 UTC, merged