[Youngdo212] todolist 구현
code-squad/javascript-todo pull request #15
Opened 2018-03-29 13:59 UTC by youngdo212

2018-03-30 04:43 UTC, crongro reviewed
이게 어느단계까지 구현한 것인지 comment좀 추가해주세요.

2018-03-30 05:52 UTC, youngdo212 commented
기본기능 + 소요시간계산까지 구현하였습니다

2018-03-30 07:26 UTC, crongro requested changes
객체로 구현하기 전에 조금 수정해보세요.

2018-03-30 07:26 UTC, nigayo commented on 180329_todolist.js
> +function command(str){
str보다는 좀더 의미있는 이름으로, 그냥 문자열은 아닐테니.

2018-03-30 07:26 UTC, nigayo commented on 180329_todolist.js
> +  thing["id"] = thingsList.length + 1;
음 나쁘진 않은데,  객체에 속성추가시, dot notation 을 쓰는게 일반적이에요.

2018-03-30 07:26 UTC, nigayo commented on 180329_todolist.js
> +  id = +id;
id++ 로 그냥 해도 되는거죠?

2018-03-30 08:31 UTC, youngdo212 commented on 180329_todolist.js
> +  id = +id;
문자열 id를 숫자로 바꾸기 위해 +를 붙였습니다

2018-04-02 08:31 UTC, crongro approved these changes
객체리터럴로 이제 표현해보세요.

2018-04-03 01:50 UTC, crongro requested changes
이렇게 불러서 사용하는 건 좋네요.  => TodoList.command(); (객체의 경우 대문자)

category와 thingsList를 합치기. 

id는 이름을 구체적으로 바꾸고, 이것도 데이터를 만드는 하나의 객체에 추가.
todoList와 Thing은 다른아이들. Thing은 list의 관심사항이 아니다. 따라서 분리.

command의 switch 없애보세요.(분기문 안쓰기)

reduce 를 활용.

2018-04-05 01:13 UTC, crongro requested changes
객체를 잘 만들었고요.
객체안에 메서드 크기도 좋습니다.
리뷰반영 좀더 해보세요.

2018-04-05 01:13 UTC, crongro commented on 180329_todolist.js
> +    fns[flag].call(this, ...details);
짝짝짝 ~
이 코드를 주석으로 설명해서 남겨주세요.

2018-04-05 01:13 UTC, nigayo commented on 180329_todolist.js
> +  createId: function(){
간단하지만 좋은 함수 같고요.
이름은 getId가 더 어울릴듯.

2018-04-05 01:13 UTC, nigayo commented on 180329_todolist.js
> +    this.Data.ThingsDict[id] = thing;
이부분을 한줄짜리 함수로 만들 수도 있겠네요.
setId()

2018-04-05 01:13 UTC, nigayo commented on 180329_todolist.js
>      console.log(result.join());
출력을 위한 거라면, 
JSON.stringify() 메서드를 쓸 수도 있어요.

2018-04-05 01:13 UTC, nigayo commented on 180329_todolist.js
> +    console.log(`id: ${id}, "${thing["name"]}" 항목이 새로 추가되었습니다`);
여기서 바로 console.log를 호출하지 않고, printStatus와 유사한 방식으로 동작하게 할 수 있을까요?
모두다 print해주는 기능인데 좀 다르게 동작해서 아쉽네요.

2018-04-05 01:13 UTC, nigayo commented on 180329_todolist.js
> +    let result = Object.keys(this.Data.ThingsDict);
result이름을 너무 자주 쓰네요 ㅎ
의도에 맞는 이름을 지어보세요.

2018-04-06 07:13 UTC, crongro approved these changes
리뷰내용 반영하시고요.
다음단계로 가보죠.

2018-04-06 07:13 UTC, nigayo commented on 180329_todolist.js
> +    // 실행 컨텍스트를 올바르기 위해서 call메소드를 사용하여 command함수가 실행되고 있는 컨텍스트인 this를 바인드합니다.
'command함수가 실행되고 있는 컨텍스트인 this를 바인드합니다'
=> 
'command함수가 실행되고 있는 context에서 참조하는 객체를 파라미터로 받은 인자(this)로 지정합니다"

2018-04-06 07:13 UTC, nigayo commented on 180329_todolist.js
> +    let result = Object.keys(this.Data.ThingsDict);
코드는 좋은데 result이름은 좀 별로네요 ㅎ

2018-04-06 07:13 UTC, nigayo commented on 180329_todolist.js
> +  measureTime: function(thing){
thing을 destructuring을 써서 바꿔보세요.

2018-04-06 07:14 UTC, merged