[Youngdo212] 할 일 관리 어플리케이션(todolist) 기능 추가
code-squad/javascript-todo pull request #17
Opened 2018-04-08 07:42 UTC by youngdo212

추가된 미션 완료하였습니다.
 1. ES6 classes 사용
 2. immutable 객체로 처리

-----------------------------
질문 : 
모듈에 들어있는 함수가 인자를 객체로 받도록 했습니다. 옳은 선택일까요?
그냥 콤마로 받으면 인자가 뭔지 알 수 없을 것 같아서요..

2018-04-09 09:49 UTC, nigayo commented
인자를 객체르 받는 건 추천되는 패턴이에요~

2018-04-09 10:07 UTC, crongro requested changes
immutable만든거 잘 봤습니다.
 Todolist 도 클래스를 만들어보세요.

2018-04-09 10:07 UTC, crongro commented on 180329_todolist.js
> +class Thing{
TodoList 객체도 Class 로 변경할 수 있겠네요 
결국 지금 구조에서는 두 개의 클래스가 존재.

2018-04-09 10:07 UTC, crongro commented on 180329_todolist.js
>      // ES6 문법인 distructuring과 rest parameter를 이용해 split된 값을 받습니다.
distructuring은 오타..혹시나해서.

2018-04-09 10:07 UTC, nigayo commented on 180329_todolist.js
> +    sameStatusGroup = sameStatusGroup.reduce((acc, id) => [...acc, this.makeSentence(id)], []);
method chaining으로 표현해보세요. 너무 길면 줄바꿈도 해두고요. 보기좋게.

2018-04-09 10:07 UTC, nigayo commented on 180329_todolist.js
> +    console.log(sameStatusGroup.join());
그냥 문자열로 출력해야 하는 것만이 목적이면,  여기서 배열을 만들 필요가 있을까요?

2018-04-09 10:07 UTC, nigayo commented on 180329_todolist.js
>      if(status === "done") this.endTime = (new Date()).getMilliseconds();
(new Date()).getMilliseconds()이 중복이네요.

2018-04-09 10:07 UTC, nigayo commented on immutable.js
> +function getDeletedPropertyObject({source, targetProp, initVal = {}}){
특정 속성을 제거하는 함수네요. 잘 분리해서 적용했어요.

지금은 불필요하지만, 만약 중첩된 객체구조라면 어떻게 처리해야 하는걸까요?

2018-04-09 12:00 UTC, youngdo212 commented on immutable.js
> +function getDeletedPropertyObject({source, targetProp, initVal = {}}){
```
let obj = {
  key1: {
    name: 'a',
    age: 12
  },
  key2: {
    name: 'b',
    age: 22,
    foo: 'i must be deleted'
  },
  key3: {
    name: 'c',
    age: 100
  },
}

getDeletedPropertyObject({source: obj,targetProp: 'key2', initVal: {key2:
getDeletedPropertyObject({source: obj.key2, targetProp: 'foo'})}})
```
이렇게 사용하려고 했는데.. 너무 긴데요?

2018-04-10 03:06 UTC, nigayo commented on immutable.js
> +function getDeletedPropertyObject({source, targetProp, initVal = {}}){
중첩된 구조는 좀 복잡하고 굉장히 번거로울 수밖에 없어요.
object spread operator를 써도 좀 불편할거고요. 이건 시도해볼만합니다.

immutable 라이브러리의 사용법을 훔쳐보고, 그와 유사하게 동작하는 함수를 만들어보세요.
(must be 아님)

2018-04-10 03:19 UTC, crongro requested changes
두 개의 클래스가 생겼네요.
좋아졌어요. 조금더 수정해보죠.

2018-04-10 03:19 UTC, crongro commented on 180329_todolist.js
> +    function recordTime(){return (new Date()).getMilliseconds();}
이게 꼭 함수여야 하나요?

2018-04-10 03:19 UTC, crongro commented on 180329_todolist.js
>      const [flag, ...details] = order.split(/\$/);
flag보다 좀더 의미있는 이름이 필요해보여요.

2018-04-10 03:19 UTC, crongro commented on 180329_todolist.js
> +    Thing.prototype.setStatus.call(thing, status);
만들어진 객체를 통해서 접근해야해요.

//어딘가에서 인스턴스를 만들고,
this.thing = new Thing(name);

//만들어진 인스턴스를 통해서 접근.
this.thing.setStatus(thing, status);

2018-04-10 03:19 UTC, crongro commented on 180329_todolist.js
>      return this.Data.ThingsDict[id];
searchThing 제거해도 좋을 듯.
내부에서 접근이기도하고, 간단한 로직이라 메서드를 통해서 접근하지 않아도 될 거 같아요.
유지할거면, getThing이 더 어울리지, search는 탐색하는 알고리즘이 있을 것으로 보이기도 하네요.

2018-04-10 08:43 UTC, youngdo212 commented on 180329_todolist.js
>      const [flag, ...details] = order.split(/\$/);
details는 괜찮나요?

2018-04-12 02:27 UTC, youngdo212 commented
todolist 클래스 안에 있던 프린트하는 코드들을 전부 밖으로 꺼냈습니다 : message객체에 담김
immutable.js 라이브러리는 아직 보고있는 중입니다. 중첩된 객체구조를 해결하는대로 PR하겠습니다!

2018-04-12 09:56 UTC, crongro approved these changes
immutable은 동작방식에 대해서 이해하고 넘어가도록 하죠.
다른 방법으로 좀더 실험해볼 것을 제가 준비하고 있어요.

지금까지 구현한 todo는 전체적으로 메서드 크기가 명확한편이라 좋아요.

message객체를 따로 분리해본 시도 좋습니다.
그런데, message객체는 독립적으로 동작하는 그런놈이라고 가정했을때는 message 객체가 getThing/getElapsedTime 등의 다른 클래스의 메서드를 의존하고 있는 상태라는 점은  좀 아쉽습니다. 대안도 있을거에요. 매개변수로 결과를 받아서 처리할 수도 있을테고요. 

이점은 참고하세요.

2018-04-12 09:56 UTC, merged