할일관리 애플리케이션
code-squad/javascript-todo pull request #2
Opened 2017-10-23 08:05 UTC by Eclatant

* ToDo ES5 -> ES6 Redux Chaining에서 가장 크게 얻어진 효과는 아래와 같다고 생각하였습니다.
- Chaining은 한 번은 만들어보고 싶어서, 고집스럽게 만든 것일 뿐, 크게 차이나는 효과가 있지는 않습니다.
- ES6 역시 작성과정을 조금 더 편하게 해주고, 가독성을 높일 뿐, 핵심적인 차이를 만들어내지는 않습니다.

- ES5로 코드를 작성할 때는 전체의 플로우를 보고, 대략적인 감으로 함수 즉 로직의 단위를 나누었던 것 같습니다.
- 그래서 각각의 명령어별로도 메소드 크기의 차이가 발생했을 것이고, 시작하고 끝나는 지점도 모두 달랐던 것 같습니다.
- 하지만 Redux를 차용해오면서, 명령어와 무관한 공통적인 단계별로 묶을 수 있게 되었고, 해당 스텝을 코드로 구성할 때 훨씬 편하게 느껴졌습니다. (이번 단계의 로직에서는 이러한 인풋이 들어와서 이러한 아웃풋까지만 만들어내는 것에 집중하면 되겠구나! 라는 마음으로 코딩하였습니다.)
- 해서 Input -> Validation -> ActionCreate -> Reducer -> View 의 Flow로 진행해보았습니다.

---

### Task Model(id, things)
- id, things, state, started, ended, runTime

### ToDoApp Class()
- input, action, tasks(task[]), record(Cache for ShortestRecord), createdId(Cache For addComplete), generateId(Closure)

- Static Method : log

- View Function : currentState, showTasks, shortestRecord

- actionCreator : input -> action

- reducer : setter by action

- view : output by getter

validateRequest : Regex

getRequest : rl.question + route

admin : cmd, state, messages 모음집

---

현재 shortestRecord를 구현하는 것은 cache? memoization? 을 활용하여
task를 done으로 변경해줄 때마다 검사하여 최신화시키는 방식을 취했습니다.

보다 느리게 할 수 있는 방식으로는 요청이 왔을 때마다 O(N)의 시간복잡도를 통해
전체 Task들을 한 번 순회하면서 값을 비교하여 알려주는 방식으로 해보았었습니다.

캐싱해둘 수 있는 것들은 최대한 캐싱을 하는 방향이 여러모로 좋은 것 같습니다, 감사합니다.

2017-10-23 08:47 UTC, nigayo commented
마이그레이션을 단계적으로 해보세요. 
예를들어, 전체 동작이 되는 보기는 어려워도 쉽게 구현할 수 있는 코드를 먼저 구현하고요, Chaining등은 그 다음 step으로 구현해서 적용해보는 거죠. 
처음부터 이런저런 기법을 섞어서 문제까지 푸는건 머리속이 너무 복잡해질 수 있어보여요.

2017-10-23 09:00 UTC, crongro requested changes
개선된 코드의 아이디어 좋아요. 
es5로 한번 수정해보죠.

2017-10-23 09:00 UTC, nigayo commented on Eclatant/todo-redux-chaining-es6.js
> +class Task {
똑같은 코드를 prototype 기반의 클래스로 변경해보세요.

2017-10-23 11:46 UTC, Eclatant commented on Eclatant/todo-redux-chaining-es6.js
> +class Task {
@nigayo 수정 완료하였습니다 :D

2017-10-24 00:46 UTC, crongro approved these changes
전체 프로그램의 클래스-메서드의 관계를 시각적으로 표현해서 보여주세요.

2017-10-24 00:46 UTC, nigayo commented on Eclatant/todo-redux-chaining-es6.js
> +const method = {
method 이름은 너무 일반적인 이름이라 별로네요.

2017-10-24 00:46 UTC, nigayo commented on Eclatant/todo-redux-chaining-es6.js
> +  showTasks(inputState) {
function 과 prototype을 사용한 객체생성방법을 이해하고 사용해보세요.
function A() {
}

A.prototype = {
 a : get() {}
}

2017-10-24 00:48 UTC, crongro requested changes
전체 프로그램의 클래스-메서드의 관계를 시각적으로 표현해서 보여주세요.

2017-10-24 08:37 UTC, crongro approved these changes
오늘 설명했듯이 branch를 잘 써서 개발해보시고, 리뷰대상이 아닌 예전버전의 코드는 PR에서 제외해주세요.

디자인리뷰 잘 했고요.

다음에 혹시 action/reducer를 사용할거면 객체에서 따로 분리하는 것까지 가보도록 해요.

2017-10-24 08:37 UTC, merged