[리오] 할일관리 애플리케이션 - STEP2
code-squad/javascript-todo pull request #22
Opened 2018-05-17 13:16 UTC by feanar729

STEP2 진행했습니다. `현재측정시간-저장된시간` 과의 차이가 크지 않아서 second단위로 method를 작동 되게 설계해 만들어 보았습니다 리뷰 부탁드립니다.

2018-05-18 01:40 UTC, crongro requested changes
요렇게 나오게 하셔야해요~

> "show$done;
> 'iOS공부하기, 3시간10분', '자바스크립트공부하기, 9시간31분', '주간회의 1시간40분'

2018-05-20 03:20 UTC, feanar729 commented
feedback 반영해 다시 제작 해봤습니다. 리뷰 부탁드립니다.

2018-05-21 02:13 UTC, crongro requested changes
inputCommand("update$1$done");
inputCommand("show$done");


이후에 아래처럼 문제가 생기네요.

//done목록에 id 1: 자바스크립트 공부하기 [ 완료시간: -318/ms ]

2018-05-25 07:35 UTC, feanar729 commented
데이터 구조를 나름대로 새롭게 바꿔서 다시 꼼꼼하게 refactoring을 시도 해보았습니다. 리뷰부탁드리겠습니다.

2018-05-28 02:15 UTC, crongro requested changes
아직도 버그가 있어요.
- add 이후에 id값이 중복으로 들어가는 이슈발생.
- 소요시간이 이상함.  ( Date클래스의 메서드를 잘못쓰고 계세요)

2018-05-28 02:15 UTC, nigayo commented
소프트웨어에 버그가 없는지 좀더 꼼꼼하게 테스트할 필요가 있어보입니다~

2018-05-29 06:52 UTC, crongro approved these changes
수 
고 
많
이
했
어
요
👍

2018-05-29 06:52 UTC, merged

2018-05-29 07:01 UTC, feanar729 commented
감사합니다~~