[리오] 할일관리 애플리케이션 - STEP4
code-squad/javascript-todo pull request #24
Opened 2018-06-01 05:28 UTC by feanar729

STEP4 진행 했습니다. 리뷰 부탁드립니다.

2018-06-01 06:30 UTC, crongro requested changes
객체사용법이 틀렸음요.

2018-06-01 11:11 UTC, feanar729 commented
피드백 반영해 다시 시도해봤습니다 리뷰 부탁드립니다.

2018-06-04 01:25 UTC, crongro approved these changes
todo는 여기까지 하면 될 거 같은데요.
class 문법은 잘 기억하고, 다음프로젝트 할때 class를 계속 써보면서 더 이해하도록 해보죠.

2018-06-04 01:25 UTC, crongro commented on todo.js
>      for (let i = 0; i < inputWord.length; i++) {
every 나 some 과 같은 배열함수로 이를 대체할 수 있을 거 같아요.

2018-06-04 01:25 UTC, merged