[새라] 할 일 관리 애플리케이션 STEP1 완료
code-squad/javascript-todo pull request #27
Opened 2018-07-16 14:15 UTC by sejungkim

할 일 관리 애플리케이션 STEP1 기능(add, show, update) 구현 완료했습니다.
리뷰 부탁드려요 :)

2018-07-17 00:21 UTC, crongro requested changes
잘 구현했네요.
리뷰남긴 부분만 추가로 확인해서 다시 push~!

2018-07-17 00:21 UTC, nigayo commented on todo.js
> +todoApp.command('update$2$doing');
아쉽게도 버그 하나가 있네요.
todoApp.command('update$2$doooooooooooing');
올바른 상태가 아니여도 들어가네요. 상태점검을 어딘가에서 하면 좋겠어요.

2018-07-17 00:21 UTC, nigayo commented on todo.js
> +    const stateCount = this.stateList.reduce((resultObj, state) => {
getStateCount 메서드가 불릴때마다, 반복적으로 이미 정해진 아래코드를 만들고 있네요.
'stateCount:{todo: 0, doing: 0, done: 0}' 
코딩할때 결과가 늘 동일한 것은 아닌지,  또는 반복적인 연산을 하고 있지 않은지 점검해보세요.

2018-07-17 00:21 UTC, nigayo commented on todo.js
> +      if (state === task.state) msg += `\n"${taskIdx + 1}, ${task.title}"`;
this.taskList를 reduce하기전에 filter함수를 먼저 거친다음에 reduce를 하는방식이 좀더 함수를 잘게 나눠서 처리할 수 있는 방법이죠.

2018-07-18 06:22 UTC, sejungkim commented
리뷰 반영 했습니다.
- update시, 바꾸려는 상태값에 대한 유효성 검사를 추가했습니다.
- getStateCount 함수에서 반복된 stateCount 객체 생성을 하지 않기 위해 stateCount를 함수 내 지역 객체 대신 todoApp 객체의 속성으로 변경하고, 이미 생성된 stateCount가 있는지 없는지 확인 후 생성을 하도록 변경했습니다.
- showTasksByState 함수에서 filter 메소드를 사용하여 조건에 따라 할 일 데이터들을 먼저 거르고, 필터링 된 데이터로 reduce 메소드를 사용하여 결과 메세지를 만들어 출력하도록 변경했습니다.

2018-07-18 07:09 UTC, crongro approved these changes
네 잘 수정했네요.
클래스나 객체를 만들때 클래스변수(인스턴스변수)를 없앨 수 있으면 없애려고 노력하세요.
예를들어, this.stateCount 를 없애고 지역변수로 처리할수도 있을거에요. 

참고하세요. 머지합니다.

2018-07-18 07:09 UTC, merged