[솔로몬] 할일관리 애필르케이션 Step4
code-squad/javascript-todo pull request #29
Opened 2018-07-23 11:50 UTC by juchan96

클래스로 구현해보았습니다! 리뷰 부탁 드리요오

2018-07-24 01:35 UTC, crongro requested changes
class구현은 잘했어요.

몇개 중복코드에 대한 리뷰를 남겼으니 고민+수정 해서 다시 
push 해주세요~

2018-07-24 01:35 UTC, nigayo commented on step4.js
> +    this.item = [];
클래스의 생성자함수에서는 주로 
지금처럼 클래스의 속성으로 사용될 값들을 정의합니다. 잘했어요.

2018-07-24 01:35 UTC, nigayo commented on step4.js
> +    const showId = dataId;
dataId를 이미 받았기 때문에 불필요하게 showId 라는 변수를 하나 더 만들필요는 없어보여요.

2018-07-24 01:35 UTC, nigayo commented on step4.js
> +    const accordData = this.item.filter(element => state === element.state)
accordData라는 이름은 의미를 알기 어려운 변수네이밍 같아요.

2018-07-24 01:35 UTC, nigayo commented on step4.js
> +        returnMsg += `ID: ${element.id}, taskName: ${element.taskName}, state: ${element.state}, leadTime: ${element.leadTime}\n`;
위에 조건과 지금 여기 조건이 비슷한데요?
leadTime만 추가되는 것으로 보여요.
중복코드를 없애보세요.

2018-07-24 01:35 UTC, nigayo commented on step4.js
> +    } else return returnMsg = `"${state}"는 올바르지 않은 state입니다. 올바른 state를 입력해주세요.`;
지금 여기 if/else 조건문을 바꾸면 코드의 indent 가 줄어들거에요.
if(!this.checkState(state)) {}

2018-07-24 01:35 UTC, nigayo commented on step4.js
> +    else if (state === "done") return Date.now() - initLeadTime;
여기 코드도 약간 중복을 없앨 수 있을듯.
Data.now()가 두번쓰이지 않고 한번만 코드에 표현가능할거 같은데요? 고민해보세요.

2018-07-25 05:18 UTC, juchan96 commented
피드백 해주신 내용 수정해보았습니다!!

2018-07-25 08:08 UTC, crongro approved these changes
잘 개선했네요.
리뷰남겨요.

2018-07-25 08:08 UTC, nigayo commented on step4.js
> +    else {
이미 위의 조건문에서 return 했으니, 여기서는 else문이 필요없습니다.

2018-07-25 08:08 UTC, nigayo commented on step4.js
> +        returnMsg += `${msg}, leadTime: ${element.leadTime}\n`;
항상 코드구현후에, 리팩토링을 하는 습관을 가져보세요.
첫번째는 중복을 찾는겁니다.

2018-07-25 08:08 UTC, merged

2018-07-25 09:40 UTC, juchan96 commented
네네! 더 신경써보도록 해보겠습니다 감사합니다아