Wfe luigi
code-squad/javascript-todo pull request #3
Opened 2017-10-24 01:26 UTC by wfe-luigi

2017-10-24 01:52 UTC, nigayo commented
순서도 좋아요. 
다음에는 더 구체적인 코드형태를 표현하면 더 좋겠어요.

2017-10-24 01:56 UTC, crongro requested changes
수정해보세요~

2017-10-24 01:56 UTC, nigayo commented on todo.js
> +    console.log("현재상태 ", flag);
이전처럼 console.log로 보여지는 부분을 별도 공통함수나 유틸리티로 만들어보세요.

2017-10-24 01:56 UTC, nigayo commented on todo.js
> +    for (var i = 0; i < arguments.length; i++) console.log(arguments[i]);
{} 는 가급적 생략하지 않는 게 좋아요.

2017-10-24 01:56 UTC, nigayo commented on todo.js
> +function printMsg() {
전체코드를 객체리터럴 형태로 만들어볼래요?

2017-10-24 02:03 UTC, wfe-luigi commented on todo.js
> +    for (var i = 0; i < arguments.length; i++) console.log(arguments[i]);
네

2017-10-24 02:03 UTC, wfe-luigi commented on todo.js
> +    console.log("현재상태 ", flag);
네

2017-10-26 00:23 UTC, crongro approved these changes
수고하셨어요.

2017-10-26 00:23 UTC, nigayo commented on todo.js
> +        for (property in obj) {
더 빠른 알고리즘이 없는지 찾아보세요.
관련해서 제대로 이해하고 넘어가길 바랄게요.

2017-10-30 01:37 UTC, crongro requested changes
setState메서드만 좀더 개선해보죠.

2017-10-30 01:37 UTC, nigayo commented on todo.js
> +    setState: function (index, value) {
if - for - if .. 상태가 지나치게 중첩되어 있습니다.
이 부분의 깊이있어 보이는 코드 구조를 
단순하게 바꿔보도록 해보면 좋겠어요.

2017-11-02 05:47 UTC, crongro approved these changes
prototype을 이해하고 다음단계로 가세요~
approve합니다.

2017-11-02 05:47 UTC, crongro commented on util.js
> +    cmdChecker: function (cmd) {
util을 분리한 건 좋은데요, 다른 코드에서 재사용할 수는 없어보여요.
좀더 범용성을 늘려보면 좋겠어요.

2017-11-02 05:47 UTC, nigayo commented on todo4.js
> +                    result += "\"" + task[property].title + ", " + task[property].runtime + "초\" ";
for-if 의 깊이는 이정도가 끝인거 같아요. 더 깊게는 짜지 마세요~

2017-11-02 05:47 UTC, nigayo commented on todo4.js
> +        var count = Task.prototype.count;
이렇게 직접 사용하지 않고, 
var task = new Task();
task.count

이런식으로 인스턴스를 만들고 메서드를 호출하는 방법을 사용합니다.

2017-11-02 05:47 UTC, nigayo commented on todo4.js
> +                    Task.prototype.minTaskTime = task.runtime;
위 count와 마찬가지입니다.

2017-11-02 05:47 UTC, merged