Lecture 3, Step1 - 할일관리 어플리케이션
code-squad/javascript-todo pull request #36
Opened 2018-09-30 02:30 UTC by pdvonzoo

1. 객체 리터럴 형태로 구현했습니다.
2. add, remove, update method를 통해 할일들을 추가, 제거, 업데이트 할 수 있도록 구현하였습니다.
3. showActiveMessage의 함수로 각 위의 각 메소드가 실행되었을때 메세지 처리를 하였습니다.
4. getCurrentStatus의 함수를 통해 'todo', 'done', 'doing'의 숫자를 카운팅한 후 showCurrentStatus 함수로 각 상태를 출력하도록 구현하였습니다.
5. 객체의 id값에 디폴트 값을 1로 두었고 add 메소드가 실행될 때마다 id값에 1을 더하여 id 키 값을 구별하였습니다.

살펴보신 후 피드백 주시면 갑사하겠습니다.

2018-09-30 12:18 UTC, nigayo commented
PR보내실때 무엇을 구현했는지 설명까지는 안하셔도 될 거 같아요~
그것은 코드와 커밋로그에서 알수가 있어요.

특별히 전달하고 싶은 내용/궁금증등을 남겨주시면 좋겠어요

2018-09-30 12:18 UTC, nigayo commented
커밋로그는 좀더 자세하게 작성하셔도 좋겠고요.

2018-09-30 13:05 UTC, crongro requested changes
수고하셨네요.
리뷰남겨드린 것(버그포함) 한번 수정해보세요~

2018-09-30 13:05 UTC, crongro commented on todo.js
> +    id : 1,
참고로, 
더 유니크한 값을 생성하는 방법도 있긴해요. (uuid라는 것도 있고요. 별도 라이브러리를 써야하지만) 
날짜값을 재료로 random으로 생성할 수도 있죠.

2018-09-30 13:05 UTC, crongro commented on todo.js
> +        this.todos.push({
자료구조가 복잡하지 않고 단순하며 상태를 다 담고 있네요.
todos 에 이렇게 id/tag/status/name 넣은건 아주 잘 하신거 같네요.

2018-09-30 13:05 UTC, crongro commented on todo.js
> +    getCurrentStatus(todo, done, doing){
todo, done, doing을 파라미터로 받았어야 했나? 싶은 생각이 드네요.
명확해서 좋긴한데요. 그럴거면 인자 3개가 아니고, 하나의 배열에 담아서 받는게 나을 수도 있을거 같아요.

2018-09-30 13:05 UTC, crongro commented on todo.js
> +        let todo_count,done_count,doing_count;
이녀석들을 각각 변수로 만들지 않고 객체로 만들어서 담을 수도 있을거에요.
이렇게 바꾸고 아래 코드를 한번 수정해보세요.

const countObj = {todo:0, done:0, doing:0}

2018-09-30 13:05 UTC, nigayo commented on todo.js
> +        let prevStatus = this.todos[id-1].status;
버그가 있을거 같네요.
만약 remove를 여러번 한 이후에 update하면 잘 될까요?

2018-09-30 13:41 UTC, pdvonzoo commented on todo.js
> +    id : 1,
피드백 감사합니다. id값을 유니크하게 담는 부분에 대해서 고민을 많이 했는데요~ uuid에 대해서도 공부해보고 날짜값으로 유니크한 id값을 생성하는 방법도 찾아보겠습니다.

2018-09-30 14:04 UTC, pdvonzoo commented on todo.js
> +        let prevStatus = this.todos[id-1].status;
splice 메소드로 제거를 해서 todos 값들이 id 값과 매칭되지 않게 밀리겠군요..수정해서 다시 올리겠습니다! 감사합니다.

2018-10-02 08:16 UTC, nigayo commented on todo.js
> +        let prevStatus = this.todos[id-1].status;
(아 추가 리뷰가 늦었네요)
이렇게 ..상태 맞추는건 쉬운게 아니에요. 그때그때 계산해서 추출해내는게 좀더 정확한방법입니다.

2018-10-02 08:24 UTC, crongro requested changes
아고..리뷰가 좀 늦었네요.
안타깝지만 조금 수정하고 넘아가도록 해요! ^^

2018-10-02 08:24 UTC, crongro commented on todo.js
> +    findIdex(id){
findIdex, 와 findDataById 가 중복적으로 많이 호출되는 상황이네요.
조금 줄이는 코드로 변경해보세요!

2018-10-02 08:24 UTC, crongro commented on todo.js
> +            countObj[v.status] = (countObj[v.status])  ? countObj[v.status] + 1 : 1;
조건이 맞으면 그냥 1만 증가시켜주면 되는거 아닌가보네요? 
여기서 1을 증가시킬필요는 없을 듯. (0도 1증가하면 1이라..)

2018-10-03 12:14 UTC, crongro approved these changes
점점 용도에 맞는 함수를 찾아서 잘 사용하는 거 같네요.
reduce도 좀더 적극적으로 사용해보려고 해보세요~

다음단계로 가요!

2018-10-03 12:14 UTC, merged