Lec3 - Step2
code-squad/javascript-todo pull request #37
Opened 2018-10-01 05:28 UTC by cohily12

todo 리스트를 출력하는 메소드를 추가하였습니다.
-. 리팩토링을 한다고는 했으나, case별 출력결과가 조금씩 달라 메소드를 합치는 것이 쉽지 않았습니다.

확인 후 많은 피드백 주세요~~!!

2018-10-01 10:12 UTC, crongro requested changes
두 개의 객체로 나눈 것은 나쁘지 않았습니다.
별도의 print객체에서 todo객체를 가져와서 출력하는 방식은 약간 별로인거 같고요.
외부에서는 한개의 객체를 통해서 뭐든게 이뤄지는 게 더 좋죠.(즉 밖에서 printTodo를 모르게.. 그건 todo 객체라 호출해서 처리하는 방식으로..)

데이터구조도 약간 이상하고요(id속성부분)

고민을 해보시고, 선택적인 수정을 해보시길 바랍니다.
지금 구현한 것이 틀린 구조는 아님에도, 자칫 대대적인 수정(?)이 될 수도 있어서요. 흑;

2018-10-01 10:12 UTC, crongro commented on index.js
> +        setTimeout(function(){
시간을 2 -> 5 > 7로 주지말고요, 
2초뒤에 콜백실행 이후 -> 다음settimeout 이렇게 호출되도록 해보세요~ 
원래 요구사항이 그거입니다.

2018-10-01 10:12 UTC, crongro commented on index.js
> +            if(task.tag) !tagObj[task.tag] ? tagObj[task.tag] = [task] : tagObj[task.tag].push(task);
여기 삼항연산자는 좀 긴코드를 담고 있네요. 
조건문으로 바꾸는 게 좀더 나을 듯 합니다.

2018-10-01 10:12 UTC, crongro commented on index.js
> +                const tagStr = todoTag[status].reduce((str, task) => str += `\n- ${task.id}번, ${task.name}`, `[ ${status} , 총${todoTag[status].length}개 ]`);
reduce를 사용한 건 좋은데요.
너무 코드가 길게 표현됐네요. 개행이라도 하면 좋겠어요.

2018-10-01 10:12 UTC, crongro commented on index.js
> +                resultStr += tagStr + '\n\n';
조건문마다 중복된 코드임으로 조건문 이후로 옮겨도 되겠네요.

2018-10-01 10:12 UTC, crongro commented on index.js
> +        const todoTag = this.getTodoByStatus(this.getTodoByTag(tag));
showTag에서 todoTag를 얻기 위해서, 
getTodoByStatus, getTodoByTag 두개를 호출하고 있는데요.
showTag입장에서는 한개만 호출해서 값을 얻어오면 좋겠어요~ (한개만 알면 좋죠)

2018-10-01 10:12 UTC, crongro commented on index.js
> +        this.id[task.id] = task;
todo 자료구조가 직관적인 형태가 아니에요.
todo아래 id와 taskid가 있지만, 실제로 id속성은 배열을 가지고 있는 형태네요.
둘 다 어떤 id인지를 표현할거 같은 느낌입니다.
todo 아래에는 그냥 list로 배열형태로 존재하는 게 가장 간단하고 예상할 수 있는 자료구조 같아요.
taskid라는 속성도 불필요해보이고요.(마지막값을 가지고 있기때문인가요?) 

이 구조를 바꾸면 코드가 너무 크게 바뀔거 같으니, 참고만 하셔도 좋습니다.

2018-10-01 10:12 UTC, crongro commented on index.js
> +todoPrint.showTag('programming');
todoPrint를 별도 객체로 만든건 좋은데요. 
이렇게 여기서 부르면, todoPrint안에서 todo 객체에 접근해서 사용하게 되는셈이죠. 
이렇게 할꺼면, todoPrint할때 todo의 값을 받아서 넣어주는 것도 방법입니다.
todo.update(todolist, {}); 이런식으로 todolist같은 정보를 전달해주는 거죠.

2018-10-01 10:12 UTC, nigayo commented on index.js
> +todoPrint.showTag('programming');
그리고 지금과 반대로, 
todo.add 이후에 todo객체에서 todoPrint를 호출해서 출력을 위임시키는 흐름은 어떨까요?

2018-10-01 10:49 UTC, cohily12 commented on index.js
> +        this.id[task.id] = task;
배열의 길이나 인덱스의 의존성을 낮추고자, update, remove 시 인자로 받는 id값을 todo.id라는 객체형태의 리스트에 바로 접근하고자 했던 것이 자료구조가 다소 이상하게 된거 같네요.
유니크한 id값을 부여하는 거면 예시에 나와있는 거와는 다르게 id값이 1,2,3 이런 식일 필요는 없는 건가요?

2018-10-02 17:34 UTC, cohily12 commented
todo 관리 객체의 자료구조를 바꿔보았습니다.
-. task의 id는 날짜를 이용하여 고유의 값을 가지게 해보았습니다.
-. todo 관리 객체와 print 객체를 분리하였습니다.

todo 관리 객체에 다소 수정이 많았는데, 방향이 맞는 지 확인 부탁드립니다.
피드백 주시면 감사하겠습니다~~~

2018-10-04 21:26 UTC, crongro requested changes
잘 수정했네요.

리뷰남겨요~ 조금더 수정하고 바로 넘어가죠

2018-10-04 21:26 UTC, crongro commented on index.js
> +        PrintTodo.prototype.commandResult.call(this, 'add', task);
이렇게 접근은 되지만, 
다음처럼 객체의 메서드로 접근하는게 표현도 간단하고, 일반적인 방법입니다. 

const printTodo = new PrintTodo();
const Todo = new Todo(printTodo);

add(task) {
 ...
 this.printTodo.commandResult('add', task);
}

2018-10-04 21:26 UTC, crongro commented on index.js
> +            if(todoByTag[status]){
조건이 중첩된 코드네요.
false 조건에서 빨리 반환~

2018-10-04 21:26 UTC, crongro commented on index.js
> +        setTimeout(function(){
이부분은 재귀적으로 한번 구현해볼래요? 
지금은 보기가...좋지 않죠.

2018-10-05 08:24 UTC, cohily12 commented
말씀하신 부분 수정해보았습니다.
피드백 부탁드립니다~

2018-10-06 00:25 UTC, crongro approved these changes
잘 했어요~!
리뷰는 조금 남겨요.

다음단계로 가보시죠.

2018-10-06 00:25 UTC, crongro commented on index.js
> +        this.printTodo = new PrintTodo;
잘했어요.
두 객체의 결합도를 조금더 낮추려면 
Todo가 생성될때 생성자의 인자로 객체(인스턴스)를 받으면 됩니다.

2018-10-06 00:25 UTC, crongro commented on index.js
> +        else if(targetTask.startTime || targetTask.spentTime){
조건문에 { } 가 있으면 일관되게 있는게 좀더 보기 좋을 듯해요.

2018-10-06 00:25 UTC, crongro commented on index.js
> +        const countTodoStatus = (status) => todoList.filter(task => task.status === status).length;
filter는 이제 잘 활용하고 있군요. 
잘했어요.

2018-10-06 00:25 UTC, crongro commented on index.js
> +                todoByTag[status].reduce((accStr, task) => {
reduce도 잘 썼어요~

2018-10-06 00:25 UTC, crongro commented on index.js
> +                todoByTags[tag].reduce((accStr, task) => {
참고로  고차함수들의 콜백함수도 모두 분리해서 선언할 수 있는거 알죠? 이렇게 하면 재사용도 되고 코드도 더 빨리 읽혀요.

makeTaskResultByTag(accStr, task) {
...
}

 todoByTags[tag].reduce( makeTaskResultByTag );

2018-10-06 00:25 UTC, crongro commented on index.js
> +        const asynTime = [2000, 3000, 2000];
보통 이런값은 변경된다고 가정하고 함수의 인자로 받는게 좀더 낫아요. 함수의 인자는 일종의 옵션들이죠.

2018-10-06 00:25 UTC, crongro commented on index.js
> +        const asynPrint = (status) => {
👍

2018-10-06 00:25 UTC, merged