[Lecture 3 - Step 3]
code-squad/javascript-todo pull request #38
Opened 2018-10-01 13:46 UTC by Vanary

스텝3 첫 PR입니다.

연습차, 고차함수를 써서 출력용 객체 todoPrint 도 한번 리팩토링해봤습니다.

검토 부탁드립니다 ^^~

2018-10-02 03:20 UTC, crongro requested changes
객체를 잘 나눴어요.  💯 

그런데 출력을 위한 객체를 만들라는 것을 제가 잘못전달했나봐요;
별도로 콘솔에서 호출해야 하는거군요. todo가 대신 todoPrint를 호출해주면 좋겠어요~
그러면서 출력관련 내용을 todoPrint로 더 많이 위임시켜보는 거죠.

그외 몇개 리뷰남깁니다.

그리고 아래 버그가 좀 있어요.
- add/update/remove, undo/redo를 하고 나서 현재상태정보가 남은갯수랑 일치하지 않음.

2018-10-02 03:20 UTC, crongro commented on todo.js
>      countOfStatus: {todo: 0, doing: 0, done: 0},
이렇게 상태관리를 하면 동기화해야 하는 일이 생겨서, 버그가 생길확률이 조금더 높을거에요.

2018-10-02 03:20 UTC, crongro commented on todo.js
> +const todoErrorCheck = {
적절하게 에러를 처리하는 객체를 잘 만들었네요.

2018-10-02 03:20 UTC, nigayo commented on todo.js
> +            console.log(`[error] 할 일 목록 todo에 이미 같은 이름의 할 일이 존재합니다.`);
에러가 발생한 상태인데 return true 하는건 어색해보여요.

2018-10-02 03:20 UTC, nigayo commented on todo.js
> +        return (isTaskExists) ? false : true
다른표현법으로 !! 를 써보세요~

2018-10-02 03:20 UTC, nigayo commented on todo.js
> +        if(isAnyErrors) return false
isArrayErrors 보다는 bArrayErrors 라고 이름짓는 것이 좀더 일반적.

2018-10-02 03:20 UTC, nigayo commented on todo.js
>          this.printUpdateResult('update', {taskId: id, taskName: targetTaskName, prevStatus: currentStatus, nextStatus: newStatus});
이함수는 출력을 하는 함수인데요.
 todoPrint객체에 포함되는 것이 더 의미있어보여요.

2018-10-02 03:20 UTC, nigayo commented on todo.js
>          targetTask.status = newStatus;
함수를 더 잘 활용하려면 이정도 2줄이라도 묶어서 함수로 만들수도 있죠.

2018-10-02 03:20 UTC, nigayo commented on todo.js
> +        this.history.push({type: actionType, args: args, data:actionData});
history 를 사용하는 건 괜찮은 아이디어 같아요.
물론 이런건 잘 업데이트 관리를 하지 않으면 안되겠죠.

2018-10-02 03:20 UTC, nigayo commented on todo.js
>      printTasksAsync(groupedTaskObj, sequenceArr, sequenceIdx = 0) {
이함수 아래쪽의 
todoPrint.showTasksByStatus(status);
코드도 this를 사용해보세요~

2018-10-02 03:20 UTC, nigayo commented on todo.js
> +        const lastAction = todoUndoRedo.history.pop();
lastAction 을 todo객체가 추출해서 주는 게 좋을까요? 
아니면, 
todoUndoRedo의 속성임으로, todoUndoRedo객체가 알아서 뽑아서 처리하는게 좋을까요? 

전 후자가 좀더 나을 거 같아요.

2018-10-02 03:20 UTC, nigayo commented on todo.js
> +        // Convert resultObj into printable String
데이터 조작은 잘 했어요.
함수의 내용이 좀 큰데, 좀더 분리해볼래요? 
reduce가 중첩되어 있는 함수라서 가독성은 별로 좋지 않네요.

2018-10-02 03:20 UTC, nigayo commented on todo.js
> +        // Convert resultObj into printable String
(원래 저런 템플릿 작업이 지저분합니다..)

2018-10-02 08:16 UTC, Vanary commented on todo.js
> +        if(isAnyErrors) return false
헝가리안 표기법을 알아보게 되었습니다.

2018-10-03 05:55 UTC, Vanary commented on todo.js
>      countOfStatus: {todo: 0, doing: 0, done: 0},
remove 동작을 되돌릴 때 countOfStatus를 업데이트하지 않고 있었습니다. 수정했습니다.

2018-10-03 06:04 UTC, Vanary commented
피드백 주신 부분들 수정했습니다. 

작지만 뚜렷한 제 할일이 있는 기능들을 추상화해서 쓰는 경험을 해본 것 같습니다.

검토 부탁드립니다 ^^~

2018-10-04 02:53 UTC, crongro approved these changes
객체가 많아지면 구현하면서 객체간의 관계를 정리해보세요.
상호호출같은 부분이 불가피 할 수도 있지만, 없다면 더 좋은객체관계이기도 해요.

코드 구현은 별로 흠잘을때 없이 잘 했어요.
리뷰는 참고해서 필요하면 수정하시고 다음단계 진행하세요.

2018-10-04 02:53 UTC, crongro commented on todo.js
> +            todo.updateStatusCount([targetTask.status, -1]);
객체가 서로 같이 호출하는 건 좋지 않아요. (상호호출)
흐름이 복잡해보이거든요. 
todoUndoRedo객체에서는 todo객체의 메서드를 호출하지 않을 수 있을지 검토해보세요.

그리고 todo -> todoUndoRedo 를 부를때 필요한 데이터를 전달하는 것은 나쁘지 않고요.

2018-10-04 02:53 UTC, nigayo commented on todo.js
> +    convertToFormattedStr: {
이 객체가 상당히 맘에 드네요.
복잡하지만 비슷한 녀석들을 객체안의 객체로 만든건 좋은 시도입니다.(이렇게 계층을 만드는 것을 네임스페이스라고도 해요)
아무튼 이녀석 덕분에 복잡해질 수 있는 print의 public메서드들이 간단해보여요. 좋습니다.

2018-10-04 02:53 UTC, nigayo commented on todo.js
> +            const makeHeader = (workingStr, tag) => `${(workingStr) ? `\n\n` : ''}[ ${tag} , 총 ${objToPrint[tag].length} 개 ]`;
makeHeader처럼 복잡한 reduce 내의 함수도 이렇게 분리해서 선언할 수 있는거죠.
잘했음.

2018-10-04 02:53 UTC, merged