커밋 로그(할 일 관리 어플리케이션) step1
code-squad/javascript-todo pull request #39
Opened 2018-10-02 05:40 UTC by cocoa-salon

-데이터에 해당하는 객체(할일목록 todoList)는 로직과 분리하였습니다.
-id와 현재 상태를 나타내는 속성은 메소드와 별도로 생성하였습니다. 
-증감연산자를 사용하여 id값이 중복되지 않도록 하였습니다. 
-현재 상태를 나타내는 메소드를 별도로 정의하여 각각의 메소드를 통해 호출하도록 하였습니다. 
-toLowerCase() 메소드를 사용하여 대소문자 상관 없이 일정한 결과를 리턴하도록 하였습니다. 
-메소드 호출시(add, update, remove) 배열을 한번만 순회하여 본래 목적을 수행하는 동시에 현재 상태에 자동으로 반영하도록 하였습니다. 
감사합니다.

2018-10-02 07:48 UTC, crongro requested changes
몇개 수정요청드립니다~

2018-10-02 07:48 UTC, nigayo commented on myTask.html
> +        const todoList = [];
javascript 코드를 실전에서는 html안에 이렇게 표현하는 건 드물어요.

<script src="todo.js"></script>
 
이렇게 별로 파일로 개발해서 보내주세요~

2018-10-02 07:48 UTC, nigayo commented on myTask.html
> +        const todo = {
todoList는 todo객체에서 가장 중요하고 필요로 하는 객체의 속성(원소)입니다.
따라서 todo객체 안에 있어야 하죠.

const todo = {
  todolist : [],
  addTodo(){}
}

이렇게 동작되어야해요! ^^

2018-10-02 07:48 UTC, nigayo commented on myTask.html
> +            status: {
todolist 에 이 힌트가 이미 있죠? 
status 를 통해서 동기화하지 않고 todoList에서 그때그때 값을 구하는 방법을 고민해보세요.
그렇게 되면 모든 상태에서 status를 맞춰야한다! 는 부담감이 없어질거에요.

2018-10-02 07:48 UTC, nigayo commented on myTask.html
> +                this.todoId++;
마지막 id값인가요? 잘 동기화 시켜야겠네요.
이름도 좀더 구체적으로 수정하면 더 좋겠고요.

2018-10-02 07:48 UTC, nigayo commented on myTask.html
> +                    if (val.todoId === info.id) {
forEach전에 filter를 먼저 써보는 건 어때요?

2018-10-02 12:08 UTC, cocoa-salon commented
-스크립트 코드를 js파일로 분리하였습니다. 
-할 일 목록(todoList)을 todo 객체에 포함하였습니다. 
-id의 변수명을 taskId로 수정하였습니다. 
-todoList에서 현재 상태 값을 바로 확인하는 메소드를 정의하였습니다. 
-업데이트 메소드 정의시 메소드 체인을 이용하였습니다.(filter, forEach)

감사합니다.

2018-10-04 21:32 UTC, crongro approved these changes
수고하셨어요. 다음단계로 가서 기능을 추가해보시죠!

리뷰남긴 부분을 포함해서 개발 진행해주세요.

2018-10-04 21:32 UTC, nigayo commented on myTask.js
> +        const result = {};
지금처럼해도 되고, 아래처럼 표현해둬도 좋고요.

const countMap = {
 todo : 0, doing:0, done:0
}

2018-10-04 21:32 UTC, nigayo commented on myTask.js
> +            if (result[val.status] === 0) {
요렇게 간단한 경우에 3항연산자 써보세요~

2018-10-04 21:32 UTC, nigayo commented on myTask.js
> +        this.todoList.filter(val =>
여기 개행이  어색합니다.
이런식으로  문단(?)별로 한줄에 보이게~

  this.todoList.filter(val =>val.taskId === info.id)
                       .forEach(val => {
                             taskName = val.name;

2018-10-04 21:32 UTC, merged