Lecture3 - step1. 기본기능 구현
code-squad/javascript-todo pull request #40
Opened 2018-10-02 06:39 UTC by HTMLhead

saveData라는 객체에 할일들의 배열과 id들의 배열을 저장해서 계속해서 사용하는 구조로 만들어 보았습니다.
1. todo객체의 getRanNum함수로 랜덤한 숫자id를 만들어 냅니다. 만약 같은 id가 만들어진다면 다시한번 랜덤한 숫자를 생성되게 만들었습니다. todo.add함수에 이용됩니다.
2. 지우거나 만들때마다 getStatusNum함수를 사용해서 todo와doing, done의 상태를 최신화 해주었습니다.
3.  printTask함수는 입력된 모든 할 일 들을 출력해줍니다.
4.  printSameTag는 tag를 입력받아 그 tag를 가진 할 일 들을 출력해줍니다.

* '특히' 노력한점

1. 중복되는 id값을 없애기 위해서 고민하고 또 고민했습니다.

* 궁금한점

1. saveData객체를 새로 만들어서 사용했는데, 이게 좋은방법인지 나쁜방법인지 궁금합니다.

2018-10-02 08:08 UTC, crongro requested changes
수고하셨어요~

메서드 단위가 작은규모라 좋군요.

saveData를 옮기셔야할거 같고, 그밖에 리뷰는 남기니 수정해보세요~

2018-10-02 08:08 UTC, crongro commented on todo.js
> +const todo = {
스켈레톤 코드 잘했어요~

2018-10-02 08:08 UTC, nigayo commented on todo.js
> +    idArrays: []
task에 각각 있는 id값과 idArrays가 완전히 정확히 동기화되어야 하는 어려움이 좀 있겠네요.
잘 맞출 수만 있다면 괜찮은 방법인거 같고요.
느리지만 정확하게 하려면 idArrays를 필요할때마다 task에서 추출하는 것이죠.

2018-10-02 08:08 UTC, nigayo commented on todo.js
> +        if(saveData.idArrays.indexOf(ranNum) !== -1) {
중복방지로직은 좋아요~ 
array 에 include와 같은 메서드는 없는지도 한번 찾아보세요~

2018-10-02 08:08 UTC, nigayo commented on todo.js
> +            obj['status'] === 'todo' ? statusNum.todo++ :
이건 어때요? 

statusNum[obj.status]++

2018-10-02 08:08 UTC, nigayo commented on todo.js
> +        const newTodo = {
새로운 객체 생성 잘했어요.

2018-10-02 08:08 UTC, nigayo commented on todo.js
> +const saveData = {
객체는 
속성과 그속성을 제어하는 행위(함수)로 구성됩니다.

todo객체에서 task는 아주 중요한 속성이죠.
따라서 별로 객체에 두지않고 당연히 todo객체안에 있고, this를 통해서 객체안의 속성을 접근해야 합니다.

지금처럼 분리하는 경우는 todo와 같은 것이 한개 이상이고, 여러객체에서 saveData를 공유하는 경우에 그렇게 할수 있습니다.

2018-10-02 08:23 UTC, HTMLhead commented on todo.js
> +const saveData = {
친절하신 피드백과 답변 감사드립니다. 항상 크롱의 피드백은 여러번 읽으면 더 잘 이해되서 좋더라구요ㅎㅎ 감사합니다 바로 수정해서 다시 푸시하고 수정사항 달겠습니다.

2018-10-02 10:40 UTC, HTMLhead commented on todo.js
> +            obj['status'] === 'todo' ? statusNum.todo++ :
대단하네요.....진짜 감탄했습니다.

2018-10-02 11:21 UTC, HTMLhead commented
* 피드백 해주신대로 수정해보았습니다.

1. todo객체와 밀접한 관련이 있는 saveData객체 내의 값을 모두 todo객체 안으로 옮겼습니다. todo.idArray의 값은 todo.add를 호출하면 추가되고, todo.remove를 호출하면 제거됩니다.
1. 알려주신 방법대로 삼항연산자를 간단하게 수정하였습니다.
1. todo.update를 호출 했을 때, 무조건 'todo => {바뀐 상태}' 로 출력되던것을 '{바뀌기 전상태} => {바뀐상태}' 로 출력되도록 수정하였습니다.

언제나 피드백 감사드립니다.

2018-10-03 12:28 UTC, crongro approved these changes
고민스러운 리뷰를 계속 남기게 되네요.
다음스텝 넘어가면서 고민(?) 이어가면서 해보세요.

2018-10-03 12:28 UTC, nigayo commented on todo.js
> +        this.printStatusNum(statusNum)
바로위에서 console.log 를 호출해서 무언가 출력하고, 
그 다음줄에서는 console.log로 동작하는 함수를 호출하고, 
비슷한 것들이니 같이 print함수쪽으로 모아서 처리하도록 하는 것도 검토할 수 있을 듯.

2018-10-03 12:28 UTC, nigayo commented on todo.js
> +        const changedTask = this.task.filter(taskObj => {
map, filter의 활용법을 잘 이해한거 같네요.
그런데 이렇게 구현하다보면 가끔 중복적인 반복은 아닌가? 싶은 마음도 들긴해요.
어려운 문제에요. 앞으로 다른것도 구현하면서 적절함을 찾아나가도록 해보세요.

2018-10-03 12:28 UTC, nigayo commented on todo.js
> +    idArrays: [],
task의 아이디와 idArrays가 sync가 잘 맞는것이라는 확신!을 할 수 있을지..
소프트웨어는 보통  같은 데이터를 이렇게 동기화하진 않아요. 
두 개의 참조가 다르기때문에 어떤이유로 달라질 수 있는 셈이죠.

2018-10-03 12:28 UTC, merged