커밋 로그(할 일 관리 어플리케이션) step2
code-squad/javascript-todo pull request #43
Opened 2018-10-06 07:18 UTC by cocoa-salon

(step1 수정사항)
-showStatus() 메소드의 todo,doing,done 키를 countMap 객체에 포함하였습니다. 
-updateTodo() 메소드의 어색한 개행을 수정하였습니다. 
-간단한 if문의 경우 3항 연산자를 사용하였습니다. 

(로그)
-경과시간은 시작,종료 시간 기록 메소드와 경과시간 계산 메소드로 분리하여 구현하였습니다. 
-경과시간 출력 시연을 위해 doing 업데이트 시 임의의 시간을 설정하였습니다. 
-경과시간 출력시 0인 시간은 표시되지 않도록 하였습니다.(공백 제거 방법은 강구중입니다.)

-특정 태그 및 모든 태그별로 리스트를 나열하는 기능은 리스트 생성과 출력 메소드로 분리하였습니다.
**printListByTag()와 printListByAlltheTags()는 현재상태 표시를 제외하고 구조적으로 동일한 메소드인데요, 하나로 합치는 것이 잘 구현이 되질 않았습니다. 자신을 호출한 메소드를 식별할 수 있다면 템플릿 리터럴을 이용하여 구현이 가능할 것 같아 강구중입니다. 

-모든 할일을 출력하는 기능(showAllListByStatus)은 리스트 생성, 지연출력 설정, 리스트 출력 메소드로 분리하였습니다.
-showAllListByStatus() 메소드 호출시 상태에 해당하는 항목이 없는 경우 해당 메시지를 출력하도록 하였습니다. 

감사합니다.

2018-10-08 05:07 UTC, crongro requested changes
수고하셨네요.
review에 남겨드린 버그가 몇개 있어요~ 수정해보세요(버그픽스)

날짜부분도 어쩌다가 입력하면, 
'경과시간: NaN일 NaN 시간 NaN분'  이렇게 나오는 경우도 있어요.
확인부탁드립니다. 
(todo => done으로 갈때 NaN으로 나옴.   doing -> done으로할때 5일이라고 너무 많이 계산되는 경우도 있음)

2018-10-08 05:07 UTC, crongro commented on myTask.js
> +                val.status === "todo" ? listObj.todo.push(val)
아 이렇게 하는 건 자주 쓰는 패턴은 아닙니다.  이렇게 다들 잘 안짜서 ㅎ (수정하진 마시고요~)
그리고 왼쪽 줄을 잘 맞추면 더 보기 좋은 코드패턴이고요.

2018-10-08 05:07 UTC, crongro commented on myTask.js
> +                } else if (!!listObj[val.tag]) {
if문안에서는..이미 true/false를 판단함으로 
!! 는 필요없어요.

2018-10-08 05:07 UTC, crongro commented on myTask.js
> +        this.todoList.filter(val => !!val.tag)
filter 에서도 true/false를 판단해서..!!불필요.

2018-10-08 05:07 UTC, crongro commented on myTask.js
> +        setTimeout(() => {
계속 호출되고 있는 setTimeout 을 재귀적으로 호출하게 수정해볼래요?

2018-10-08 05:07 UTC, nigayo commented on myTask.js
>          console.log(`id: ${info.id}, "${taskName}" 삭제완료`);
실제로 없는 task경우에는 삭제가 안되는데도, 이 메시지가 나오는 거 같아요.

2018-10-08 05:07 UTC, nigayo commented on myTask.js
>      addTodo(todoInfo) {
addTodo 할때 같은 아이디를 넣어도 계속 추가될 거 같아요.

2018-10-08 17:03 UTC, cocoa-salon commented on myTask.js
>      addTodo(todoInfo) {
수정 요청 사항을 잘 이해하지 못했는데요, 미처 여쭤보질 못했습니다.ㅠㅠ 다른 요청 사항은 우선 수정하여 푸시하였습니다. addTodo() 메소드는 아이디를 인자로 받지 않고 고유한 아이디를 생성하도록 구현했는데 제가 파악하지 못한 사항에 대해서 추후 지적해주시면 감사하겠습니다!

2018-10-08 17:04 UTC, cocoa-salon commented
커밋 로그(할 일 관리 어플리케이션) step2 modified 1

-조건문에서 불필요한 !!을 제거하였습니다.
-할일 추가 메소드에서 할일을 추가한 시간(addedTime)을 객체의 속성값으로 지정하였으며 todo에서 done으로 doing없이 바로 업데이트할 경우 종료시간과 추가시간을 통해 경과시간을 계산하도록 하였습니다. 
-재귀를 사용하여 setTimeout을 구현하였습니다. 재귀시 불규칙적으로 변동되는 부분은 별도의 변수 선언과 3항 연산자를 활용하였습니다. 
-이미 삭제한 항목을 다시 삭제 시도할 경우 관련 안내 메시지를 출력하도록 하였습니다. 
-템플릿 리터럴에서 trim() 메소드를 사용하여 불필요한 공백을 제거하였습니다. 

감사합니다.

2018-10-09 06:59 UTC, nigayo commented on myTask.js
>      addTodo(todoInfo) {
아 자동생성이군요. 알겠어요.

2018-10-09 07:07 UTC, crongro approved these changes
네 코드가 점점 좋아졌네요.
이번 step에서 수정한 부분 잘 기억하시고요.
step3 으로 가보시죠. (약간 낯설 기능일수도 있지만 많이 생각해보세요~)

2018-10-09 07:07 UTC, nigayo commented on myTask.js
> +        function repeatSelf(listObj) {
좋아요. 복잡한 조건의 재귀지만, 
이렇게 구현하는게 좋긴하죠.

참고로, 
함수안에서 2000,3000... 이렇게 표현했는데  이런값들이 변경된다고 가정하고 
동작되게 한다면 더 좋은 함수가 될거에요.

2018-10-09 07:07 UTC, nigayo commented on myTask.js
>          this.taskId++;
참고.
코드에서 taskId를 task와 sync를 계속시켜줘야 하는데요.
이게 꼭 맞는다는 보장은 할 수가 없어요.진짜 task를 taskList에 있음으로..

그래서 이런식으로 원본의 일부를 계속 맞춰주는 건 아주 좋은 방법은 아닙니다.

2018-10-09 07:07 UTC, merged