Lec3 - Step3
code-squad/javascript-todo pull request #45
Opened 2018-10-06 17:53 UTC by cohily12

-. undo, redo 기능구현을 위해 호출된 method를 log하는 class를 추가하였습니다.

기능구현으로 class가 다소 생성되어 결합도가 올라간 거 같은데 문제가 되지 않을 지 궁금합니다.

확인 후 피드백 바랍니다.

2018-10-08 05:27 UTC, crongro requested changes
전체객체구조와 메서드들을 잘 구현했어요.

객체는 잘 나누었고, log만 별도로 있는 것이 어색해보입니다. 
print하는 객체와 이름만 봐서는 뭐가 다른지 애매해보이기도 하고요.

기능에 몇개 버그가 있어요. 이외에도 좀더 테스트해보시고요
- doing -> dddd (없는상태로가면) 상태가 변경되고 task가 없어짐.
- todo.show("done"); // 시간값이 안나와요.

2018-10-08 05:27 UTC, nigayo commented on index.js
> +class Log{
Log라는 이름은 SW만들때 자주 쓰는데요. 보통 프로그램 동작이과 결과를 기억하고 저장하는 용도에요. 
지금 Log는 undo/redo 전용이기때문에 undoredo 객체와 통합해서 같이 하나로 사용하는 것이 좀더 나아보여요.

2018-10-08 05:27 UTC, nigayo commented on index.js
> +const todo = new Todo(printTodo, errorCheck, log, undoOrRedo);
객체선언과 객체를 인자로 넣어주는 방식을 잘 구현했네요.
그리고 클래스는 보통 명사로만 써요~

2018-10-08 09:05 UTC, crongro requested changes
구두로 말씀드린대로, 

1) Message 에서  의존하고 있는 TodoObj객체를 Todo 객체에서 사용하게 해보세요.
2) reduce의 함수선언부를 별도 메서드로 분리해보세요.

2018-10-09 09:04 UTC, cohily12 commented
reduce 콜백 함수를 분리하는 과정에서 함수 인자가 reduce함수에 의해 결정되어 showTag, showTags, show 메소드에 따라 다른 결과를 출력 되지 않았습니다. 
그리하여 최대한 같은 메세지를 호출하는 함수를 분리하여 reduce 콜백함수를 간결하게 해보았습니다.

확인 후 피드백 부탁드립니다.

2018-10-10 06:04 UTC, crongro approved these changes
수정이 잘 됐네요~
다음단계로 가도 될 거 같습니다.

2018-10-10 06:04 UTC, crongro commented on index.js
> +class Message {
class를 사용했네요. 잘 구현했고요.

그런데 지금처럼 constructor가 없어도 된다면?  class없이 객체리터럴로 구현해도 됩니다

2018-10-10 06:04 UTC, nigayo commented on index.js
> +    this.record = {
생성자에 커다란 객체가 하나 들어왔는데요.
객체의 속성으로는 this.record = { undoList :[], redoList:[]} 만 넣어두고요.
나머지 메서드들은, execution의 메서드로 그냥 존재해도 될 거 같아요.

2018-10-10 06:04 UTC, merged