Lecture 3, Step2 - 할일관리 어플리케이션
code-squad/javascript-todo pull request #46
Opened 2018-10-06 18:37 UTC by pdvonzoo

- 객체를 나누는 것에 대하여 스스로 판단하여 코드를 작성하였습니다. 
- 데이터들의 출력 결과가 전부 상이하여 그 부분에 대한 고민이 많았습니다. 결과적으로 각 결과 값에 필요한 정보들을 공통된 함수로 얻을수 있도록 설계하고 코드를 작성했습니다. 

살펴보신 후 피드백 주시면 감사하겠습니다.

2018-10-08 07:33 UTC, crongro requested changes
네 피드백 드린 내용 수정해보세요~

2018-10-08 09:12 UTC, pdvonzoo commented
수정사항
1. 호출 메소드들을 todosList 객체에 모두 묶어두었습니다.
2. doing 단계 실행 없이 done 단계를 바로 실행할 수 없도록 수정하였습니다.
3. show method을 다시 정상적으로 작동하도록 수정하였습니다. 
4. 비동기 메소드를 따로 객체로 두지 않고 기존의 객체 안에 포함시켰습니다.

2018-10-08 09:25 UTC, crongro requested changes
리뷰드린 내용 좀더 고민해보세요! 
작은 메서드의 갯수는 좀더 많아져도 상관없습니다.

2018-10-08 09:25 UTC, crongro commented on todo.js
> +        if(asyncCheck === 'async'){
async 가 아니면 return~

2018-10-08 09:25 UTC, crongro commented on todo.js
> +                console.log(contents[index].title);
template literal 을 사용해서 출력~

2018-10-08 09:25 UTC, crongro commented on todo.js
> +    showAsyncData(contents, index = 0){
showmessage -> showAsyncData 를 연속처리할때, 
중간에 객체/배열구조(자료구조)를 안만들고 하는 방법으로 좀더 고민해봐요.

2018-10-08 09:25 UTC, crongro commented on todo.js
> +        getData.getPrintFormat(requiredData, 'status');
getPrintFormat 함수는 똑똑해서 좋네요.

2018-10-09 04:42 UTC, pdvonzoo commented
수정사항 
1.getAsyncNotice에서 비동기를 체크하는 조건문을 넣어서 메세지 출력을 두 가지로 나눴습니다.
2.기존의 배열에 객체를 푸쉬했던 복잡했던 코드를 수정했습니다. getData 객체에 비동기를 위한 새로운 메소드들을 추가하였습니다.

2018-10-10 01:57 UTC, crongro approved these changes
잘 수정하셨네요. 전체적으로 객체도 잘 나누었고요.

코드가 복잡하다가 느껴지면, 항상 수정을 고려해보세요.

프로그램 동작도 다른 분께 테스트 요청도 꼭 해보세요.

2018-10-10 01:57 UTC, nigayo commented on todo.js
> +            obj.sec =   (obj.value === 'todo') ? 2000:
상태에따라서 분기처리하는 코드를 객체로 표현해두면 어때요? 

여기코드에서도 todo/doing/done 에 따라서 2000,3000,2000 이런값이  매칭되는데요.
객체로 만들어버리는 것도 방법이겠어요.
 todo : 2000, doing :3000.. 이렇게요.

2018-10-10 01:57 UTC, nigayo commented on todo.js
> +            todo: 2000,
아 여기서 객체로 만들었군요. 잘했어요.

2018-10-10 01:57 UTC, nigayo commented on todo.js
> +        inputData.reduce((acc, curr,i) => {
이 함수를 별도 함수로 선언하면 조금더 보기 좋을 거 같아요.

```
(acc, curr,i) => {
            requiredValueObj[curr[key]] += 
            `-${curr.id}번, ${curr.name} ${(curr.status === 'done')? curr.elapsedTime+' msec':''} \n`;
            return curr;
        }
```

2018-10-10 01:57 UTC, merged

2018-10-10 02:08 UTC, pdvonzoo commented on todo.js
> +        inputData.reduce((acc, curr,i) => {
넵 함수를 기능 단위로 작게 나누는 것이 더 읽기 좋은것 같아요. 코멘트 감사합니다.