[숨] Lec3. 할일관리 애플리케이션
code-squad/javascript-todo pull request #47
Opened 2018-10-08 00:59 UTC by developersoom

Lecture3_step1 할일관리 애플리케이션 구현하였습니다. 
코드 리뷰 부탁드립니닷! 😀

2018-10-08 07:47 UTC, crongro requested changes
id는 순차적인 증가를 하는 방법도 있지만,  랜덤하게 unique id생성방법을 사용해보세요.

idlist와 statusList는 제거~

2018-10-08 07:47 UTC, nigayo commented on Lec3_ToDoList.js
> +let taskList = [];
밖의 아이들이 모두 todo 객체안으로 이동해야 todo객체에 필요한 속성이 추가됨.

2018-10-08 07:47 UTC, nigayo commented on Lec3_ToDoList.js
> +let idList = [];
idList와 taskList의 아이디가 항상 동기화가 되지 않을 수 있음.
따라서 idlist를 없애보고 구현.

2018-10-08 10:59 UTC, developersoom commented
피드백 반영하여 수정하였습니다.
리뷰 부탁드립니다아아 😀

2018-10-09 06:55 UTC, crongro approved these changes
네 이제 객체가 그럴싸해졌네요~

잘 하셨어요.

이상태에서 step2 개발하면서 기능을 추가하고, 필요하면 객체를 추가로 만들어서 연결도하고 해보세요.

2018-10-09 06:55 UTC, merged