Lec3 - Step4
code-squad/javascript-todo pull request #49
Opened 2018-10-10 09:57 UTC by cohily12

-. add 시 deadLine을 추가할 수 있게 하였습니다. 그리하여 showDeadLine method를 통해서 기한이 짧은 todo부터 볼 수 있게 하였습니다.

-. alarm 기능을 추가하였습니다. alarm에 정보(ex. '1h')를 입력하면 기한 전에 브라우저에 alert하여 사용자에게 알려주게 하였습니다.

2018-10-10 23:41 UTC, nigayo commented
신규스펙이 모두 재미있는 기능이네요~  👍

2018-10-11 01:49 UTC, crongro requested changes
잘 구현했어요!
객체의 역할정의와 관계가 괜찮아보입니다.

일단 클래스를 여러개로 나누었으니, 역할이 잘 드러나야 합니다.
지금 역할은 대체로 다 좋아요. 

로직에 대한 수정은 이제 고만하고, 
네이밍과 설명으로 코드를 마무리 지으면서 회고하는 시간을 갖고 넘어가면 좋겠어요.

1) 
클래스 상단에 '클래스의 역할에 대한 설명을 한 두 줄 써보세요' 

2) 
클래스 이름도 어울리게 지어보세요.
- Execution 클래스 이름은, 일반적인 이름이니, undo/redo역할에 어울리는 이름으로 변경해도 좋겠네요.
- TodoObj도 사실 두리뭉실한 편인데요. 이녀석이 하는 일이 데이터를 조건에 맞춰서 새롭게 만들고 있자나요? 이런 역할을 상태관리하는 측면에서 reducer라고도 해요. 지금 todoObj역할이 비슷함.  다시말해 데이터의 변경을 일으키는 역할을 하는 녀석인셈이죠.  그런 이름을 지어도 좋고요. 현재보다는 더 구체적이면 좋겠네요.

2018-10-11 01:49 UTC, crongro commented on index.js
> +    const resultStr = filteredList.reduce((accStr, task) => accStr += `${this.getMsg(task)}, [${task.status}], [${task.tag}], [${this.getDate(task.deadLine)}]\n`, '');
reduce 인자로 받는 콜백함수는 분리해서 선언하는 게 더 좋겠어요.
좀 길어서 보기 어렵기도하고요.

2018-10-11 05:54 UTC, cohily12 commented
-. 리뷰 반영하여 수정해보았습니다.
-. reduce callback 함수를 분리하는 것보다 reduce 메소드를 사용하지 않고 새로운 함수를 만드는 것이 더 좋을 거 같아 그렇게 하였습니다.

2018-10-11 06:45 UTC, crongro approved these changes
todo  하느라 수고했네요.

객체라는 게 묶음의 가치로 쓸 수 있지만, 좀더 이상적인 것은 재사용이에요. 
재사용은 사실 좀 어렵습니다. 

앞으로 객체를 만들때(클래스) 재사용이 될까? 라는 질문을 스스로 하면서 개발해보세요.

2018-10-11 06:45 UTC, merged