[숨] Lec3. 할일관리 애플리케이션
code-squad/javascript-todo pull request #50
Opened 2018-10-11 01:50 UTC by developersoom

**Lecture3_step2 할일관리 애플리케이션** 구현하였습니다. 
- master로 푸시한 거 같은데 😅 ... 조치를 취하긴 했는데 잘 됐는지 모르겠습니다..? 
- 시간으로 id 받는 부분, 지금처럼 하면 너무 길죠...? 
- 각 함수에서 공통으로 들어가는 부분을 줄이면 좋겠는데 어떻게하면 좋을 지 모르겠습니다

😃😃 리뷰 부탁드립니다앗 😃😃

2018-10-11 06:39 UTC, crongro requested changes
완성하느라 수고했네요~
고민의 흔적은 많이 볼 수 있었어요.

수정할게 좀 됩니다 ^^

2018-10-11 06:39 UTC, nigayo commented on Lec3_ToDoList.js
> +        setTimeout(function () {
바로 위의 setTimeout 의 콜백함수가 실행된 이후에 실행되도록 해야 합니다. 
지금은 위에것과 상관없이 실행 될 듯.

2018-10-11 06:39 UTC, nigayo commented on Lec3_ToDoList.js
> +        idAndStatus.nextstatus = idAndStatus.nextstatus.trim().toLowerCase();
idAndstatus 는 객체임으로, 이름을 o로 시작하거나, ht로 시작하거나, 아니면 이름끝네 object 라는 걸 넣어주어도 좋을 듯.
헝가리안표기법이 무엇인지도 좀 봐보세요~

2018-10-11 06:39 UTC, nigayo commented on Lec3_ToDoList.js
> +    findStatus(taskList) {
find 이름이 부적절~

2018-10-11 06:39 UTC, nigayo commented on Lec3_ToDoList.js
>      update(idAndStatus) {
설명드린대로, 
하위 함수 3~6개로 분리해보세요~!

2018-10-11 06:39 UTC, nigayo commented on Lec3_ToDoList.js
> +                } else if (takenTime <= 3600) {
3600은 뭐고, 86400은 뭔지 변수에 이름을 저정해두는 건 어때요?

const min = 60;

2018-10-11 06:39 UTC, nigayo commented on Lec3_ToDoList.js
> +        if (todo !== 0) {
showTag의 조건문아래 코드부분은 약간씩 다르고 중복코드같은데요.
좀 어려울수도 있지만, 함수하나로 모아서 할수도 있을까요? (고민해보세요)
(중복코드는 항상 제거하려고 해야해요)

2018-10-11 06:42 UTC, developersoom commented on Lec3_ToDoList.js
>      update(idAndStatus) {
악ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ ~~도전!!~~

2018-10-12 08:31 UTC, developersoom commented
**Lecture3_step2 할일관리 애플리케이션**  수정하였습니다. 

함수를 최대한 작게 쪼갰습니다. 리뷰 부탁드립니다아아아아아아아앗! 😜

2018-10-15 06:50 UTC, crongro requested changes
setTimeout 리뷰드린거는 꼭 해보세요.
(잘좀해라...)

2018-10-15 06:50 UTC, crongro commented on Lec3_ToDoList.js
> +        const timeUnit = {
잘 했네요.

2018-10-15 06:50 UTC, crongro commented on Lec3_ToDoList.js
> +            takenTime = (takenTime / 3600).toFixed(0) + '시간';
3600말고 여기서도 timeUnit.hour 를 사용하시면 될 듯.

2018-10-15 06:50 UTC, crongro commented on Lec3_ToDoList.js
> +            if (values.status === showStatus && showStatus !== 'done') {
조건상황에서도 중복이 느껴지면 이를 없애보려고 노력해보세요.

if(values.status !== showStatus) continue;
if(showStatus === 'done) {}
else {}

2018-10-15 06:50 UTC, crongro commented on Lec3_ToDoList.js
> +        setTimeout(function () {
이렇게 비동기 콜백에서 못벗어나는 코드가 나오게 되죠.. 비동기의 특징입니다.
잘구현하셨어요.

setTimeout 을 재귀적으로 호출하도록 한번 바꿔보세요! 
(다들 하고 있어요...)

2018-10-15 06:50 UTC, crongro commented on Lec3_ToDoList.js
> +            let takenTime = (new Date().getTime() - taskToUpdate.doingTime) / 1000;
함수로 더 분리하라! 라고 한다면, 아래 코드를 별도 함수로 분리할 수 있을 듯.

````javascript
 let takenTime = (new Date().getTime() - taskToUpdate.doingTime) / 1000;
            takenTime = this.getTakenTimeWithUnit(takenTime);
            taskToUpdate.takenTime = takenTime;
            delete taskToUpdate.doingTime;
            this.printUpdate(taskToUpdate, statusToUpdate);
```

2018-10-15 06:50 UTC, crongro commented on Lec3_ToDoList.js
> +            let takenTime = (new Date().getTime() - taskToUpdate.doingTime) / 1000;
executeUpdate 라는 함수이름으로, 분리하면 이렇게 되겠죠.

update(updateObj) {
  if (statusToUpdate === 'done') executeUpdate(a,b,c,d) 
}

2018-10-15 12:02 UTC, developersoom commented
step2 수정하였습니다. 리뷰 부탁드립니다! 😸

2018-10-16 03:25 UTC, crongro approved these changes
네 이제 다음 스텝 고고!

리뷰는 조금 남깁니다.

중복코드는 늘 없애도록 노력해주세요.

2018-10-16 03:25 UTC, crongro commented on Lec3_ToDoList.js
> +            if (!!!task.takenTime) {
!!!!!!!!

2018-10-16 03:25 UTC, crongro commented on Lec3_ToDoList.js
> +            this.executeUpdate(taskToUpdate, statusToUpdate);
바로 위에 코드와 똑같네요 ??

2018-10-16 03:25 UTC, crongro commented on Lec3_ToDoList.js
> +            if (!task.takenTime) {
부정보다는 긍정을 먼저 적으면 더 좋을 듯
if(true) {..}
else {..}

2018-10-16 03:25 UTC, merged