Step2 PR입니다!
code-squad/javascript-todo pull request #51
Opened 2018-10-11 12:33 UTC by sk2504

# 궁금한점
- 128, 143번줄을 정확히 이해를못하고 써서 봐도 잘모르겠습니다...
-  함수자체가 비슷하게 생긴것들이 있는데, 출력값이 다르기 떄문에
같은 함수를 못쓰는데, 가능한방법이 있을까요?

2018-10-12 02:00 UTC, nigayo commented
충돌이 난 것을 먼저 해결해볼래요? 
@sk2504

2018-10-12 02:00 UTC, nigayo commented
128, 143 라인으로 표시하지 말고, 어떤 내용이 잘 모르는지 설명도 주석으로 해주실래요?

2018-10-12 02:02 UTC, crongro requested changes
리뷰참고하시고요,
설명대로 PR다시 보내주세요~
충돌...

2018-10-12 02:02 UTC, nigayo commented on index.js
> +        setTimeout(() => {
이부분 재귀호출로 수정해보세요!

2018-10-12 02:02 UTC, nigayo commented on index.js
> +        const uniqueTagNameArray = [...new Set(tagNameArray)];
set이라는 자료구조는 배열과 유사한 자료구조이고요. 중복내용이 들어가지 못합니다.
... 하면 다른 type으로 변경되는데요, 무엇으로 바뀌는지 테스트해보세요.

2018-10-12 09:35 UTC, crongro requested changes
약간 더 리뷰 추가했으니 참고해서 수정해보세요~

2018-10-12 09:35 UTC, nigayo commented on index.js
> +        setTimeout(() => {
재귀적으로 구현하면 중첩된 setTimeout 호출코드패턴이 사라질거에요. 
하지만 2000, 3000 등 처리하기 애매한 값들이 재귀호출할때 좀 고민스러울겁니다.

2018-10-12 09:35 UTC, nigayo commented on index.js
> +            x[y] = ++x[y] || 1;
여기 문법을 이해못하는건가요?

2018-10-12 09:35 UTC, nigayo commented on index.js
> +        if (array.length === 0) return console.log('항목이 없습니다.')
return console.log 는 undefined 가 리턴되는거라 불필요..

2018-10-12 09:35 UTC, nigayo commented on index.js
> +        for (let i = 0; i < uniqueTagNameArray.length; i++) {
특별한거아니면 forEach를 쓰면 더 좋죠.

2018-10-12 09:50 UTC, nigayo commented
아 그리고 
출력값이 다르다... 어쩔 수 없죠.

가능하면 console.log에 담아야 하는 그 지저분한 것들을 어떻게 분리하지? 라는 고민은 해볼만합니다.

2018-10-15 09:07 UTC, sk2504 commented
- 피드백주신사항 수정했습니다! 확인부탁드립니다

2018-10-17 05:30 UTC, crongro approved these changes
리뷰가 늦어버렸군요! 이런..
잘 수정하셨네요. 다음단계로 가보시죠.

2018-10-17 05:30 UTC, crongro commented on index.js
> +                (n >= 2) ? false :
false...

2018-10-17 05:30 UTC, crongro commented on index.js
> +    setTimeArray: [2000, 5000, 7000],
이렇게 속성으로 두는 건 괜찮음.

2018-10-17 05:30 UTC, crongro commented on index.js
> +            [todo, doning, done] = [filteredArray[0], filteredArray[1], filteredArray[2]];
[todo, doning, done] = filteredArray;

2018-10-17 05:30 UTC, crongro commented on index.js
> +        const numberOfTags = tagNameArray.reduce((x, y) => {
참고로 
mapReduce 살펴보기!

2018-10-17 05:30 UTC, nigayo commented on index.js
> +        if (array.length === 0) console.log('항목이 없습니다.')
array 라는건 Array와 헷갈려서 잘 안쓰는 네이밍이에요.  **object도** 그런점에서 마찬가지고요.

2018-10-17 05:30 UTC, nigayo commented on index.js
>      loopConsoleLog(array) {
이름을 자주 ConsoleLog라고 했는데요, 특정메서드로 이름짓기보다는
print라고 하는게 좀더 일반적일 거 같네요. 아니면 log! 정도로.

2018-10-17 05:30 UTC, merged