Lecture 3, Step3 - 할일관리 어플리케이션
code-squad/javascript-todo pull request #52
Opened 2018-10-11 12:53 UTC by pdvonzoo

- 객체를 나눠서 추가하였는데요. 이 부분에 대해서 어색한 부분이 있는지 판단하기 어려운 부분이 있습니다.
- 기능들이 추가되어서 어떤 상황에서 버그, 에러가 나올수 있는지에 대하여 고민이 많았습니다. 혼자 생각하기엔 한계가 있는것 같아서 주변 분들께 도움받고 테스트들을 진행하였는데요. 여러 상황들을 대비하기위한 테스트를 어떤식으로 만들어야 될지 궁금합니다. 

살펴보신 후 피드백 부탁드리겠습니다.
감사합니다.

2018-10-12 02:05 UTC, nigayo commented
객체를 나눠서 처리흐름이 헷갈리지 않는 상태라면, 우선 괜찮은 구조죠.

2018-10-15 05:38 UTC, crongro reviewed
객체는 처음에 하나로 시작, 객체내에 메서드마다 비슷한 일을 하고 있다면, 그것들을 모아서 분리해보기.

2018-10-15 05:52 UTC, crongro requested changes
todoslist와 errorcheck가 서로 불리는 건 좋지 않음.

리뷰참고해서 수정해보세요.

2018-10-15 05:52 UTC, nigayo commented on todo.js
> +    getLogObject([active, id, name, tag, prevStatus, nextStatus], undo){
배열말고 객체를 사용해서 파라미터를 받으면 좋을 듯.

2018-10-15 05:52 UTC, nigayo commented on todo.js
> +        if(typeof(Object.values(arguments)[0]) === 'string'){
typeof arguments[0]

2018-10-15 05:52 UTC, nigayo commented on todo.js
> +                  .forEach((v)=>{
아래 부분을 함수로 추가로 만들어서 선언하고, 여기서 그 함수이름을 추가하기.
(v)=>{
                    if(nextStatus === 'doing'){ v.startTime = stopWatch.start(); }
                    if(nextStatus === 'done' && v.startTime){ v.elapsedTime = stopWatch.stop(v.startTime); }
                    v.status = nextStatus;      
                  }

2018-10-15 05:52 UTC, nigayo commented on todo.js
> +        if(!!error){ console.log(error); return; }
if문에서는 !! 불필요.

2018-10-15 05:52 UTC, nigayo commented on todo.js
> +        if(typeof(Object.values(arg)[0]) === 'string'){
302라인 arg사용이 이상함.

2018-10-15 05:52 UTC, nigayo commented on todo.js
> +    todosCounter : 0,
counter  = {
 todos :0, undo:0
}

?

2018-10-15 07:58 UTC, pdvonzoo commented
- 상호 호출하는 객체들을 수정하여 한 방향으로만 작업을 위임하도록 코드를 작성하였습니다.
- 중복되는 코드를 최소화 하도록 노력하였습니다.
- 코멘드 달아주신 내용들을 수정하였습니다.

살펴보신 후 피드백 부탁드리겠습니다.
감사합니다.

2018-10-16 01:59 UTC, crongro approved these changes
네 좋아요.
남겨드린 리뷰만 수정같이 하시고요. 다음단계 바로 진행해보세요.

객체간의 관계에 기능을 개선/수정하면서 계속 고민해보시고요.

2018-10-16 01:59 UTC, nigayo commented on todo.js
> +        (undo === 'undo')?
삼항연산자 부분의 함수호출이  중복인거 같아요.
함수호출은 한 줄로 표현가능하고, 삼항연산자를 없앨 수 있을거 같아요.
makeLogObject의 마지막 인자는 늘 넘겨주고, 정상값이거나, 아니면 null등을 넘겨주는 방법으로..

2018-10-16 01:59 UTC, merged

2018-10-16 03:24 UTC, pdvonzoo commented on todo.js
> +        (undo === 'undo')?
아 다시보니 굳이 필요없는 코드를 작성하였네요.. 수정하도록 하겠습니다. 
객체 관계에 조금 더 고민해서 코드를 작성하도록 할게요.
피드백 감사합니다.