할일 관리 애플리케이션 step3
code-squad/javascript-todo pull request #54
Opened 2018-10-12 07:51 UTC by cocoa-salon

-undo, redo 기능 구현을 위해 활동 내역(추가,업데이트,삭제)을 저장하는 스택을 만들고 내역을 전달, 관리하는 메소드를 별도로 정의하였습니다. 
-각각의 스택은 활동 내역을 3개까지만 저장하도록 하였으며 내역 추가 시 마지막 건이 삭제되도록 구현하였습니다. 
-undo, redo 횟수가 3회 초과시 메시지를 출력하도록 구현하였습니다. 

-에러를 검출하는 메소드를 유형별로 분리하였으며 할일 추가,업데이트,삭제 시 자동으로 오류를 검사하도록 하였습니다.

감사합니다.

2018-10-12 09:27 UTC, crongro requested changes
잘 구현했네요.

큰 관점에서  리팩토링을 조금은 하고 가는게 좋겠어요.

먼저, forEach안에 커다란 로직들이 몇군데 있는데요. 
별도 함수로 선언하고,  그 함수를 forEach에서 불러보세요.

function func2(){}
filter(func1).forEach(fun2);
이렇게요.
undo/redo 관련 부분에서 개선이 당장 필요해 보이네요.

console.log로  print하는 부분(print하기까지 데이터 가공하는 부분을 포함해서) 을 별도 객체로 분리해보는 건 어때요? 
그것도 고민해보세요.

2018-10-15 03:28 UTC, crongro requested changes
리뷰를 잘 반영하셨고요.
객체들의 역할도 대체로 좋고, 객체 나누는 규모도, 적절하게 잘 나누셨어요. 👍 

객체 관계에 대해서는 고민이 필요한 부분이 보입니다.
객체간의 호출관계(협력관계)에 대해서는 printList 객체를 따로 불어야하고, undo/redo객체를 따로 불러야 하는데요.
그것보다 todo.print(), todo.undo() 이런식으로 하나의 접점을 통해서만 동작되게 하는 것도 좋아요.

또한 상호호출은 없는지도 살펴보셔야해요.
A,B 두 객체가 있을때, A가 B를 부르고(속성이나, 메서드 접근) 또 반대로 B가 A를 부른다면, 상호호출이라서 복잡도가 올라가는 객체관계가 됩니다. 이것은 안티패턴이에요.

이부분을 참고해서 현재 수정할 수 있는 부분을 고민해보세요.

2018-10-15 03:28 UTC, nigayo commented on myTask.js
> +        if (this.todoList.every(val =>
every 결과를 변수로 받고, if문에은 짧게 표현하면 좋겠어요.~

const result = [].every();
if(result) {}

checkError 에 모든 코드가 다 그렇게 되어 있어서, 수정이 필요합니다요.
디버깅이 어려운 코드라서..

2018-10-15 03:28 UTC, nigayo commented on myTask.js
> +        if (checkError.checkInvalidUpdate.call(this, this.info)) return;
사실
call 메서드를 즐겨(?)쓰는 건 그리 좋진 않아요. 객체에서 가리키는 this가 예상과 달라져서요.

2018-10-15 03:28 UTC, nigayo commented on myTask.js
> +                (val.status === "done" && target.nextStatus === "doing") ||
filter 함수를 두 번 쓰는 것도 방법이겠네요.
status가 done인거 거르고, 
nextstatus가 todo나 doing인것 거르고

2018-10-15 03:28 UTC, nigayo commented on myTask.js
> +        if (this.undoStack.length < 3) {
이런 숫자 3도 인자로 받을 수도 있죠.
이런식으로 의미없는 숫자나 문자열 하드코딩은 안좋아요.

2018-10-15 08:31 UTC, cocoa-salon commented
할일 관리 애플리케이션 step3 modified 2

-할일 관리의 주요 핵심 기능을 모두 todo 객체 안으로 포함하여 메소드 호출의 편의성을 높였습니다.(undo, redo 및 각종 결과 출력)

-이에 기존의 manageUndoRedo 객체를 변경된 특성에 따라 manageStack으로 변경하였습니다.

-의미 없는 숫자 사용을 지양하고 의도가 드러나는 변수를 선언하여 초기화하였습니다.(스택의 길이를 제한하는 stackLimit)

감사합니다.

2018-10-16 02:04 UTC, crongro approved these changes
잘 수정했네요~ 
리뷰남겨드린 부분 참고해서, 다음단계 풀이로 가보세요.

객체의 개선과 undo/redo개선은 아이디어를 계속 고민해봐도 좋을 거 같네요.

2018-10-16 02:04 UTC, nigayo commented on myTask.js
> +        if (val.taskId === this.searchId && this.statusLog === "updated") {
요부분이 중복조건이네요.
if (val.taskId === this.searchId )

그러면 먼저 이렇게 하는건 어때요?

if (val.taskId !== this.searchId) return;

2018-10-16 02:04 UTC, nigayo commented on myTask.js
> +        if (val.taskId === this.searchId && this.statusLog === "removed") {
여기의 조건문도 위에 리뷰드린 것과 같은 중복상황..

2018-10-16 02:04 UTC, nigayo commented on myTask.js
>      generateSetTimeout(listObj) {
이 함수 아래에서 이런 코드가 있는데요
```
  repeatCount === 0 ? milliSec = 3000 : repeatCount === 1 ? milliSec = 2000 : "";
                repeatCount === 0 ? status = "doing" : repeatCount === 1 ? status = "done" : "";
```

이런걸 없애려면 배열로 관계를 지정해놔도 좋겠어요.
times = [2000, 5000, 3000];

2018-10-16 02:04 UTC, nigayo commented on myTask.js
> +                                (val.status === "done" && target.nextStatus === "doing") ||
filter를 한번 더 쓰는 건 어때요? done만 또 먼저 체크하는 것으로,

filter((val)=>val.status==="done").filter()

2018-10-16 02:04 UTC, merged