lec3-step3.사용성향상
code-squad/javascript-todo pull request #55
Opened 2018-10-17 07:51 UTC by HTMLhead

* 피드백에 의한 수정
   1. 모든 객체내의 메서드들을 모두 간단하게 표현하였습니다.
   1. statusNum을 this.statusNum으로 사용 할 수 있게 변경하였습니다.
   1. showAll메서드를 재귀적으로 바꾸었습니다.
   1. todoData를 완전히 껍질 역할만을 하도록 바꾸었습니다. 이제 todoData내에는 콘솔 창으로 직접 메서드를 실행 할 때마다 바뀌는 데이터 들만 모아져 있습니다.
   1. addFunc같은 함수로 표현되는듯한 객체의 이름을 addUtility로 수정하였습니다.
* step3구현 맥락.
   1. todoData.~ 라고 직접 console창에 찍는 메서드별로 객체로 나누었습니다.
   1. 에러를 체크해주는 메서드들도 다른 객체로 나누었습니다.
   1. 메서드내에서 사용하는 비슷한 메서드를 commonUtility객체로 한데 모았습니다.
   1. undo와 redo는 add, remove, update가 입력 될 때마다 각자 하는 일들의 데이터를 저장하여 undo가 실행되면 저장된 데이터를 불러와 다시 원상태로 되돌리도록 구현하였습니다.
   1. redo는 undo가 입력 될 때마다 입력되는 데이터를 저장하여 다시 되돌리도록 구현하였습니다.
   1. redo를 하고 다시 undo를 했을때에도 문제없이 실행될 수 있도록 구현하였습니다.
* 노력한점
   1. 어떻게 하면 적절하게 객체로 나눌 수 있을까 생각을 많이 한 것 같습니다.
   1. 객체들이 서로 상호작용을 하는것이 아니라 한 방향으로 사용 할 수 있도록 많이 노력했습니다.
   1. undo와 redo를 구현하기 위해서 많이 노력했습니다.

얼마만의 pr인지..ㅜㅜ 피드백 부탁드립니다 !

2018-10-18 03:17 UTC, crongro requested changes
오늘 강의때 설명드린 부분으로 개조(?)해보세요!

나머지 리뷰 좀더 남깁니다.

2018-10-18 03:17 UTC, nigayo commented on todo.js
> +    lastDoArrays: [],//이전에 했던 상태 3개 저장
lastDoDataArrays 와 이곳의 lastDoArrays 라는 게 약간 헷갈리게 이름이 되어 있네요.

그리고 배열은 이미 list형태기때문에, Arrays 라고 복수로 표현안해도 될 듯. Array이름도 이왕이면 lists 나 todos 라고 하는 게 좀더 낫고요.

2018-10-18 03:17 UTC, nigayo commented on todo.js
> +        if (!errorCheck.remove(objToRemove, this.task)) return;
빨리 리턴시키는 코드는 좋아요.

2018-10-18 03:17 UTC, nigayo commented on todo.js
> +    },//태그에 따라 모든 값을 출력해주는 기능
주석이 좀 많은 편이네요. 
조금 줄이고 코드에서 의도를 드러내려고 하시면 더 좋겠어요.

2018-10-18 03:17 UTC, nigayo commented on todo.js
> +        todoTask.push(lastDo.removedData)
이건 좀 다른 이야기인데요.
push와 같은 메서드를 통해서 상태를 수정할 것인가,  아니면 concat이나 spread operator 를 사용해서 새로운 데이터를 만들것이냐? 하는 고민이 있을수 있어요.
둘 다 쓸 수 있는 당연한 방법이고요. 요즘은 concat과 같은 메서드로 새로운 데이터를 만드는 것 선호합니다. 즉 이전 상태를 직접 변경하지 않는 것이죠.

2018-10-18 03:17 UTC, nigayo commented on todo.js
> +            if (tag === taggedTaskObj.tag) {
잊지말고 filter 메서드를 쓸 수 있는 곳은 사용해보세요.
some/every/map/reduce도요.

2018-10-18 03:17 UTC, nigayo commented on todo.js
> +        }.bind(showUtility), 2000)
bind를 잘 썼네요~ bind는 참고로 인자도 전달해줄 수 있어요~

2018-10-18 03:21 UTC, HTMLhead commented on todo.js
> +        todoTask.push(lastDo.removedData)
concat을 분명히 알고있음에도 불구하고 미처 생각해내지를 못했네요. 한번 concat으로 구현해 보도록 하겠습니다.

2018-10-19 01:39 UTC, crongro approved these changes
아주 잘 구현했어요.
그리고 클래스는 보통 명사 그리고 대문자로 시작하는 단어를 사용합니다~

2018-10-19 01:39 UTC, nigayo commented on todo.js
> +    checkUpdateStatus(objToUpdate, todoList) {
이렇게 비슷한 (update)함수끼리 모아두는 것도 좋은 방법이에요. 잘했어요.

2018-10-19 01:39 UTC, nigayo commented on todo.js
> +        history.undo(this.todoList, history.dataList.pop())
history.dataList.pop() 
이값은 여기서 하지않고, history의 undo함수 내부에서 해도 되지 않을까요?

2018-10-19 01:39 UTC, nigayo commented on todo.js
> +        history.redo(this.todoList, history.undoList.pop())
history 객체쓰는 거 잘 했어요~

2018-10-19 01:39 UTC, nigayo commented on todo.js
> +        while (array.length > 3) {
이런 숫자3 같은 값을 하드코딩하는 건 늘 안좋아요.

2018-10-19 01:39 UTC, merged

2018-10-19 01:39 UTC, HTMLhead commented
* 피드백에 의한 수정
   1. 변수들의 이름과 배열들의 이름을 좀 더 적합하게 변경하였습니다.
   1. 메서드를 forEach대신 filter와 map을 더 사용하도록 노력해보았습니다.
   1. 주석을 간단하게(그 메서드가 어디에 이용되는 것인지만 표출함.) 수정했습니다.
* 코드맥락
   1. 강의에서 말씀해 주신 대로 객체를 나누어보았습니다. todo객체는 todo객체내의 todoList를 직접적으로 변경하는 것과 콘솔창에 직접 사용하는 메서드들을, history객체는 undo와 redo를 위한 데이터와 메서드들을, show객체는 console창에 직접 찍어주는 것들을 모아두었습니다. checkError객체는 에러를 확인하는 메서드들을 모아두었습니다.

2018-10-19 04:51 UTC, HTMLhead commented on todo.js
> +        history.undo(this.todoList, history.dataList.pop())
그게 더 깔끔한 것 같네요. redo부분도 그렇게 바꿔야겠어요...

2018-10-19 04:51 UTC, HTMLhead commented on todo.js
> +        while (array.length > 3) {
네 항상 숙지 하겠습니다.

2018-10-21 08:46 UTC, nigayo commented
@HTMLhead  네 수정한 코드는 제가 이미 확인한것 같은데요?
아직 확인 안한 부분은 STEP4에서 같이 확인할게요~ (잘 수정하고 있으리라 믿어요 ㅎ)
step4에 포함해서 PR보내주세요