할일 관리 애플리케이션 step4
code-squad/javascript-todo pull request #56
Opened 2018-10-18 10:23 UTC by cocoa-salon

-기존의 객체 리터럴 방식의 객체 구현을 클래스 개념을 사용하여 다시 구현하였습니다.

새로운 기능 : 휴지통 복구
-삭제된 항목(휴지통)에 대해 undo, redo 제약 없이 접근 및 복구가 가능하도록 하였습니다.
-복구 메소드 호출시 복구 가능 목록을 출력하도록 하였습니다.
-복구하고자 하는 아이디를 프롬프트 창을 통해 입력하도록 하였습니다. 
-부정확한 아이디 입력 또는 복구 가능 항목이 없을 시 오류 메시지를 출력하도록 하였습니다.

추가 보완 사항 :
-상태별 결과 리스트 출력 시 해당 상태가 없으면 오류 메시지 출력.
-태그 별 결과 리스트 출력 시 없는 태그를 입력하면 오류 메시지 출력.
-업데이트 시 todo, doing, done  외에 다른 상태를 입력하면 오류 메시지 출력.

감사합니다.

2018-10-19 01:20 UTC, crongro requested changes
잘 했어요! 새로운 기능도 좋고요.

리뷰드린 것 참고해서 조금더 수정해보면 좋겠네요.

2018-10-19 01:20 UTC, crongro commented on myTask.js
> +const todo = new GenerateTodoObj([],0,[])
클래스는 명사로 역할에 맞게 이름을 지어보세요.

2018-10-19 01:20 UTC, crongro commented on myTask.js
> +const todo = new GenerateTodoObj([],0,[])
[],0,[]  
이처럼 무엇인지 알기 어려운 경우에는 객체형태로 전달해보세요.

2018-10-19 01:20 UTC, crongro commented on myTask.js
> +const checkError = new GenerateCheckErrorObj();
각 클래스코드 안에서 다른 객체를 직접 불러서 쓰고 있는데요.  객체를 주입받아서 하면 더 좋아요.

예를들어서 printList를 manageStack에서 사용한다면,
이렇게 객체를 인자로 전달해주는 거죠.

const printList = new GeneratePrintListObj(); 
const manageStack = new GenerateManageStackObj([],[], const printList);

2018-10-19 01:20 UTC, crongro commented on myTask.js
>              printMsgUndoRedo.printUndoMsgUpdated( // 메시지 출력
함수의 인자를 표현할때는 좀더 간결하게 넣어주면 좋겠어요.

아래처럼  id, name, status, prevStatus 와 같이 전달할 값을 변수에 담아두고 호출하는 게 더 좋겠어요.

printMsgUndoRedo.printUndoMsgUpdated(id, name, status prevStatus)

2018-10-19 01:20 UTC, crongro commented on myTask.js
> +    constructor() { }
불필요하면 생략가능해요.

2018-10-19 13:09 UTC, cocoa-salon commented
할일 관리 애플리케이션 step4 modified 1

보완 사항
-결과 출력 메소드 호출 시 길이가 지나치게 긴 인자는 별도의 변수를 선언하여 간소화하였습니다. 
-클래스명을 목적과 역할에 맞는 명사형으로 변경하였습니다. 
-TodoMainFunction 클래스로 생성한 객체 내에서만 다른 클래스 객체의 메소드를 사용하도록 생성자 함수에 파라미터를 추가하였습니다. 

기능 수정 사항
-redo 기능은 undo를 실행할 때만 허용하기 위해 undo 외에 다른 작업 발생시(추가,업데이트,삭제,복구) redo 스택이 초기화되도록 하였습니다. 
-redo 스택에서 undo 스택으로 재이동시 undo 스택의 숫자를 제한하지 못한 점을 수정하였습니다. 

감사합니다.

2018-10-22 01:38 UTC, crongro commented
곧 리뷰할게요.

2018-10-22 02:08 UTC, crongro requested changes
오프라인 리뷰 남긴대로 수정해보세요~

2018-10-22 02:08 UTC, crongro commented on myTask.js
> +const TodoMainFunction = class {
Class인데 MainFunction이라고 한 것이 이상해요.
그리고 이름에 class, function 이런건 안넣는게 좋아요.

2018-10-22 02:08 UTC, crongro commented on myTask.js
> +    printList: new ResultListView(),
객체 5개를 전달하는데요. 비슷한 녀석끼리 그룹을 짓는 것도 가능하겠네요.

new TodoMainFunction( {
  todoList:[],
  taskId:0,
 obj : {
    printList :new ResultListView(),
    checkError : new ErrorCheck(),
    ..
  }
});

TodoMainFunction 안에서 this.obj.manageStack 이런식으로 쓰게 될것이라, 좀더 객체라는 표현이 잘 될 거 같아요.

2018-10-22 02:09 UTC, crongro requested changes
오프라인 리뷰 남긴대로 수정해보세요~

2018-10-22 09:39 UTC, cocoa-salon commented
할일 관리 애플리케이션 step4 modified 2

-undo, redo 메소드 내부의  중첩된 if문을 별도의 메소드로 분리하였습니다. 
-결과 내역을 출력하는 클래스를 네임스페이스를 이용하여 하나의 객체로 통합하고 todoMainCommand 객체의 인자로 주입하였습니다. 
-객체의 이름을 명사로 변경하였습니다. 

감사합니다.

2018-10-23 02:27 UTC, crongro requested changes
몇 개 좀더 수정해보세요.
외부객체의 속성을 직접 접근하는 부분을 꼭 수정해주세요~

2018-10-23 02:27 UTC, crongro commented on myTask.js
> +        this.mainSupport = mainSupport;
좀 낯선느낌입니다. mainSupport 라는 이름..ㅎ
그리고 자주 불리는 객체임으로, 좀 줄여주는 건 어때요? \

아니면 this.mainSupport으로 받긴하지만, 해체해서 사용하는 것도 좋고요.
ex)  아래처럼요.
this.oStateManagement = this.mainSupport.stateManagement;

2018-10-23 02:27 UTC, crongro commented on myTask.js
> +        if (this.statusLog === "removed") {
여기서도 아래코드처럼해서 indent를 없애보세요.
 if (val.taskId !== this.idToSearch) return;

2018-10-23 02:27 UTC, crongro commented on myTask.js
> +            this.redoInCaseAdded();
네 하위함수로 분리 잘 했어요. 
참고로 더 많은 부분을 분리해도 됩니다.

2018-10-23 02:27 UTC, crongro commented on myTask.js
> +            this.mainSupport.stackManagement.redoStack.unshift(this.mainSupport.stackManagement.undoStack.splice(this.endIndex, 1)[0]); // redo 스택으로 이동
stackManagement 와 같은 외부 객체에 접근할때는 '메서드'를 통해서 접근해서 변경하는 게 일반적이에요.
메서드가 객체간의 협력을 위한 일종의 창구역할을 하는 것이라고 생각하면 됩니다. 
지금은 undoStack 속성을 접근해서 splice등을 하고 있으니 문제입니다.

2018-10-23 02:27 UTC, crongro commented on myTask.js
>          if (this.statusLog === "added") {
이와 유사한 부분들 모두 not 조건으로 판단해서 return 시켜버리세요

2018-10-23 09:14 UTC, crongro approved these changes
변수로 캐시해두고 쓰는 거에 대한 설명을 남겼어요.
이해가 안가시면 다시 저에게 메시지 주세요~ 

수고하셨습니다.

2018-10-23 09:14 UTC, nigayo commented on myTask.js
> +        if (this.todoControl.errorCheck.checkInvalidUpdate.call(this, this.info)) return;
이미 리뷰드렸지만, 
this.errChk = this.todoControl.errorCheck; 
이렇게 저장해두고 짧게 구현해도 될 듯 해요.

2018-10-23 09:14 UTC, nigayo commented on myTask.js
> +        this.todoControl.stackManagement.redoStack = [];
위에랑 같은 설명인데요, 
만약 자꾸 반복적으로 긴 코드가 보인다면 변수로 저장해둘 수 있어요.
this.todoControl.stackManagement
이 부분을 이렇게, 

const stackManager = this.todoControl.stackManagement;
stackManager.moveUndoStack();

2018-10-23 09:14 UTC, nigayo commented on myTask.js
> +        this.todoControl.stackManagement.redoStack = [];
this.todoControl.stackManagement.redoStack = [];

이부분도 외부객체의 속성을 초기화 시키는 건데요,  이렇게 메서드를 활용하는 게 더 좋아요.
 this.todoControl.stackManagement.redoStack.reset();

2018-10-23 09:15 UTC, merged