Lecture 3, Step4 - 할일관리 어플리케이션
code-squad/javascript-todo pull request #57
Opened 2018-10-20 13:55 UTC by pdvonzoo

1. 수정사항
- 객체 나누는 것에 대하여 고민 한 후 리펙토링 했습니다.
- 이전의 코드에서 기존의 조건문 대신 삼항연산자를 이용하여 조건을 설정했습니다. 하지만 삼항 연산자는 예외상황이 명확한 경우, 조건에 의한 코드의 진행이 간결할 때만 사용하는게 더 좋을것으로 판단하였고 코드를 다시 리펙토링하였습니다.
- 기존에 비동기 코드를 콜백으로 처리했습니다. 하지만 비동기 상황에 제한 조건이 많을때 코드가 복잡해짐을 느꼈습니다. 비동기 상황의 코드를 promise, generater, async/await를 이용하여 리펙토링 하였고 새롭게 추가된 기능들도 async/await를 이용하여 작성하였습니다. 

2. 추가 기능
- 작업을 시작(todo -> doing)을 위한 알람 기능을 추가하였습니다. add시 setTime으로 시간 인자를 받습니다.
- 작업의 마감시간을 정해놓고 작업시간이 지났을때 해당 작업을 제거하도록 설정하였습니다. add, update시 deadline으로 시간 인자를 받습니다.

살펴보신 후 피드백 부탁드리겠습니다.
감사합니다.

2018-10-21 09:08 UTC, crongro requested changes
객체로 나눈 단위가 매우 적절해보여요.
역할도 명확하고 아주 잘 나눴어요.

훌륭한 비동기 코드에 대해서 몇가지 질문을 남겼으니, 설명만 부탁드려요!

2018-10-21 09:08 UTC, crongro commented on todo.js
> +class Delay {
Delay 가 클래스 수준으로 동작하는게 좀 어색해보여요.
함수수준정도가 아닐까요?

2018-10-21 09:08 UTC, crongro commented on todo.js
> +        (async () => {
async 를 안쓸때보다 어떤 장점이 있는지 한번 댓글로 설명해주세요.

2018-10-21 09:08 UTC, nigayo commented on todo.js
> +          for await (let x of range()) {
와 for await of 를 쓰다니 ㅎ
잘 했는데요.

브라우저 지원범위는 어떻게 되는지 한번 알아보세요.

2018-10-21 09:08 UTC, nigayo commented on todo.js
> +          for (let value of noticeArr) yield Promise.resolve(value);
yield 의 동작을 한번 설명해볼래요?

2018-10-21 09:08 UTC, nigayo commented on todo.js
> +          for await (let x of range()) {
range 함수를 반복하려고 for - of 문법을 썼는데요. for - of와  generator의 관계도 한번 설명해보세요!

2018-10-23 14:22 UTC, pdvonzoo commented on todo.js
> +class Delay {
처음에 delay 객체를 만들었을땐 다양한 객체에서 util의 개념으로 생각했었습니다.
하지만 결과적으로 show의 역할에서만 필요한 개념이라고 생각이 되어 TodoMassage 객체 안의 메소드로 수정하였습니다.

2018-10-23 14:22 UTC, pdvonzoo commented on todo.js
> +        (async () => {
첫번째, 가독성입니다. async 코드를 처음 봤을때 동기 코드와 비슷하게 보여서 디버깅하기에 용이하다고 생각됐습니다.
두번째, 비동기 코드를 await로 blocking하는 점이 좋았습니다. await를 쓰지 않는 코드들은 동기적으로 실행이 되는데요. 비동기 코드가 실행되기 전에 다른 동기 코드가 실행되지 않는 점이 순차적으로 데이터를 처리하기에 좋았습니다..

2018-10-23 14:23 UTC, pdvonzoo commented on todo.js
> +          for await (let x of range()) {
async의 지원 범위는 https://caniuse.com/#feat=async-functions 에서 확인할 수 있었는데요.
for await of는 또 다른 지원 범위를 가지고 있는지 궁금합니다.

2018-10-23 14:26 UTC, pdvonzoo commented on todo.js
> +          for (let value of noticeArr) yield Promise.resolve(value);
caller에서 이터레이터를 호출할 때마다 yield는 순차적으로 Promise를 반환합니다.
또 다시 호출이 될 때 이전에 for루프의 이전에 멈추었던 곳에서 다시 값을 반환합니다.
이후 이터레이터의 for 루프 안의 모든 값들이 반환되면 yield는 실행되지 않고 제너레이터 함수는 종료됩니다.

2018-10-23 14:37 UTC, pdvonzoo commented on todo.js
> +          for await (let x of range()) {
제너레이터 함수는 이터레이터를 생성하기 위해 만들었습니다.
또한 async 코드에서 for await of는 이터레이터에서 만들어진 promise의 fulfill된 값을 순차적으로 반환합니다.
for await of의 루프가 한 번 돌 때마다 제너레이터 함수가 실행되는데요. 
제너레이터에서도 yield를 통해서 순차적으로 한 번씩 값을 반환하여 두 함수가 순환하며 실행됩니다.

2018-10-24 06:10 UTC, nigayo commented on todo.js
> +          for await (let x of range()) {
네 별도 스펙이라 지원범위가 다른 걸로 알고 있어요. async iteration 일겁니다.

2018-10-24 06:37 UTC, crongro requested changes
async  부분을 학습하다니 좋아요~
동료들에게 특강이라도 해주셔야 하는거 아닙니까? ㅎ

async 쓴 김에 좀 간단하게 만들어보면 더 좋겠습니다.
조금더 손을 대보세요~

2018-10-24 06:37 UTC, nigayo commented on todo.js
> +    playAlarm({id, setTime, deadline}){
playAlarm이 async 함수일수는 없나요?

2018-10-24 06:37 UTC, nigayo commented on todo.js
> +          for (let value of noticeArr) yield Promise.resolve(value);
for of 가 원래 이터레이터 프로토콜을 따르는 자료구조를 반복적으로 처리할 수 있게 해주죠.

2018-10-24 06:37 UTC, nigayo commented on todo.js
> +          for await (let x of range()) {
좋아요. generator 와 async까지 많이  학습한거 같네요. 
그런데 간단히 짤수도 있을 거 같아요.
예를들어 이런식으로요.

generator도 없을 수 있고, 즉시실행되는 async도 없앨 수 있을 듯..
좀더 간단한 방법은 없는지 생각해보세요~

```javascript
async function showAsyncMessage() {
   for (let task of [{name:"jisu"}, {name:"crong"}]) {
      await delay(1000);
      console.log(task.name);
   }
}
```

2018-10-25 01:44 UTC, pdvonzoo commented on todo.js
> +    playAlarm({id, setTime, deadline}){
1. 비동기 함수를 작성할 때 외부 함수를 굳이 감쌀 필요가 없었던 것 같습니다. 객체의 최상단 메소드를 그 자체로 async로 비동기 선언하여 리펙토링 하였습니다.
2. 또한 학습 차원에서 제너레이터를 이용하여 이터레이터를 생성하는 함수를 만들었고 for await of를 이용해서 그 값들을 출력하도록 설계하였는데요.
그 코드에 대해서 for of를 사용하여 입력으로 들어오는 일반적인 이터레이터 프로토콜을 따르는 자료구조를 비동기적으로 출력하도록 리펙토링 하였습니다.

2018-10-25 01:49 UTC, pdvonzoo commented
익숙하지 않았던 promise, generator, aync/await를 이용하여 비동기 함수를 만들려고 하다보니까 학습시간이 생각보다 오래걸렸습니다ㅠㅠ(아직 완벽하지 않아서 조금 더 시간을 투자할 계획입니다.)
아직 비동기를 이용한 코드에 대한 경험이 많지 않았기 때문에 더욱 더디게 학습하였는데요.
이번 기회를 통해서 '비동기'에 대한 개념에 대해서 전보다 더 잘 이해할 수 있었습니다. 
크롱이 피드백 주신 내용들 덕분에 학습에 큰 도움이 되었습니다. 감사합니다.

"동료들에게 특강"에 대해선 더욱 명확하게 개념을 파악한 이후에 할 수 있을것 같습니다..ㅎㅎ

2018-10-26 02:19 UTC, crongro approved these changes
잘 수정했네요.
객체 나눈 것에 대해서 스스로 회고를 좀 해보세요.
본인 코드에 대해서 장단점을 느껴보고, 느낀점도 어딘가 정리까지 하면 더 좋고요. 

비동기처리는 다양한 방법이 있지만, 간단하게 구현할 수 있으면 그렇게 하도록 하시고요.
이번 스텝에서 시도한 학습방법은 좋아요. 뭔가 깊게 공부하고 이를 적용해보는 건 매우 좋습니다.  👍

2018-10-26 02:20 UTC, merged