lec3-Step4.ES6 Classes로 개선
code-squad/javascript-todo pull request #58
Opened 2018-10-21 03:31 UTC by HTMLhead

* 피드백에 의한 수정
  1. 모든 클래스를 대문자로 시작하는 단어로 바꾸었습니다.
  2. Todo객체 내에서 다시 History객체 내로 들어가 데이터를 pop해주는 대신 History객체 내에서 데이터를 pop해줄 수 있도록 수정 하였습니다.
  3. 하드코딩한 숫자 3을 limitNum이라는 변수에 넣어줌으로써 의미를 부여하도록 하였습니다.
*  코드맥락
   1. 새로운 할 일을 만들때, 그리고 statusNum을 초기화할때 class문법을 사용하도록 구현하였습니다.
   2. 새로운 기능을 두가지 추가하였습니다.
      1. 이제부터 할 일을 추가할 때 동기부여가 되도록 명언을 하나씩 보여줍니다. 
마치 플러그인처럼 넣었다 뺏다 할 수 있도록 AddWiseSaying객체를 만들었습니다.
      2. 할 일을 초기화 할 수 있게 되었습니다.(undo, redo, 가능)
할 일이 비어있다면 에러메세지를 반환합니다.

* 노력한 점
   1. class문법을 어떻게하면 잘 활용할 수 있을지 생각해 보았습니다.

* 반성한 점
커밋 메세지가 이전에 비해 많이 빈약해진 것 같습니다. 다음부턴 버그를 수정하거나 함수단위로 무언가를 추가할 때마다 꼭꼭 잊지않고 커밋 메세지를 남겨야겠다고 생각했습니다.

2018-10-21 11:29 UTC, crongro requested changes
todo, History 등  모든 객체를 모두 다 ES6 Class로 다 변경해보세요.
클래스의 의존관계가 있다면 클래스를 초기화할때 전달 받아서 사용하고요
a = new A();
b  = new  B(a); // b가 a를 의존하고 있다면 이렇게 객체를 주입.

2018-10-21 11:29 UTC, nigayo commented on todo.js
>      update(objToUpdate) {
함수를 조금더 작게 해보는 연습을 해보면 좋겠어요.
update 메서드를 작은 메서드 1~3개로 분리해볼 수 있을까요?

2018-10-21 11:29 UTC, nigayo commented on todo.js
> +const Show = {
객체나 클래스의 이름은 대문자로 시작하는 명사가 좀더 좋아요.
(show를 뭘로 바꾸지.. 미얀)

2018-10-21 11:31 UTC, HTMLhead commented on todo.js
>      update(objToUpdate) {
바로 해보겠습니다

2018-10-21 11:31 UTC, HTMLhead commented on todo.js
> +const Show = {
ㅋㅋㅋㅋ사전을 한번 뒤져봐야겠네요 알겠습니다!

2018-10-23 02:15 UTC, crongro approved these changes
💯  잘 했어요. 
step4 까지 끝~!

2018-10-23 02:15 UTC, nigayo commented on todo.js
> +        const newTodo = new Task(this.getRanNum(this.todoList), objToAdd.name, 'todo', objToAdd.tag, 0)
한줄로 다 표현하지 말고, getRanNum()의 결과를 변수로 저장하고, 그 변수를 Task의 인자로 추가하면 보기 좋을 듯.

2018-10-23 02:15 UTC, nigayo commented on todo.js
> +        this.History = History;
클래스는 대문자로 쓰지만.. 객체는 소문자로 사용하는 게 일반적 ^^

2018-10-23 02:15 UTC, merged

2018-10-24 07:15 UTC, HTMLhead commented on todo.js
> +        this.History = History;
숙지하겠습니다😄 피드백 주신대로 수정한 후에 다음 lecture로 넘어가 보겠습니다~!!