[숨] lec3 - step3
code-squad/javascript-todo pull request #59
Opened 2018-10-22 03:16 UTC by developersoom

** lec3 할일관리 애플리케이션 - step3 사용성 향상 **
첫 구현하였습니다. 
리뷰 부탁드립니다아아앗 😸

2018-10-23 01:27 UTC, crongro commented
커밋로그 상당히 좋고요.
커밋로그의 prefix 뒤에 점(.)을 찍으면 더 좋을 듯.
ex) Fix. typo & change undo error messsage.

2018-10-23 01:38 UTC, crongro requested changes
객체를 크게 몇 개로 아주 잘 나눴어요. 
이정도의 감을 유지하면서 앞으로 객체를 활용해보세요. 

코드수정할 부분이 좀 보이니 수정하고 넘어가죠~

2018-10-23 01:38 UTC, nigayo commented on Lec3_ToDoList.js
> +        if (errorCheck.add(task)) {
이렇게 조건문 안에 함수를 표현하면 읽기 좋은 코드가 되죠. 잘 했어요.

2018-10-23 01:38 UTC, nigayo commented on Lec3_ToDoList.js
> +        if (errorCheck.remove(id)) {
if안에 모든코드가 들어가 있으니..
if(!errorCheck.remove(id))  return;
해서 빨리 탈출해서 indent를 제거하면 좋겠음.

2018-10-23 01:38 UTC, nigayo commented on Lec3_ToDoList.js
> +            for (const values of this.taskList) {
자바스크립트에서 for-of를 쓸 수 있는 타입은 무엇인지 한번 찾아서 공부해두세요.

2018-10-23 01:38 UTC, nigayo commented on Lec3_ToDoList.js
> +                if (values.id === id.id) {
for-of 안에서 if문을 썼는데요.

filter -> forEach 방식으로 바꿔보세요.  함수형프로그래밍 형태로 데이터를 처리하는게 좀더 읽기 좋고, 함수단위로 기능을 세분화시키는 것이라 좋아요.

2018-10-23 01:38 UTC, nigayo commented on Lec3_ToDoList.js
> +            this.cacheList.shift();
shift() 똑같은코드를 여러번 쓰는 것보다, 
while문등으로 cacheList의 길이가 주어진 값(3)이 될때까지 반복적으로 shift호출하는 게 좀더 똑똑한 표현같아요.

2018-10-23 01:38 UTC, nigayo commented on Lec3_ToDoList.js
> +            this.cacheList.push(func, Object.assign({}, task));
object.assign 동작에 대해서 설명해보세요. 댓글로.

2018-10-23 01:38 UTC, nigayo commented on Lec3_ToDoList.js
> +        this.undoCacheList.pop();
계속 반복적으로 pop(), shift() 등을 호출하고 있네요.
위에 언급한대로 수정하고, (반복문활용)
자꾸 사용되는 코드임으로, 함수로 별도로 만드는 것이 좋음.

2018-10-23 01:38 UTC, nigayo commented on Lec3_ToDoList.js
> +        for (const values of todo.taskList) {
for-if-if ..
이렇게 중첩된 코드는 안좋은 코드~ 읽기 어렵고 디버깅이 어려운 코드에요.

2018-10-23 06:28 UTC, developersoom commented on Lec3_ToDoList.js
> +            for (const values of this.taskList) {
넵!

2018-10-23 10:34 UTC, developersoom commented on Lec3_ToDoList.js
> +            this.cacheList.push(func, Object.assign({}, task));
object.assign을 쓰면 이후에 undo나 redo를 통해 task의 값이 바뀌어도 처음에 입력한 데이터 값에 영향을 주지 않습니당.

2018-10-23 12:45 UTC, developersoom commented
피드백 주신대로 코드 수정하였습니다. 😆 
중복코드 제거와 인덴트를 줄이기 위해 노력했습니다. 
리뷰 부탁드립니다아~

2018-10-24 06:00 UTC, crongro approved these changes
잘 수정했어요.
충분히 코드가 좋아진 거 같아요.

이제 다음 step을 해보세요!

2018-10-24 06:00 UTC, crongro commented on Lec3_ToDoList.js
> +        console.log(`id : ${taskToRemove[0].id}, "${taskToRemove[0].name}" 삭제 완료.`);
삭제는 아래에서(splice) 하는데, 
벌써 삭제했다고 거짓말하면 어떻게 해요.

2018-10-24 06:00 UTC, crongro commented on Lec3_ToDoList.js
> +        todo.taskList.push(undoArg);
todo는 외부의 객체인데요.
외부의 객체의 속성을 접근하고 싶을때는 todo.taskList 라기보다는, todo.getTaskList() 와 같은 메서드를 통한 접근방법으로 통일해서 쓰면 더 좋아요.

2018-10-24 06:00 UTC, merged

2018-10-25 01:59 UTC, developersoom commented on Lec3_ToDoList.js
> +        console.log(`id : ${taskToRemove[0].id}, "${taskToRemove[0].name}" 삭제 완료.`);
ㅎ... 수정하겠습니다....

2018-10-25 02:47 UTC, nigayo commented on Lec3_ToDoList.js
> +        console.log(`id : ${taskToRemove[0].id}, "${taskToRemove[0].name}" 삭제 완료.`);
프로그래밍 로깅은 어떤 사건이 정확히 일어난 후에 기록하는게 좋아요~

2018-10-25 02:49 UTC, developersoom commented on Lec3_ToDoList.js
> +        console.log(`id : ${taskToRemove[0].id}, "${taskToRemove[0].name}" 삭제 완료.`);
넵! ㅋㅋ 수정하다보니 의도치않게 거짓말을 하게 되었습니다...ㅋㅋㅋ