Step3 PR 입니다
code-squad/javascript-todo pull request #62
Opened 2018-10-24 16:51 UTC by sk2504

commit을 거의못했습니다 다음번엔 더작은단위로 할수있도록 하겠습니다!
피드백 부탁드립니다

2018-10-25 07:20 UTC, crongro requested changes
taskClipBoard 는 아주 잘 만들었어요. 아이디어도 괜찮고요.

몇개 부분에 리뷰를 남겨드렸으니 고민해서 선택적으로 수정해보시고요.

taskProgram 객체는 응집도는 높은 코드가 됐지만, 객체 단위를 1개에서 2개로 나눠볼 부분은 없을지 생각해보세요.
억지로 나눌 필요는 없으니, 고민의 시간을 좀더 갖아보면 좋겠습니다.
그래서 필요하면 다른 객체로 나누고 taskProgram과 협력을(함수호출) 하는 구조로 만들어보세요.

2018-10-25 07:20 UTC, crongro commented on index.js
> +    clipBoard: Object.seal(new Array(3).fill(undefined)),
어디서 이런 신선한 아이디어를 얻었나요? ㅎ 
잘하셨어요.
seal 과 freeze 의  차이도 알아두면 좋을 듯.

2018-10-25 07:20 UTC, crongro commented on index.js
> +            console.log('올바른 입력값이 필요합니다. "id$state 또는 {id: nexststatus: } " 중하나를 입력하세요.');
이런 에러처리 좋아요~ 사용법까지 잘 설명해주니 쓰기 좋죠.

2018-10-25 07:20 UTC, crongro commented on index.js
> +        if (this.undoCount === 3) {
checkUndoCount(undoCount) {

}

이런식으로 this 로 접근하지 않고 인자로 넣어도 됩니다. 이렇게 하는 게 this로 접근하는 것보다 인자로 무엇을 받는지 알 수 있어서 좋은코드에요.

2018-10-25 07:20 UTC, crongro commented on index.js
> +        [Savedfunc.function, Savedfunc.argument, Savedfunc.id] = [name, argument, id];
clipboard 아이디어는 좋아요.
function을 넣은것과 , pastState도 적절한 속성으로 보입니다.

2018-10-25 07:20 UTC, crongro commented on index.js
> +    undoCount: 0,
이와 같은 상태를 둬야 할 때가 있는데요.
항상 best방법은 아닙니다. 

어쨋든 이런 상태값을 보관해야 한다면, 상태관리가 잘 되어야 합니다.

2018-10-25 07:20 UTC, crongro commented on index.js
> +            } else if (obj.function.name === 'update') {
객체의 이름이 function이라 예약어를 쓰는 느낌이들어요.
fn 정도가 적당해보이네요.

2018-10-25 07:20 UTC, crongro commented on index.js
> +                let conleobj = this.createRversedArg(obj);
변수명이 이상해요.. conleobj ?

2018-10-25 07:20 UTC, crongro commented on index.js
>      settime(n, statesArray, setTimeArray) {
이름을 잘 짓고 있는데요.
간혹 카멜표기법을 쓰다 안쓰다 하는 경우가 눈에 띕니다.

2018-10-25 07:20 UTC, crongro commented on index.js
> +        if (this.checkParametertype(obj)) {
자주 언급한 내용인데요.
if(!this.checkParametertype()) return; 
이렇게 해서 들여쓰기를 없앨수있죠.

2018-10-25 07:20 UTC, nigayo commented on index.js
> +                let conleobj = this.createRversedArg(obj);
createRversedArg 함수 이름도 잘못된건지 뜻을 알기가 어렵습니다!

2018-10-25 07:20 UTC, nigayo commented on index.js
> +                taskProgram.update(conleobj, 1);
이렇게 실행하는 게 좀더 똑똑한 거 같아요.

taskProgram[obj.function.name](conleobj,1);

2018-10-25 07:20 UTC, nigayo commented on index.js
> +                if (obj.name === taskobj.name) {
else if  - for - if ..좀 복잡한 코드네요.

2018-10-26 08:52 UTC, sk2504 commented
피드백 주신 사항 수정해보았습니다.

examine 이라는 객체를 추가해서 taskProgram 과 협력할수있도록 만들었습니다.
피드백 주신것중에 taskProgramobj.function.name; 이렇게 실행하라고 알려주신 부분이
잘 이해가 안갑니다!

2018-10-29 02:01 UTC, nigayo commented on index.js
> +                taskProgram.update(conleobj, 1);
흑, 제가 제대로 설명을 못했네요. 

taskProgram.update(conleobj, 1) 
이렇게 호출하고 있는데요. 
 update나 remove 이런 이름이 이미 name에 지정되어 있으니 이렇게 호출할 수 있을 거 같아요. 

taskProgramobj[obj.function.name]()

2018-10-29 02:11 UTC, crongro approved these changes
수고하셨네요.
새로운 객체를 두고 협력하는 시도는 좋았어요.
그 객체의 역할이 유틸리티(이것저것 부수적인 처리를 도와주는)에 가까운 객체 같습니다.
즉 보조역할을 하는 듯 해보여요. examine에 맞게 맞추기보다, examine의 이름을 다시 지어도 될 거 같습니다 ^^

객체의 협력에 집중해서 이해를 했기를 바라고요.
객체들의 역할은 계속 고민하셔야 할 거 같네요.

수고하셨고, 다음 step 진행하세요!

2018-10-29 02:11 UTC, nigayo commented on index.js
> +        if (!this.checkUndoCount(this.undoCount)) return;
잘 했어요. 항상 indent를 줄이도록 노력해보세요.

2018-10-29 02:11 UTC, nigayo commented on index.js
> +        examine.checkTag(obj);
checkTag는 tag를 체크해서 true/false로 반환할 거 같은데요. 
실제로는 그렇지 않고 뭔지 모르는 무언가를 처리하는 코드네요. 
examine가 체크를 대신해주는 역할이라면 checkTag의 동작은 어울리지 않는 동작이라고 볼 수 있어요 .

2018-10-29 02:11 UTC, nigayo commented on index.js
>      removeSpace(obj) {
examine 에 있는 이녀석도, 어찌보면 유틸리티 함수라고 생각합니다.
무언가를 평가(examine)해주는 건 아닌거 같아요.

2018-10-29 02:14 UTC, merged