토마스 step3
code-squad/javascript-todo pull request #66
Opened 2018-11-27 12:58 UTC by woogyunThomasSeo

오랜만에 PR보내요~

2018-11-28 03:56 UTC, nigayo commented
master 브랜치로 보내지말고, 본인의 github아이디로 된 브랜치로 보내주세요 ~ @woogyunThomasSeo

2018-11-28 04:01 UTC, crongro requested changes
오랜만에 PR!! 

update함수만 수정해볼래요? 
다른 리뷰는 참고하시고, 선택적으로 수정하세요.(필수아님)

2018-11-28 04:01 UTC, crongro commented on L3_S3.js
> +    for (let task of this.taskList) {
for-of가 간편하죠. 이제는 for-of를 쓸 수 있는 건 그렇게 해보세요.

2018-11-28 04:01 UTC, crongro commented on L3_S3.js
> +    return new Date().getTime();
이렇게 한줄짜리 메서드를 만드는 것도 좋아요.

2018-11-28 04:01 UTC, crongro commented on L3_S3.js
> +          if (undo === undefined) {
다음엔 if-if 중첩된 것은 다른방법이 없을지 고민하면 더 좋겠어요.

2018-11-28 04:01 UTC, crongro commented on L3_S3.js
> +        return false;
반환값이 있는 것이 우선 좋고, 
반환 type이 boolean type 하나로 동작하는 것도 좋네요.

2018-11-28 04:01 UTC, crongro commented on L3_S3.js
> +    this.todoCount = 0;
this에 꼭 추가할필요는 없어요.
메서드안에서만 필요한변수(데이터, 또는 상태라고도 하고)라면  지역변수로 선언하기.(const,let을 활용)

2018-11-28 04:01 UTC, crongro commented on L3_S3.js
> +  update(newTask, undo) { // 현재상태를 갱신
update함수는 규모가 좀 큰편이에요.
3개로 나눠보면 더 좋겠음.

2018-11-28 04:01 UTC, nigayo commented on L3_S3.js
> +    debugger;
PR보낼때는 괜찮은데, 배포할때는 이런 디버깅코드는 항상 주의해서 삭제해야겠죠.(실무에서는 빌드도구가 제거해줄수도있음)

2018-11-28 04:01 UTC, nigayo commented on L3_S3.js
> +    let sortTaskArr = [[], [], []]; // todo, doing, done
재할당을 할 것이 아니면, const를 쓰도록해보삼

2018-11-28 04:01 UTC, nigayo commented on L3_S3.js
> +    for (let i = 0; i < tagsArray.length; i++) {
여기서도 for-of를 쓸 수 있을듯한데요

2018-12-06 01:40 UTC, nigayo commented
@woogyunThomasSeo  지금 이거 수정중인가요?

2018-12-07 06:01 UTC, woogyunThomasSeo commented
수정 끝났습니다.

2018-12-10 03:04 UTC, crongro approved these changes
전체적으로 잘 구현했어요. 

아쉬운점 몇가지만 남깁니다.

코드 복잡도가 높은 코드가 조금 보여요.  반복문과 조건문을 중첩되게 쓰는 건 계속 줄이려고 해보세요. 

for문보다는 for-of를 쓰거나, filter/forEach/map을  연결해서 사용하면 더 작은 함수들이 생기고 이들을 재사용할 수도 있어서 더 좋아요. 

함수들의 크기는 명확해서 좋아요. 

간혹 2,3,2 와 같은 magic number를 코드에 그대로 두는 경우가 있는데, 의미를 값에 부여해서 쓰세요.

클래스 한가지로 프로그래밍을 만들었지만, 
앞으로는 한개 이상의 클래스를 만들어서 객체간의 호출을 통해 협력하는 코드를 시도해야 합니다.

2018-12-10 03:04 UTC, merged