step4-1 todo 앱 설계와 구현
code-squad/javascript-todo pull request #81
Opened 2019-04-15 08:15 UTC by andole87

2019-04-15 08:50 UTC, crongro requested changes
몇개 개선사항을 도전적으로 드렸네요.

도전!

2019-04-15 08:50 UTC, nigayo commented on todo.js
> +        name: '크롱과 뽀로로보기',
언제 볼까요?

2019-04-15 08:50 UTC, nigayo commented on todo.js
> +        showFilteredTodo(todos,filterArg);
이름이 맘에 드네요.
명확함.

2019-04-15 08:50 UTC, nigayo commented on todo.js
> +        const todoMap = getTodoMap(_filteredArray);
동일한 filteredArray 라도 계속 Map을 만드는 데요. 이를 개선해보면 좋겠네요.

2019-04-15 08:50 UTC, nigayo commented on todo.js
> +            console.log(`${key}는 ${value}임.`);
참고. 
한줄로 이어써야 한다면 reduce를 활용할 수도 있겠죠!

2019-04-15 08:50 UTC, nigayo commented on todo.js
> +        todoMap.forEach(function (value, key) {
새로운 count를 만들어낸다면, reduce를 쓸 수도 있겠죠? 

그런데 map형태죠... 방법이 있다고 합니다. 
Map 자료구조에서  reduce를 사용해보세요!

2019-04-15 15:47 UTC, andole87 commented
추가로 푸시 하였사옵니다. 🔥

2019-04-15 23:05 UTC, crongro approved these changes
잘 했 음.

2019-04-15 23:05 UTC, nigayo commented on todo.js
> +        return new Map(Object.entries(middleObj))
아 맵으로 변환하는 군요 ㅎ 
잘했어요.

2019-04-15 23:05 UTC, nigayo commented on todo.js
> +        const showMessageArray = Array.from(todoMap.keys())
key만 필요하니 이렇게 하면 되는군요.
spread operator 로 변환하는 방법도 찾아보세요.

2019-04-15 23:05 UTC, nigayo commented on todo.js
> +            .reduce((acc, curr) => {
reduce로 잘했네요! 
map으로 해결될 수 있는지도 생각해보세요.
그렇다면 map이 더 어울릴수 있겠네요.

2019-04-15 23:06 UTC, nigayo commented
페어가 누구죠? PR보내실때 다음엔 페어명도 같이 적어주셔야~

2019-04-15 23:06 UTC, merged

2019-04-15 23:26 UTC, andole87 commented
wook과 페어입니다. 죄송..

2019-04-16 01:05 UTC, wo0kgod commented
와 ... 머지됬네요 .... 나도 하려고했는데....

2019-04-16 03:21 UTC, wo0kgod commented on todo.js
> +        const todoMap = getTodoMap(_filteredArray);
이게 무슨뜻인지 모르겠습니다 ㅠㅠ 
show('todo');가 2번 실행되서 
filterArg로 todo 가 들어오고, 그 다음에 다시 todo가 입력될때 
Map이 2번 만들어진다는 뜻인가요?

2019-04-16 03:21 UTC, wo0kgod commented on todo.js
> +        const todoMap = getTodoMap(_filteredArray);
> 동일한 filteredArray 라도 계속 Map을 만드는 데요. 이를 개선해보면 좋겠네요.

이게 무슨뜻인지 모르겠습니다 ㅠㅠ 
show('todo');가 2번 실행되서 
filterArg로 todo 가 들어오고, 그 다음에 다시 todo가 입력될때 
Map이 2번 만들어진다는 뜻인가요?