step4-1 미션 (Q & Sony)
code-squad/javascript-todo pull request #84
Opened 2019-04-16 06:42 UTC by sonypark

Q & Sony

step4-1 미션

todos.js 함수에 대한 설계와 코드 구현 완료했습니다.

2019-04-16 06:49 UTC, sonypark commented
repository 경로를 잘 못 설정해서 다시 Pull request 보냈습니다...!

2019-04-16 10:05 UTC, crongro requested changes
어쩌다 늦었군요.
몇 개 리뷰를 남겨드리니 가능한 것들 수정해보세요.

2019-04-16 10:05 UTC, nigayo commented on step4/step4-1/pseudoCode.md
> +const show = (array, status) => {
참고로 pseudo code라면 더 간단해도 됩니다.

2019-04-16 10:05 UTC, nigayo commented on step4/step4-1/todoList.js
> +    switch (status) {
todo/doing/done 케이스의 코드들이 비슷한 거 같네요. 
중복을 제거하는 방법을 생각해보세요.

2019-04-16 10:05 UTC, nigayo commented on step4/step4-1/todoList.js
> +const getAllStatus = array => {
array라는 변수명은 이미 자바스크립트에 있는 keyword라서 안쓰는 게 좋습니다.(new Array..)

2019-04-16 10:09 UTC, sonypark commented
피드백 감사합니다. 내일까지 수정해서 보내겠습니다!

2019-04-17 04:38 UTC, sonypark commented on step4/step4-1/pseudoCode.md
> +const show = (array, status) => {
더 간단하게 수정했습니다!

2019-04-17 04:38 UTC, sonypark commented on step4/step4-1/todoList.js
> +    switch (status) {
피드백 반영하여 중복된 부분 제거하고 단순화 시켰습니다.

2019-04-17 04:38 UTC, sonypark commented on step4/step4-1/todoList.js
> +const getAllStatus = array => {
변수 이름을 array에서 todoList로 변경했습니다.

2019-04-18 08:03 UTC, crongro approved these changes
네 확인했습니다.
제가 늦었네요!

2019-04-18 08:03 UTC, nigayo commented on step4/step4-1/todoList.js
> +    let todoCount = 0
이건 객체나 Map객체를 활용해서 데이터 관리를 하는 게 더 좋아보이네요.

2019-04-18 08:03 UTC, merged