step4-2 할일 관리 프로그램 : 대화형 구현
code-squad/javascript-todo pull request #86
Opened 2019-04-18 07:42 UTC by Soorealbutnice

circus & 수리

step4-2 대화형프로그래밍 구현

2019-04-18 08:28 UTC, crongro reviewed
버그해결부탁.

2019-04-18 09:07 UTC, crongro requested changes
대체로 간결하고 코드의 동작을 이해하기  쉽게 구현한 거 같아요.

리뷰 남겨드린 부분 수정해보세요.

2019-04-18 09:07 UTC, crongro commented on step4_2_todos.js
> +const todos = require("./todos");
데이터 모듈 분리 잘했어요.

2019-04-18 09:07 UTC, crongro commented on step4_2_todos.js
> +        let key = todo.status;
const를 먼저쓰고, 문제가 있으면 let을쓰고, var는 단점이 많아서 안쓰고.
이렇게 많이 하는데요.
이유를 찾아보고 이렇게 전체적으로 코드를  바꿔보세요.

2019-04-18 09:07 UTC, crongro commented on step4_2_todos.js
> +    newTodoList = {'todo' : [], 'doing' : [], 'done' : []};
이거 전역변수군요! 음 개선할 수도 있을까요?

2019-04-18 09:07 UTC, nigayo commented on step4_2_todos.js
> +    for(key in newTodoList){
newtodolist라는 건  'list' 이름 때문에 배열같네요.

2019-04-18 09:07 UTC, nigayo commented on step4_2_todos.js
> +        inputOrder(todos.todos);
todos.todos 라는 것이 좀  헷갈리는 key이름이네요.

2019-04-18 09:07 UTC, nigayo commented on step4_2_todos.js
> +    }).map((obj) => { return obj.name });
arrow function이 간결할때는 return 을  생략해도 return 됩니다. 예제를 좀더 찾아보시고 수정해보세요.

2019-04-18 09:07 UTC, nigayo commented on step4_2_todos.js
> + let printStatusAfterCheckKwd = function (searchKeyWord, newTodoList) {
이 함수를 let으로 한 이유는 수정되는 함수라서 그런건가요?

2019-04-18 09:07 UTC, nigayo commented on step4_2_todos.js
> +    if (keyWord == 'status') {
==, === 두 개중 ===만 사용하는게 좋고, 
그 이유를 여기에 남겨주세요.

2019-04-18 09:07 UTC, nigayo commented on step4_2_todos.js
> +const makeUI = () => {
UI라는 단어는 너무 광범위해서 의도를 알기 어려워보여요.

2019-04-18 09:07 UTC, nigayo commented on step4_2_todos.js
> +    todo = {
이녀석도 전역변수인가요? 개선할 수 있을지 검토해주세요.

2019-04-18 09:07 UTC, nigayo commented on step4_2_todos.js
> +        if(todo.id === Number(args[1])){
args1이 뭔지 args2이 뭔지.. 등등 알기가 어렵죠? 만약 이런게 많아지면 더 보기 어렵고요.
변수를 만들고 의미를 드러내는게 더 좋을 거 같군요.

이런 방식도 살펴볼래요?
https://dev.to/sarah_chima/destructuring-assignment---arrays-16f

2019-04-19 07:12 UTC, Soorealbutnice commented on step4_2_todos.js
> +    if (keyWord == 'status') {
== 은 값이 같은지만 비교하고, ===은 값과 타입까지 모두 같은지 비교합니다.
==으로 값을 비교하는 경우, 암묵적인 형변환이 일어난 뒤 두 값을 비교하기 때문에 의도하지 않은 결과가 도출될 수 있습니다.

`
if (1 == true) {
    console.log('형변환 발생')
}
// 형변환 발생

if (1 === true) {
    console.log('형변환 발생')
}
//
`

2019-04-22 05:51 UTC, crongro requested changes
작은 거 하나 수정해보세요.

2019-04-22 05:51 UTC, nigayo commented on step4_2_todos.js
> +            if (updatedSchedule[4] !== 'nc') {
여기 if문 3개가 중복코드인데요.. 이부분 중복을 없애보세요.

2019-04-22 05:51 UTC, nigayo commented on step4_2_todos.js
> +            if (updatedSchedule[2] !== 'nc') {
중첩된 if 문이 보이면 개선하도록 하세요.
여기서는 === 상황을 먼저 체크하고 return 하는 게 어때요?

2019-04-22 08:56 UTC, crongro approved these changes

2019-04-22 08:56 UTC, nigayo commented on step4_2_todos.js
> +            printUpdate(todo,updatedSchedule)
oh ! 조건문을 없앴군요.

2019-04-22 08:57 UTC, merged