Gren&왕민 step4-2 미션
code-squad/javascript-todo pull request #87
Opened 2019-04-18 08:07 UTC by Min-92

리뷰부탁드립니다.

2019-04-18 08:57 UTC, crongro requested changes
간결하게 잘 구현한 편입니다.
리뷰남긴 부분 한번 수정해보세요.

2019-04-18 08:57 UTC, nigayo commented on app.js
> +    if(actionMatchResult === null){
꼭 정규표현식만 가능한건 아니지만 
정규표현식을 이용한 방법을 시도한 거 좋네요.

2019-04-18 08:57 UTC, nigayo commented on todo.js
> +const ids = [423, 1535, 9999, 512, 2, 77];
윽 별건 아닌데 옥의티군요.
todo 데이터를 탐색해서 id 중복을 체크하도록 해보세요.

2019-04-18 08:57 UTC, nigayo commented on todo.js
> +      id = Math.floor(Math.random() * 10000) + 1;
10000 이런 값은 변경가능한  내용임으로, 파라미터로 받는 게 어때요?

2019-04-18 08:57 UTC, nigayo commented on todo.js
> +      countObj[status] += 1;
객체 key를 잘 활용했네요.
++ 도 있긴하죠.

2019-04-18 08:57 UTC, nigayo commented on todo.js
> +      .filter(function (element) {
한줄로 map까지 표현해보세요. 간단한 코드는 그런코드가 보기 더 좋긴하죠.

2019-04-18 08:57 UTC, nigayo commented on todo.js
> +    namesArr.forEach(function (element, index) {
arrow function 즐겨사용하면 더 보기 좋음.

2019-04-18 08:57 UTC, nigayo commented on todo.js
> +    todos.forEach((element, index) => {
여기는 filter &  reduce 같은 메서드로 수정할까요? (검토해보세요)

2019-04-18 08:57 UTC, nigayo commented on todo.js
> +    const statusReg = /^todo$|^doing$|^done$/;
별건 아니지만 자꾸 중복코드로 보입니다. 어떻게 하면 좋을까요?

2019-04-18 08:57 UTC, nigayo commented on todo.js
> +      log("update명령어의 인자가 잘못 되었습니다");
message를 함수안에서 모두 제거하고 밖에 객체매핑으로 만드는 건 어때요?
ex)
const MSG = {
  XXX_ERR : "어쩌다에러.."
}

2019-04-22 04:49 UTC, Min-92 commented
수정완료 했습니다.
리뷰부탁드립니다!

2019-04-22 05:53 UTC, crongro approved these changes
업데이트된 것을 늦게 확인했네요.
수고하셨어요.
확인&&머지합니다.

2019-04-22 05:53 UTC, merged