Step4-2 CHANNY & H 페어프로그래밍
code-squad/javascript-todo pull request #93
Opened 2019-04-19 04:46 UTC by aftersnowing

2019-04-19 05:27 UTC, crongro reviewed
(버그해결 대기중...)

2019-04-19 05:34 UTC, aftersnowing commented
> (버그해결 대기중...)

2019-04-19 05:59 UTC, crongro requested changes
잘 구현했어요 👍 

간단한 리뷰남깁니다. 
수정 & 설명 부탁드려요.

2019-04-19 05:59 UTC, nigayo commented on application.js
> +    if (line === 'q') {
q 좋은 문자네요 ㅎㅎ

2019-04-19 05:59 UTC, nigayo commented on application.js
> +function application(line) {
함수로 다른 함수를 감싸면 좋은 점은 무엇인가요?

2019-04-19 05:59 UTC, nigayo commented on application.js
> +        if (!utils.isValidName(name)) return r.prompt();
조금이라도 중복을 줄이려면, ('return r.prompt();') 
조건문 두개를 한개로 바꾸는 게 좋겠네요.

2019-04-19 05:59 UTC, nigayo commented on application.js
> +            .filter((el) => el['status'] === status[0])
체이닝 잘 사용했어요

2019-04-19 05:59 UTC, nigayo commented on application.js
> +        objToAdd['id'] = Math.floor(Math.random() * (100000 - 10000 + 1) + 10000);
만약, 5자리가 아니가 다른자리로 만들겠다! 그렇다면 이부분을 수정할텐데요.
자리수를 입력받아서 랜덤값을 생성하는 함수를 한번 만들어보세요.

2019-04-19 05:59 UTC, nigayo commented on application.js
> +        todos.some((el, i) => {
빨리 반환할 수 있는 some을 잘 선택했네요. 불필요한 반복을 줄이기 위해서는 유용한 함수죠.

2019-04-19 06:06 UTC, aftersnowing commented on application.js
> +function application(line) {
전역스코프에 함수가 속해 있다면 다른 함수를 추가 구현할때 중복될수도 있고 예상치 못한 버그를 일으킬수도 있다고 생각했습니다.

2019-04-22 05:57 UTC, nigayo commented on application.js
> +function application(line) {
네 함수로 private한 것을 만들수가 있죠. 의도를 잘 알고 사용했네요. 
모듈패턴도 공부해보세요.

2019-04-22 06:03 UTC, crongro approved these changes
유용한 유틸리티가 앞으로 생기면 utils.js 처럼 별도 파일로 분리해서 관리하고,
다음프로젝트(미션등)에서 쓸 수도 있겠죠.
이렇게 작은 라이브러리를 만들어가는 경험도 매우 좋아요.

2019-04-22 06:03 UTC, nigayo commented on application.js
> +        objToAdd['id'] = utils.makeRanNum(5,todos);
메서드 잘 만드셨네요.

2019-04-22 06:03 UTC, nigayo commented on application.js
> +        if (!utils.isValidId(id) || !utils.isValidStatus(status)) return r.prompt();
좋아요 잘 수정했네요.

2019-04-22 06:04 UTC, merged