Step4-2: Q & Sony
code-squad/javascript-todo pull request #94
Opened 2019-04-19 06:05 UTC by sonypark

Q & Sony

step4-2 미션 코드는 step4-2 폴더에 저장되어있습니다.

피드백 부탁드립니다.

2019-04-19 07:33 UTC, nigayo commented
충돌좀 해결해서 다시 push해주세요.
그리고 step별로 디렉토리를 따로 두지 않고, 
git을 더 잘 활용하도록 하세요. git branch를 사용할 수도 있을거 같네요
@sonypark

2019-04-19 10:38 UTC, sonypark commented
충돌 해결 후 다시 push 했습니다.
앞으로는 폴더가 아닌 git branch를 이용해 step 관리를 하도록 하겠습니다.

2019-04-20 00:48 UTC, crongro requested changes
간결하게 잘 구현했어요.
(승인하려다가) 조금만 더 수정하면 더 좋을 거 같습니다.

2019-04-20 00:48 UTC, nigayo commented on step4/step4-1/todoList.js
> +            printListAll(todoCount, doingCount, doneCount)
출력 메서드를 분리한 것은 잘 했어요!

2019-04-20 00:48 UTC, nigayo commented on step4/step4-1/todoList.js
> +    return [todoCount, doingCount, doneCount]
객체를 쓸 수도 있고, 배열을 사용한 것을보니 괜찮네요. 
하지만 객체에는 key가 있는셈이라, 자료에 접근하기가 좀더 편한 장점이 있겠죠.

2019-04-20 00:48 UTC, nigayo commented on step4/step4-2/todoApp.js
> +    return
return 을 하나 안하나 undefined이니까 지금은 할 필요가 없겠죠?

2019-04-20 00:48 UTC, nigayo commented on step4/step4-2/todoApp.js
> +    const newID = Math.floor(Math.random() * 10000) + 1;
10000 이런걸 매직넘버라고 하는데 없애도록 해보세요.

2019-04-20 00:48 UTC, nigayo commented on step4/step4-2/todoApp.js
> +        }, 3000);
사실 3000,1000 이것도 모두 매직넘버..

2019-04-20 00:48 UTC, nigayo commented on step4/step4-2/todoApp.js
> +    return [totalCount, done_result];
getTodoName은 숫자값도 계산하고, 새로운배열도 만드는 역할이네요.
이 두가지가 하나의 객체에 담겨져 있으면 어때요?  reduce를 사용해서요.

2019-04-20 15:33 UTC, sonypark commented on step4/step4-2/todoApp.js
> +    return
네 마지막 return은 삭제했습니다 :)

2019-04-20 15:34 UTC, sonypark commented on step4/step4-1/todoList.js
> +    return [todoCount, doingCount, doneCount]
피드백 반영하여 객체로 디스트럭쳐링해서 객체의 key로 프로퍼티를 받아오도록 수정했습니다.

2019-04-20 15:34 UTC, sonypark commented on step4/step4-1/todoList.js
> +            printListAll(todoCount, doingCount, doneCount)
감사합니다!ㅎㅎ

2019-04-20 15:35 UTC, sonypark commented on step4/step4-2/todoApp.js
> +        }, 3000);
매직넘버를 없애고 함수의 인자값으로 받도록 수정했습니다.

2019-04-20 15:36 UTC, sonypark commented on step4/step4-2/todoApp.js
> +    return [totalCount, done_result];
이 부분도 피드백 반영하여 reduce함수를 이용해 수정했습니다.
숫자값 계산과 배열 생성을 객체에 담아 한번에 처리했습니다.

2019-04-22 05:11 UTC, crongro approved these changes
네 step4-2 확인했어요.
수고하셨습니다.

2019-04-22 05:11 UTC, nigayo commented on step4/step4-2/todoApp.js
> +    let todoCount = 0
이부분은 객체로 묶어서 담아두는 게 더 나을 거 같네요.

2019-04-22 05:11 UTC, nigayo commented on step4/step4-2/todoApp.js
> +const printCommandResult = (command, updatedList, inputReadline, showAllMsgTimeout, updateMsgTimeout) => {
여러파라미터를 받은것은 좋고요. 참고로 파라미터가 많아지면 객체로 받는 것도 생각해보세요.
그리고 파라미터의 이름이 동사+명사로 되어 있는 것은 함수같아서 어색하고요. (timeoutForUpdate 이라고 하는 게 나을 수 있죠)

2019-04-22 05:11 UTC, merged

2019-04-22 09:07 UTC, sonypark commented on step4/step4-2/todoApp.js
> +const printCommandResult = (command, updatedList, inputReadline, showAllMsgTimeout, updateMsgTimeout) => {
네 객체로 받는 방법도 좋을 것 같네요!
변수 이름은 명사형으로 바꾸겠습니다 :)

2019-04-22 09:07 UTC, sonypark commented on step4/step4-2/todoApp.js
> +    let todoCount = 0
네 변경하겠습니다!