Step4-2 잉글비&Seldev
code-squad/javascript-todo pull request #97
Opened 2019-04-19 07:20 UTC by sel-dev

2019-04-19 09:24 UTC, crongro requested changes
리뷰참고해서 조금 더 수정하면 좋겠습니다.

2019-04-19 09:24 UTC, crongro commented on todo.js
> +    return todos.some(idCheck);
idCheck보다는 checkId 가 보기 좋은 이름 같죠?

2019-04-19 09:24 UTC, crongro commented on todo.js
> +    const max = 10000;
10000을 파라미터로 받는게 좋아보이는데, 왜 그럴까요?

2019-04-19 09:24 UTC, crongro commented on todo.js
> +    const todosSortedByStatus = {};
네 이부분은 for-of를 써서 잘 구현했는데요.
배열의 고차함수들(filter, map 등)을 활용하는 방법도 있겠죠.
이 코드를 그렇게 연습삼아 수정해보세요.

2019-04-19 09:24 UTC, crongro commented on todo.js
> +    let res = "현재상태는";
res 변수를 block scope로 옮기는 게 어떨까요?

2019-04-19 09:24 UTC, crongro commented on todo.js
> +    todos.forEach((todo) => {
forEach이외 다른 메서드를 사용해서 의도를 더 구체적으로 표현할수 있을 듯.

2019-04-19 09:24 UTC, crongro commented on todo.js
> +    todo.status = "todo";
지금 todo.xxx, todo.xx 이렇게 객체를 만들고 있는데요.
 생성자패턴으로 이부분을 좀 낫게 보일수도 있을거에요. 객체에 대해서는 곧 배우는데, 미리 찾아보셔도 좋을 듯.

2019-04-19 09:24 UTC, crongro commented on todo.js
> +        },3000)
3000도 인자로 받으면 조금더 범용적인 함수가 되겠죠?

2019-04-19 09:24 UTC, nigayo commented on todo.js
> +            setTimeout(()=> {
참고로 나중에 이렇게 callback-callback 이 중첩된 코드를 좀더 보기 좋게 바꾸는 패턴을 적용할 수 있을거에요.

2019-04-19 09:24 UTC, nigayo commented on todo.js
> +            console.log("ID가 목록에 없습니다.");
console객체에 디버깅용도로 다른 메서드도 있다허이다.

2019-04-22 05:17 UTC, gminiy commented on todo.js
> +    const max = 10000;
max를 parameter로 사용하면 재사용에 용이한 함수가 됩니다.

2019-04-22 05:44 UTC, gminiy commented on todo.js
> +    let res = "현재상태는";
res를 각 블럭별로 선언하고 무엇의 result인지 명확하게 표현하기 위해 이름을 변경하였습니다.(resultOfAll, resultOfStatus)

2019-04-22 05:52 UTC, gminiy commented on todo.js
> +    todos.forEach((todo) => {
find 메서드를 사용해서 입력받은 id와 동일한 id를 갖는 객체를 찾는다는 의도를 표현했습니다.

2019-04-22 06:37 UTC, gminiy commented on todo.js
> +    const todosSortedByStatus = {};
filter 를 사용해서 의도를 좀더 분명하게 표현해봤습니다.

2019-04-22 07:05 UTC, gminiy commented on todo.js
> +    todo.status = "todo";
makeTodo class를 만들어서 생성자패턴을 사용해보았습니다.

2019-04-22 07:55 UTC, gminiy commented on todo.js
> +        },3000)
update 결과 출력 시간을 인자(setTime)로 받아 사용하게 바꾸었습니다.

2019-04-22 07:56 UTC, gminiy commented on todo.js
> +            setTimeout(()=> {
중복되는 setTimeout을 모듈화하여 조금더 보기좋게 만들었습니다.

2019-04-22 08:20 UTC, gminiy commented on todo.js
> +            console.log("ID가 목록에 없습니다.");
1. console.trace() : console이 실행될때의 stack 을 같이 확인할 수 있다.
2. console.time(), console.timeEnd() : 수행시간을 check할때 사용
3. console.memory() : memory status를 확인할 수 있다.
4. console.count() : recursive function 과 같은 반복동작시 그 코드가 얼마나 실행되었는지 카운트할 수 있다.
5. console.assert() : conditional 하게 log를 출력할수 있다.(매우 유용할듯?)
6. console.group() : log가 엄청 많을때 한꺼번에 모아서 출력할 수 있다.
7. console.table() : 객체 출력시 더 보기좋게 table로 출력할 수 있다.
* 참조 : https://medium.com/appsflyer/10-tips-for-javascript-debugging-like-a-pro-with-console-7140027eb5f6

debugging에 유용하게 사용할 수 있는 console 객체의 method를 학습했습니다.

2019-04-22 08:21 UTC, gminiy commented on todo.js
> +    return todos.some(idCheck);
naming 할때 동사+명사 패턴이 더 보기 좋은 이름인것 같습니다. 이름 변경하였습니다.

2019-04-22 08:45 UTC, crongro approved these changes
네 수정 잘 하셨어요.

승인합니다~!

2019-04-22 08:45 UTC, nigayo commented on todo.js
> +        if(!(tag === undefined)) this.tag = tag.match(/[a-z0-9]+/g);
좀더 쉽게 표현.
if(tag)  이렇게만 해도 false인 상황을 피하니까 괜찮을 거 같네요. 
(false로 표현되는 것은 undefined, null.. 등등 더 알아보세요)

2019-04-22 08:45 UTC, nigayo commented on todo.js
> +const update = (id, inputStatus, setTime = 3000) => {
default parameter 잘 썼어요!

2019-04-22 08:45 UTC, merged