190419 JS step 4-2 Michelle & Jake
code-squad/javascript-todo pull request #99
Opened 2019-04-19 07:56 UTC by leehwarang

2019-04-20 00:13 UTC, nigayo commented
다음번 미션에서는 커밋도 잘하시고, 커밋메시지 컨벤션도 찾아서 시도해보세요.

2019-04-20 00:24 UTC, crongro requested changes
배열메서드들을 아주 잘 활용해서 좋네요.

지금코드보다 if/else를 조금 줄일 수 있을지 살펴보세요.
나머지 리뷰내용도 참고해서 조금 수정해보세요.

2019-04-20 00:24 UTC, nigayo commented on step4-2.js
> +let todos = [];
const를 먼저 쓰고, const를 쓰면 안되는 상황(뭘까요?)이 오면 let를 쓰는 게 좋겠죠. 
var 를 포함해서 좀더 공부해보세요.

2019-04-20 00:24 UTC, nigayo commented on todoFunction.js
> +function addImpl(todos, name, tag, status = "todo") {
Impl..이 구현?인가요? 좀더 명확한 표현이면 좋을 듯. 이 함수의 의도를 생각해서 네이밍해보세요.

2019-04-20 00:24 UTC, nigayo commented on todoFunction.js
> +  const helpMessage = `사용법
사용하기 좋은 설명 좋네요 👍

2019-04-20 00:24 UTC, nigayo commented on todoFunction.js
> +    todos.push(newtodo);
참고.
배열을 추가하는 방법중 concat이나 spread operator , 그리고 지금 방법과의 차이를 한번 찾아보세요.
모두 가능한데 생각보다 큰 차이도 있을겁니다.

2019-04-20 00:24 UTC, nigayo commented on todoFunction.js
> +    } else {
분기문은 코드의 중첩을 만들어서 복잡한 상황에선 더욱더 코드보기가 안좋죠.
여기 else문이 꼭 필요할까요?  없애려면 어떻게 해야할까요?

2019-04-20 00:24 UTC, nigayo commented on todoFunction.js
> +      .map(v => `${v[0]} : ${v[1]}`)
entires/map/join. 잘했요.

2019-04-20 00:24 UTC, nigayo commented on todoFunction.js
> +  let result;
여기서 result = []  이렇게 배열임을 표현하는 것도 괜찮을 거 같네요.

2019-04-20 12:59 UTC, cocahack commented on step4-2.js
> +let todos = [];
delete 연산을 구현할 때 filter를 사용하려고 const에서 let으로 바꿨습니다. 이 방법 대신에 todos 배열을 const로 바꾸고 element를 삭제하는 것은 indexof와 splice를 사용하는 방법으로 바꿔보겠습니다.

2019-04-20 12:59 UTC, cocahack commented on todoFunction.js
> +function addImpl(todos, name, tag, status = "todo") {
수정하겠습니다.. 너무 대충 지은거 같네요 ㅠㅠ;

2019-04-20 12:59 UTC, cocahack commented on todoFunction.js
> +    todos.push(newtodo);
push는 원본을 변경하고 concat은 새로운 배열을 반환하는 것 까진 알고 있었는데, spread operator도 배열을 결합하는데에 쓸 수 있었네요. 이 방법도 새로운 배열을 만드는 걸로 보이네요. 정말 유용한 연산자같아요.

2019-04-20 12:59 UTC, cocahack commented on todoFunction.js
> +    } else {
undefined가 아닐때만 연산을 수행하면 되니 else를 쓸 이유가 없네요. 수정하겠습니다~

2019-04-20 12:59 UTC, cocahack commented on todoFunction.js
> +  let result;
배열 선언과 동시에 값을 할당하는 습관을 들여야할 것 같습니다..

2019-04-25 04:44 UTC, crongro approved these changes
수고하셨어요. 머지합니다.

2019-04-25 04:44 UTC, nigayo commented on todoFunction.js
>  module.exports = {
key/value가 같으면 생략해서 객체를 표현할 수 있습니다.
const obj = {add, delete, update...}

2019-04-25 04:45 UTC, merged